namespace QuanLyDuLich.Forms {
 partial class FrmChuyenLe {
 private System.ComponentModel.IContainer components=null;
 protected override void Dispose(bool disposing){if(disposing && components!=null)components.Dispose();base.Dispose(disposing);}
 private void InitializeComponent(){
  this.label0=new System.Windows.Forms.Label();
  this.txtMa=new System.Windows.Forms.TextBox();
  this.label2=new System.Windows.Forms.Label();
  this.cboTour=new System.Windows.Forms.ComboBox();
  this.label4=new System.Windows.Forms.Label();
  this.dtDi=new System.Windows.Forms.DateTimePicker();
  this.label6=new System.Windows.Forms.Label();
  this.lblNgayVe=new System.Windows.Forms.Label();
  this.label8=new System.Windows.Forms.Label();
  this.txtDon=new System.Windows.Forms.TextBox();
  this.btnThem=new System.Windows.Forms.Button();
  this.btnDongDK=new System.Windows.Forms.Button();
  this.dgv=new System.Windows.Forms.DataGridView();
  this.btnDong=new System.Windows.Forms.Button();
  this.SuspendLayout();
  this.label0.Name="label0";
  this.label0.Location=new System.Drawing.Point(25,28);
  this.label0.Size=new System.Drawing.Size(100,25);
  this.label0.TabIndex=0;
  this.label0.Text="Mã chuyến:";
  this.Controls.Add(this.label0);
  this.txtMa.Name="txtMa";
  this.txtMa.Location=new System.Drawing.Point(125,25);
  this.txtMa.Size=new System.Drawing.Size(150,25);
  this.txtMa.TabIndex=1;
  this.txtMa.MaxLength = 1500;
  this.Controls.Add(this.txtMa);
  this.label2.Name="label2";
  this.label2.Location=new System.Drawing.Point(330,28);
  this.label2.Size=new System.Drawing.Size(70,25);
  this.label2.TabIndex=2;
  this.label2.Text="Tour:";
  this.Controls.Add(this.label2);
  this.cboTour.Name="cboTour";
  this.cboTour.Location=new System.Drawing.Point(400,25);
  this.cboTour.Size=new System.Drawing.Size(405,25);
  this.cboTour.TabIndex=3;
  this.cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.Controls.Add(this.cboTour);
  this.label4.Name="label4";
  this.label4.Location=new System.Drawing.Point(25,68);
  this.label4.Size=new System.Drawing.Size(100,25);
  this.label4.TabIndex=4;
  this.label4.Text="Ngày đi:";
  this.Controls.Add(this.label4);
  this.dtDi.Name="dtDi";
  this.dtDi.Location=new System.Drawing.Point(125,65);
  this.dtDi.Size=new System.Drawing.Size(160,25);
  this.dtDi.TabIndex=5;
  this.dtDi.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
  this.dtDi.CustomFormat = "dd/MM/yyyy";
  this.Controls.Add(this.dtDi);
  this.label6.Name="label6";
  this.label6.Location=new System.Drawing.Point(330,68);
  this.label6.Size=new System.Drawing.Size(80,25);
  this.label6.TabIndex=6;
  this.label6.Text="Ngày về:";
  this.Controls.Add(this.label6);
  this.lblNgayVe.Name="lblNgayVe";
  this.lblNgayVe.Location=new System.Drawing.Point(415,68);
  this.lblNgayVe.Size=new System.Drawing.Size(300,25);
  this.lblNgayVe.TabIndex=7;
  this.lblNgayVe.Text="-";
  this.lblNgayVe.Font = new System.Drawing.Font("Segoe UI",9F,System.Drawing.FontStyle.Bold);
  this.Controls.Add(this.lblNgayVe);
  this.label8.Name="label8";
  this.label8.Location=new System.Drawing.Point(25,108);
  this.label8.Size=new System.Drawing.Size(100,25);
  this.label8.TabIndex=8;
  this.label8.Text="Địa điểm đón:";
  this.Controls.Add(this.label8);
  this.txtDon.Name="txtDon";
  this.txtDon.Location=new System.Drawing.Point(125,105);
  this.txtDon.Size=new System.Drawing.Size(520,25);
  this.txtDon.TabIndex=9;
  this.txtDon.MaxLength = 1500;
  this.Controls.Add(this.txtDon);
  this.btnThem.Name="btnThem";
  this.btnThem.Location=new System.Drawing.Point(760,100);
  this.btnThem.Size=new System.Drawing.Size(100,34);
  this.btnThem.TabIndex=10;
  this.btnThem.Text="Tạo chuyến";
  this.btnThem.UseVisualStyleBackColor = false;
  this.btnThem.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnThem.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnThem.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnThem);
  this.btnDongDK.Name="btnDongDK";
  this.btnDongDK.Location=new System.Drawing.Point(870,100);
  this.btnDongDK.Size=new System.Drawing.Size(110,34);
  this.btnDongDK.TabIndex=11;
  this.btnDongDK.Text="Đóng đăng ký";
  this.btnDongDK.UseVisualStyleBackColor = false;
  this.btnDongDK.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDongDK.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDongDK.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDongDK);
  this.dgv.Name="dgv";
  this.dgv.Location=new System.Drawing.Point(25,155);
  this.dgv.Size=new System.Drawing.Size(950,425);
  this.dgv.TabIndex=12;
  this.dgv.ReadOnly = true;
  this.dgv.AllowUserToAddRows = false;
  this.dgv.AllowUserToDeleteRows = false;
  this.dgv.MultiSelect = false;
  this.dgv.RowHeadersVisible = true;
  this.dgv.RowHeadersWidth = 28;
  this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgv.BackgroundColor = System.Drawing.Color.White;
  this.dgv.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgv.EnableHeadersVisualStyles = false;
  this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgv.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgv.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgv.ColumnHeadersHeight = 26;
  this.Controls.Add(this.dgv);
  this.btnDong.Name="btnDong";
  this.btnDong.Location=new System.Drawing.Point(865,595);
  this.btnDong.Size=new System.Drawing.Size(110,32);
  this.btnDong.TabIndex=13;
  this.btnDong.Text="Đóng";
  this.btnDong.UseVisualStyleBackColor = false;
  this.btnDong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDong);
  this.AutoScaleDimensions=new System.Drawing.SizeF(7F,15F);
  this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
  this.ClientSize=new System.Drawing.Size(1000,640);
  this.Font=new System.Drawing.Font("Segoe UI",9F);
  this.BackColor=System.Drawing.Color.FromArgb(240,240,240);
  this.StartPosition=System.Windows.Forms.FormStartPosition.CenterParent;
  this.Name="FrmChuyenLe";
  this.Text="Lịch chuyến khách lẻ";
  this.Load+=new System.EventHandler(this.FrmChuyenLe_Load);
  this.ResumeLayout(false);
  this.PerformLayout();
 }
 private System.Windows.Forms.Label label0;
 private System.Windows.Forms.TextBox txtMa;
 private System.Windows.Forms.Label label2;
 private System.Windows.Forms.ComboBox cboTour;
 private System.Windows.Forms.Label label4;
 private System.Windows.Forms.DateTimePicker dtDi;
 private System.Windows.Forms.Label label6;
 private System.Windows.Forms.Label lblNgayVe;
 private System.Windows.Forms.Label label8;
 private System.Windows.Forms.TextBox txtDon;
 private System.Windows.Forms.Button btnThem;
 private System.Windows.Forms.Button btnDongDK;
 private System.Windows.Forms.DataGridView dgv;
 private System.Windows.Forms.Button btnDong;
 }
}