namespace QuanLyDuLich.Forms {
 partial class FrmDangKyDoan {
 private System.ComponentModel.IContainer components=null;
 protected override void Dispose(bool disposing){if(disposing && components!=null)components.Dispose();base.Dispose(disposing);}
 private void InitializeComponent(){
  this.grpDoan=new System.Windows.Forms.GroupBox();
  this.grpDangKy=new System.Windows.Forms.GroupBox();
  this.label2=new System.Windows.Forms.Label();
  this.txtMaDoan=new System.Windows.Forms.TextBox();
  this.label4=new System.Windows.Forms.Label();
  this.txtTen=new System.Windows.Forms.TextBox();
  this.label6=new System.Windows.Forms.Label();
  this.txtDia=new System.Windows.Forms.TextBox();
  this.label8=new System.Windows.Forms.Label();
  this.txtPhone=new System.Windows.Forms.TextBox();
  this.label10=new System.Windows.Forms.Label();
  this.txtDaiDien=new System.Windows.Forms.TextBox();
  this.label12=new System.Windows.Forms.Label();
  this.txtSo=new System.Windows.Forms.TextBox();
  this.label14=new System.Windows.Forms.Label();
  this.cboTour=new System.Windows.Forms.ComboBox();
  this.label16=new System.Windows.Forms.Label();
  this.dtDi=new System.Windows.Forms.DateTimePicker();
  this.label18=new System.Windows.Forms.Label();
  this.numNguoi=new System.Windows.Forms.NumericUpDown();
  this.label20=new System.Windows.Forms.Label();
  this.txtDon=new System.Windows.Forms.TextBox();
  this.label22=new System.Windows.Forms.Label();
  this.numCoc=new System.Windows.Forms.NumericUpDown();
  this.chkBH=new System.Windows.Forms.CheckBox();
  this.label25=new System.Windows.Forms.Label();
  this.lblKetThuc=new System.Windows.Forms.Label();
  this.label27=new System.Windows.Forms.Label();
  this.lblTong=new System.Windows.Forms.Label();
  this.label29=new System.Windows.Forms.Label();
  this.dgvTV=new System.Windows.Forms.DataGridView();
  this.btnDangKy=new System.Windows.Forms.Button();
  this.btnHuy=new System.Windows.Forms.Button();
  this.label33=new System.Windows.Forms.Label();
  this.dgv=new System.Windows.Forms.DataGridView();
  this.btnDong=new System.Windows.Forms.Button();
  this.SuspendLayout();
  this.grpDoan.Name="grpDoan";
  this.grpDoan.Location=new System.Drawing.Point(20,15);
  this.grpDoan.Size=new System.Drawing.Size(515,225);
  this.grpDoan.TabIndex=0;
  this.grpDoan.Text="Thông tin đoàn khách";
  this.Controls.Add(this.grpDoan);
  this.grpDangKy.Name="grpDangKy";
  this.grpDangKy.Location=new System.Drawing.Point(550,15);
  this.grpDangKy.Size=new System.Drawing.Size(530,225);
  this.grpDangKy.TabIndex=1;
  this.grpDangKy.Text="Đăng ký tour";
  this.Controls.Add(this.grpDangKy);
  this.label2.Name="label2";
  this.label2.Location=new System.Drawing.Point(15,33);
  this.label2.Size=new System.Drawing.Size(110,25);
  this.label2.TabIndex=2;
  this.label2.Text="Mã đoàn:";
  this.grpDoan.Controls.Add(this.label2);
  this.txtMaDoan.Name="txtMaDoan";
  this.txtMaDoan.Location=new System.Drawing.Point(125,30);
  this.txtMaDoan.Size=new System.Drawing.Size(150,25);
  this.txtMaDoan.TabIndex=3;
  this.txtMaDoan.MaxLength = 1500;
  this.grpDoan.Controls.Add(this.txtMaDoan);
  this.label4.Name="label4";
  this.label4.Location=new System.Drawing.Point(15,70);
  this.label4.Size=new System.Drawing.Size(110,25);
  this.label4.TabIndex=4;
  this.label4.Text="Cơ quan / gia đình:";
  this.grpDoan.Controls.Add(this.label4);
  this.txtTen.Name="txtTen";
  this.txtTen.Location=new System.Drawing.Point(125,67);
  this.txtTen.Size=new System.Drawing.Size(365,25);
  this.txtTen.TabIndex=5;
  this.txtTen.MaxLength = 1500;
  this.grpDoan.Controls.Add(this.txtTen);
  this.label6.Name="label6";
  this.label6.Location=new System.Drawing.Point(15,107);
  this.label6.Size=new System.Drawing.Size(110,25);
  this.label6.TabIndex=6;
  this.label6.Text="Địa chỉ:";
  this.grpDoan.Controls.Add(this.label6);
  this.txtDia.Name="txtDia";
  this.txtDia.Location=new System.Drawing.Point(125,104);
  this.txtDia.Size=new System.Drawing.Size(365,25);
  this.txtDia.TabIndex=7;
  this.txtDia.MaxLength = 1500;
  this.grpDoan.Controls.Add(this.txtDia);
  this.label8.Name="label8";
  this.label8.Location=new System.Drawing.Point(15,144);
  this.label8.Size=new System.Drawing.Size(110,25);
  this.label8.TabIndex=8;
  this.label8.Text="Điện thoại:";
  this.grpDoan.Controls.Add(this.label8);
  this.txtPhone.Name="txtPhone";
  this.txtPhone.Location=new System.Drawing.Point(125,141);
  this.txtPhone.Size=new System.Drawing.Size(200,25);
  this.txtPhone.TabIndex=9;
  this.txtPhone.MaxLength = 1500;
  this.grpDoan.Controls.Add(this.txtPhone);
  this.label10.Name="label10";
  this.label10.Location=new System.Drawing.Point(15,181);
  this.label10.Size=new System.Drawing.Size(110,25);
  this.label10.TabIndex=10;
  this.label10.Text="Người đại diện:";
  this.grpDoan.Controls.Add(this.label10);
  this.txtDaiDien.Name="txtDaiDien";
  this.txtDaiDien.Location=new System.Drawing.Point(125,178);
  this.txtDaiDien.Size=new System.Drawing.Size(365,25);
  this.txtDaiDien.TabIndex=11;
  this.txtDaiDien.MaxLength = 1500;
  this.grpDoan.Controls.Add(this.txtDaiDien);
  this.label12.Name="label12";
  this.label12.Location=new System.Drawing.Point(15,33);
  this.label12.Size=new System.Drawing.Size(75,25);
  this.label12.TabIndex=12;
  this.label12.Text="Số phiếu:";
  this.grpDangKy.Controls.Add(this.label12);
  this.txtSo.Name="txtSo";
  this.txtSo.Location=new System.Drawing.Point(90,30);
  this.txtSo.Size=new System.Drawing.Size(140,25);
  this.txtSo.TabIndex=13;
  this.txtSo.MaxLength = 1500;
  this.grpDangKy.Controls.Add(this.txtSo);
  this.label14.Name="label14";
  this.label14.Location=new System.Drawing.Point(265,33);
  this.label14.Size=new System.Drawing.Size(55,25);
  this.label14.TabIndex=14;
  this.label14.Text="Tour:";
  this.grpDangKy.Controls.Add(this.label14);
  this.cboTour.Name="cboTour";
  this.cboTour.Location=new System.Drawing.Point(320,30);
  this.cboTour.Size=new System.Drawing.Size(195,25);
  this.cboTour.TabIndex=15;
  this.cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.grpDangKy.Controls.Add(this.cboTour);
  this.label16.Name="label16";
  this.label16.Location=new System.Drawing.Point(15,70);
  this.label16.Size=new System.Drawing.Size(75,25);
  this.label16.TabIndex=16;
  this.label16.Text="Ngày đi:";
  this.grpDangKy.Controls.Add(this.label16);
  this.dtDi.Name="dtDi";
  this.dtDi.Location=new System.Drawing.Point(90,67);
  this.dtDi.Size=new System.Drawing.Size(160,25);
  this.dtDi.TabIndex=17;
  this.dtDi.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
  this.dtDi.CustomFormat = "dd/MM/yyyy";
  this.grpDangKy.Controls.Add(this.dtDi);
  this.label18.Name="label18";
  this.label18.Location=new System.Drawing.Point(275,70);
  this.label18.Size=new System.Drawing.Size(85,25);
  this.label18.TabIndex=18;
  this.label18.Text="Số người:";
  this.grpDangKy.Controls.Add(this.label18);
  this.numNguoi.Name="numNguoi";
  this.numNguoi.Location=new System.Drawing.Point(360,67);
  this.numNguoi.Size=new System.Drawing.Size(100,25);
  this.numNguoi.TabIndex=19;
  this.numNguoi.Minimum = 13M;
  this.numNguoi.Maximum = 10000M;
  this.numNguoi.Value = 15M;
  this.numNguoi.ThousandsSeparator = true;
  this.grpDangKy.Controls.Add(this.numNguoi);
  this.label20.Name="label20";
  this.label20.Location=new System.Drawing.Point(15,107);
  this.label20.Size=new System.Drawing.Size(100,25);
  this.label20.TabIndex=20;
  this.label20.Text="Địa điểm đón:";
  this.grpDangKy.Controls.Add(this.label20);
  this.txtDon.Name="txtDon";
  this.txtDon.Location=new System.Drawing.Point(115,104);
  this.txtDon.Size=new System.Drawing.Size(380,25);
  this.txtDon.TabIndex=21;
  this.txtDon.MaxLength = 1500;
  this.grpDangKy.Controls.Add(this.txtDon);
  this.label22.Name="label22";
  this.label22.Location=new System.Drawing.Point(15,144);
  this.label22.Size=new System.Drawing.Size(75,25);
  this.label22.TabIndex=22;
  this.label22.Text="Tiền cọc:";
  this.grpDangKy.Controls.Add(this.label22);
  this.numCoc.Name="numCoc";
  this.numCoc.Location=new System.Drawing.Point(90,141);
  this.numCoc.Size=new System.Drawing.Size(190,25);
  this.numCoc.TabIndex=23;
  this.numCoc.Minimum = 0M;
  this.numCoc.Maximum = 999999999999M;
  this.numCoc.Value = 30000000M;
  this.numCoc.ThousandsSeparator = true;
  this.grpDangKy.Controls.Add(this.numCoc);
  this.chkBH.Name="chkBH";
  this.chkBH.Location=new System.Drawing.Point(310,141);
  this.chkBH.Size=new System.Drawing.Size(175,25);
  this.chkBH.TabIndex=24;
  this.chkBH.Text="Mua bảo hiểm";
  this.chkBH.Checked = false;
  this.grpDangKy.Controls.Add(this.chkBH);
  this.label25.Name="label25";
  this.label25.Location=new System.Drawing.Point(15,185);
  this.label25.Size=new System.Drawing.Size(80,25);
  this.label25.TabIndex=25;
  this.label25.Text="Kết thúc:";
  this.grpDangKy.Controls.Add(this.label25);
  this.lblKetThuc.Name="lblKetThuc";
  this.lblKetThuc.Location=new System.Drawing.Point(95,185);
  this.lblKetThuc.Size=new System.Drawing.Size(160,25);
  this.lblKetThuc.TabIndex=26;
  this.lblKetThuc.Text="-";
  this.lblKetThuc.Font = new System.Drawing.Font("Segoe UI",9F,System.Drawing.FontStyle.Bold);
  this.grpDangKy.Controls.Add(this.lblKetThuc);
  this.label27.Name="label27";
  this.label27.Location=new System.Drawing.Point(260,185);
  this.label27.Size=new System.Drawing.Size(100,25);
  this.label27.TabIndex=27;
  this.label27.Text="Tổng dự kiến:";
  this.grpDangKy.Controls.Add(this.label27);
  this.lblTong.Name="lblTong";
  this.lblTong.Location=new System.Drawing.Point(370,185);
  this.lblTong.Size=new System.Drawing.Size(145,25);
  this.lblTong.TabIndex=28;
  this.lblTong.Text="0 đ";
  this.lblTong.ForeColor = System.Drawing.Color.DarkRed;
  this.lblTong.Font = new System.Drawing.Font("Segoe UI",9F,System.Drawing.FontStyle.Bold);
  this.grpDangKy.Controls.Add(this.lblTong);
  this.label29.Name="label29";
  this.label29.Location=new System.Drawing.Point(20,255);
  this.label29.Size=new System.Drawing.Size(1060,25);
  this.label29.TabIndex=29;
  this.label29.Text="Danh sách người cùng đi (bắt buộc đủ số người khi mua bảo hiểm):";
  this.Controls.Add(this.label29);
  this.dgvTV.Name="dgvTV";
  this.dgvTV.Location=new System.Drawing.Point(20,285);
  this.dgvTV.Size=new System.Drawing.Size(1060,185);
  this.dgvTV.TabIndex=30;
  this.dgvTV.ReadOnly = false;
  this.dgvTV.AllowUserToAddRows = true;
  this.dgvTV.AllowUserToDeleteRows = true;
  this.dgvTV.MultiSelect = false;
  this.dgvTV.RowHeadersVisible = true;
  this.dgvTV.RowHeadersWidth = 28;
  this.dgvTV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvTV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvTV.BackgroundColor = System.Drawing.Color.White;
  this.dgvTV.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvTV.EnableHeadersVisualStyles = false;
  this.dgvTV.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvTV.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvTV.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvTV.ColumnHeadersHeight = 26;
  this.Controls.Add(this.dgvTV);
  this.btnDangKy.Name="btnDangKy";
  this.btnDangKy.Location=new System.Drawing.Point(725,485);
  this.btnDangKy.Size=new System.Drawing.Size(170,34);
  this.btnDangKy.TabIndex=31;
  this.btnDangKy.Text="Lập phiếu đăng ký";
  this.btnDangKy.UseVisualStyleBackColor = false;
  this.btnDangKy.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDangKy.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDangKy.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDangKy);
  this.btnHuy.Name="btnHuy";
  this.btnHuy.Location=new System.Drawing.Point(910,485);
  this.btnHuy.Size=new System.Drawing.Size(170,34);
  this.btnHuy.TabIndex=32;
  this.btnHuy.Text="Hủy phiếu (mất cọc)";
  this.btnHuy.UseVisualStyleBackColor = false;
  this.btnHuy.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnHuy.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnHuy.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnHuy);
  this.label33.Name="label33";
  this.label33.Location=new System.Drawing.Point(20,535);
  this.label33.Size=new System.Drawing.Size(1060,25);
  this.label33.TabIndex=33;
  this.label33.Text="Các phiếu đăng ký đoàn:";
  this.Controls.Add(this.label33);
  this.dgv.Name="dgv";
  this.dgv.Location=new System.Drawing.Point(20,565);
  this.dgv.Size=new System.Drawing.Size(1060,200);
  this.dgv.TabIndex=34;
  this.dgv.ReadOnly = true;
  this.dgv.AllowUserToAddRows = false;
  this.dgv.AllowUserToDeleteRows = false;
  this.dgv.MultiSelect = false;
  this.dgv.RowHeadersVisible = true;
  this.dgv.RowHeadersWidth = 28;
  this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgv.BackgroundColor = System.Drawing.Color.White;
  this.dgv.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgv.EnableHeadersVisualStyles = false;
  this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgv.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgv.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgv.ColumnHeadersHeight = 26;
  this.Controls.Add(this.dgv);
  this.btnDong.Name="btnDong";
  this.btnDong.Location=new System.Drawing.Point(970,780);
  this.btnDong.Size=new System.Drawing.Size(110,32);
  this.btnDong.TabIndex=35;
  this.btnDong.Text="Đóng";
  this.btnDong.UseVisualStyleBackColor = false;
  this.btnDong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDong);
  this.AutoScaleDimensions=new System.Drawing.SizeF(7F,15F);
  this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
  this.ClientSize=new System.Drawing.Size(1100,820);
  this.Font=new System.Drawing.Font("Segoe UI",9F);
  this.BackColor=System.Drawing.Color.FromArgb(240,240,240);
  this.StartPosition=System.Windows.Forms.FormStartPosition.CenterParent;
  this.Name="FrmDangKyDoan";
  this.Text="Phiếu đăng ký theo đoàn";
  this.Load+=new System.EventHandler(this.FrmDangKyDoan_Load);
  this.ResumeLayout(false);
  this.PerformLayout();
 }
 private System.Windows.Forms.GroupBox grpDoan;
 private System.Windows.Forms.GroupBox grpDangKy;
 private System.Windows.Forms.Label label2;
 private System.Windows.Forms.TextBox txtMaDoan;
 private System.Windows.Forms.Label label4;
 private System.Windows.Forms.TextBox txtTen;
 private System.Windows.Forms.Label label6;
 private System.Windows.Forms.TextBox txtDia;
 private System.Windows.Forms.Label label8;
 private System.Windows.Forms.TextBox txtPhone;
 private System.Windows.Forms.Label label10;
 private System.Windows.Forms.TextBox txtDaiDien;
 private System.Windows.Forms.Label label12;
 private System.Windows.Forms.TextBox txtSo;
 private System.Windows.Forms.Label label14;
 private System.Windows.Forms.ComboBox cboTour;
 private System.Windows.Forms.Label label16;
 private System.Windows.Forms.DateTimePicker dtDi;
 private System.Windows.Forms.Label label18;
 private System.Windows.Forms.NumericUpDown numNguoi;
 private System.Windows.Forms.Label label20;
 private System.Windows.Forms.TextBox txtDon;
 private System.Windows.Forms.Label label22;
 private System.Windows.Forms.NumericUpDown numCoc;
 private System.Windows.Forms.CheckBox chkBH;
 private System.Windows.Forms.Label label25;
 private System.Windows.Forms.Label lblKetThuc;
 private System.Windows.Forms.Label label27;
 private System.Windows.Forms.Label lblTong;
 private System.Windows.Forms.Label label29;
 private System.Windows.Forms.DataGridView dgvTV;
 private System.Windows.Forms.Button btnDangKy;
 private System.Windows.Forms.Button btnHuy;
 private System.Windows.Forms.Label label33;
 private System.Windows.Forms.DataGridView dgv;
 private System.Windows.Forms.Button btnDong;
 }
}