namespace QuanLyDuLich.Forms {
 partial class FrmDanhMuc {
 private System.ComponentModel.IContainer components=null;
 protected override void Dispose(bool disposing){if(disposing && components!=null)components.Dispose();base.Dispose(disposing);}
 private void InitializeComponent(){
  this.tabs=new System.Windows.Forms.TabControl();
  this.tabPT=new System.Windows.Forms.TabPage();
  this.tabDB=new System.Windows.Forms.TabPage();
  this.tabHDV=new System.Windows.Forms.TabPage();
  this.tabTQ=new System.Windows.Forms.TabPage();
  this.dgvPT=new System.Windows.Forms.DataGridView();
  this.label6=new System.Windows.Forms.Label();
  this.txtPTMa=new System.Windows.Forms.TextBox();
  this.label8=new System.Windows.Forms.Label();
  this.txtPTTen=new System.Windows.Forms.TextBox();
  this.label10=new System.Windows.Forms.Label();
  this.txtPTNote=new System.Windows.Forms.TextBox();
  this.btnThemPT=new System.Windows.Forms.Button();
  this.dgvDB=new System.Windows.Forms.DataGridView();
  this.label14=new System.Windows.Forms.Label();
  this.txtDBMa=new System.Windows.Forms.TextBox();
  this.label16=new System.Windows.Forms.Label();
  this.txtDBTen=new System.Windows.Forms.TextBox();
  this.label18=new System.Windows.Forms.Label();
  this.txtDBDia=new System.Windows.Forms.TextBox();
  this.label20=new System.Windows.Forms.Label();
  this.txtDBPhone=new System.Windows.Forms.TextBox();
  this.btnThemDB=new System.Windows.Forms.Button();
  this.dgvHDV=new System.Windows.Forms.DataGridView();
  this.label24=new System.Windows.Forms.Label();
  this.txtHDVMa=new System.Windows.Forms.TextBox();
  this.label26=new System.Windows.Forms.Label();
  this.txtHDVTen=new System.Windows.Forms.TextBox();
  this.label28=new System.Windows.Forms.Label();
  this.txtHDVPhone=new System.Windows.Forms.TextBox();
  this.label30=new System.Windows.Forms.Label();
  this.numLuong=new System.Windows.Forms.NumericUpDown();
  this.btnThemHDV=new System.Windows.Forms.Button();
  this.dgvTQ=new System.Windows.Forms.DataGridView();
  this.label34=new System.Windows.Forms.Label();
  this.txtTQMa=new System.Windows.Forms.TextBox();
  this.label36=new System.Windows.Forms.Label();
  this.txtTQTen=new System.Windows.Forms.TextBox();
  this.label38=new System.Windows.Forms.Label();
  this.txtTQDia=new System.Windows.Forms.TextBox();
  this.label40=new System.Windows.Forms.Label();
  this.txtTQNoiDung=new System.Windows.Forms.TextBox();
  this.label42=new System.Windows.Forms.Label();
  this.txtTQYNghia=new System.Windows.Forms.TextBox();
  this.btnThemTQ=new System.Windows.Forms.Button();
  this.btnDong=new System.Windows.Forms.Button();
  this.SuspendLayout();
  this.tabs.Name="tabs";
  this.tabs.Location=new System.Drawing.Point(20,15);
  this.tabs.Size=new System.Drawing.Size(960,560);
  this.tabs.TabIndex=0;
  this.Controls.Add(this.tabs);
  this.tabPT.Name="tabPT";
  this.tabPT.Location=new System.Drawing.Point(0,0);
  this.tabPT.Size=new System.Drawing.Size(950,535);
  this.tabPT.TabIndex=1;
  this.tabPT.Text="Phương tiện";
  this.tabPT.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabPT);
  this.tabDB.Name="tabDB";
  this.tabDB.Location=new System.Drawing.Point(0,0);
  this.tabDB.Size=new System.Drawing.Size(950,535);
  this.tabDB.TabIndex=2;
  this.tabDB.Text="Điểm bán vé";
  this.tabDB.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabDB);
  this.tabHDV.Name="tabHDV";
  this.tabHDV.Location=new System.Drawing.Point(0,0);
  this.tabHDV.Size=new System.Drawing.Size(950,535);
  this.tabHDV.TabIndex=3;
  this.tabHDV.Text="Hướng dẫn viên";
  this.tabHDV.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabHDV);
  this.tabTQ.Name="tabTQ";
  this.tabTQ.Location=new System.Drawing.Point(0,0);
  this.tabTQ.Size=new System.Drawing.Size(950,535);
  this.tabTQ.TabIndex=4;
  this.tabTQ.Text="Điểm tham quan";
  this.tabTQ.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabTQ);
  this.dgvPT.Name="dgvPT";
  this.dgvPT.Location=new System.Drawing.Point(12,15);
  this.dgvPT.Size=new System.Drawing.Size(930,345);
  this.dgvPT.TabIndex=5;
  this.dgvPT.ReadOnly = true;
  this.dgvPT.AllowUserToAddRows = false;
  this.dgvPT.AllowUserToDeleteRows = false;
  this.dgvPT.MultiSelect = false;
  this.dgvPT.RowHeadersVisible = true;
  this.dgvPT.RowHeadersWidth = 28;
  this.dgvPT.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvPT.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvPT.BackgroundColor = System.Drawing.Color.White;
  this.dgvPT.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvPT.EnableHeadersVisualStyles = false;
  this.dgvPT.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvPT.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvPT.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvPT.ColumnHeadersHeight = 26;
  this.tabPT.Controls.Add(this.dgvPT);
  this.label6.Name="label6";
  this.label6.Location=new System.Drawing.Point(15,388);
  this.label6.Size=new System.Drawing.Size(100,25);
  this.label6.TabIndex=6;
  this.label6.Text="Mã Phương tiện:";
  this.tabPT.Controls.Add(this.label6);
  this.txtPTMa.Name="txtPTMa";
  this.txtPTMa.Location=new System.Drawing.Point(115,385);
  this.txtPTMa.Size=new System.Drawing.Size(160,25);
  this.txtPTMa.TabIndex=7;
  this.txtPTMa.MaxLength = 1500;
  this.tabPT.Controls.Add(this.txtPTMa);
  this.label8.Name="label8";
  this.label8.Location=new System.Drawing.Point(345,388);
  this.label8.Size=new System.Drawing.Size(120,25);
  this.label8.TabIndex=8;
  this.label8.Text="Tên Phương tiện:";
  this.tabPT.Controls.Add(this.label8);
  this.txtPTTen.Name="txtPTTen";
  this.txtPTTen.Location=new System.Drawing.Point(465,385);
  this.txtPTTen.Size=new System.Drawing.Size(380,25);
  this.txtPTTen.TabIndex=9;
  this.txtPTTen.MaxLength = 1500;
  this.tabPT.Controls.Add(this.txtPTTen);
  this.label10.Name="label10";
  this.label10.Location=new System.Drawing.Point(15,428);
  this.label10.Size=new System.Drawing.Size(100,25);
  this.label10.TabIndex=10;
  this.label10.Text="Ghi chú:";
  this.tabPT.Controls.Add(this.label10);
  this.txtPTNote.Name="txtPTNote";
  this.txtPTNote.Location=new System.Drawing.Point(115,425);
  this.txtPTNote.Size=new System.Drawing.Size(520,25);
  this.txtPTNote.TabIndex=11;
  this.txtPTNote.MaxLength = 1500;
  this.tabPT.Controls.Add(this.txtPTNote);
  this.btnThemPT.Name="btnThemPT";
  this.btnThemPT.Location=new System.Drawing.Point(800,465);
  this.btnThemPT.Size=new System.Drawing.Size(130,34);
  this.btnThemPT.TabIndex=12;
  this.btnThemPT.Text="Thêm";
  this.btnThemPT.UseVisualStyleBackColor = false;
  this.btnThemPT.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnThemPT.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnThemPT.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabPT.Controls.Add(this.btnThemPT);
  this.dgvDB.Name="dgvDB";
  this.dgvDB.Location=new System.Drawing.Point(12,15);
  this.dgvDB.Size=new System.Drawing.Size(930,345);
  this.dgvDB.TabIndex=13;
  this.dgvDB.ReadOnly = true;
  this.dgvDB.AllowUserToAddRows = false;
  this.dgvDB.AllowUserToDeleteRows = false;
  this.dgvDB.MultiSelect = false;
  this.dgvDB.RowHeadersVisible = true;
  this.dgvDB.RowHeadersWidth = 28;
  this.dgvDB.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvDB.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvDB.BackgroundColor = System.Drawing.Color.White;
  this.dgvDB.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvDB.EnableHeadersVisualStyles = false;
  this.dgvDB.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvDB.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvDB.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvDB.ColumnHeadersHeight = 26;
  this.tabDB.Controls.Add(this.dgvDB);
  this.label14.Name="label14";
  this.label14.Location=new System.Drawing.Point(15,388);
  this.label14.Size=new System.Drawing.Size(100,25);
  this.label14.TabIndex=14;
  this.label14.Text="Mã Điểm bán:";
  this.tabDB.Controls.Add(this.label14);
  this.txtDBMa.Name="txtDBMa";
  this.txtDBMa.Location=new System.Drawing.Point(115,385);
  this.txtDBMa.Size=new System.Drawing.Size(160,25);
  this.txtDBMa.TabIndex=15;
  this.txtDBMa.MaxLength = 1500;
  this.tabDB.Controls.Add(this.txtDBMa);
  this.label16.Name="label16";
  this.label16.Location=new System.Drawing.Point(345,388);
  this.label16.Size=new System.Drawing.Size(120,25);
  this.label16.TabIndex=16;
  this.label16.Text="Tên Điểm bán:";
  this.tabDB.Controls.Add(this.label16);
  this.txtDBTen.Name="txtDBTen";
  this.txtDBTen.Location=new System.Drawing.Point(465,385);
  this.txtDBTen.Size=new System.Drawing.Size(380,25);
  this.txtDBTen.TabIndex=17;
  this.txtDBTen.MaxLength = 1500;
  this.tabDB.Controls.Add(this.txtDBTen);
  this.label18.Name="label18";
  this.label18.Location=new System.Drawing.Point(15,428);
  this.label18.Size=new System.Drawing.Size(100,25);
  this.label18.TabIndex=18;
  this.label18.Text="Địa chỉ:";
  this.tabDB.Controls.Add(this.label18);
  this.txtDBDia.Name="txtDBDia";
  this.txtDBDia.Location=new System.Drawing.Point(115,425);
  this.txtDBDia.Size=new System.Drawing.Size(420,25);
  this.txtDBDia.TabIndex=19;
  this.txtDBDia.MaxLength = 1500;
  this.tabDB.Controls.Add(this.txtDBDia);
  this.label20.Name="label20";
  this.label20.Location=new System.Drawing.Point(570,428);
  this.label20.Size=new System.Drawing.Size(100,25);
  this.label20.TabIndex=20;
  this.label20.Text="Điện thoại:";
  this.tabDB.Controls.Add(this.label20);
  this.txtDBPhone.Name="txtDBPhone";
  this.txtDBPhone.Location=new System.Drawing.Point(670,425);
  this.txtDBPhone.Size=new System.Drawing.Size(220,25);
  this.txtDBPhone.TabIndex=21;
  this.txtDBPhone.MaxLength = 1500;
  this.tabDB.Controls.Add(this.txtDBPhone);
  this.btnThemDB.Name="btnThemDB";
  this.btnThemDB.Location=new System.Drawing.Point(800,465);
  this.btnThemDB.Size=new System.Drawing.Size(130,34);
  this.btnThemDB.TabIndex=22;
  this.btnThemDB.Text="Thêm";
  this.btnThemDB.UseVisualStyleBackColor = false;
  this.btnThemDB.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnThemDB.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnThemDB.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabDB.Controls.Add(this.btnThemDB);
  this.dgvHDV.Name="dgvHDV";
  this.dgvHDV.Location=new System.Drawing.Point(12,15);
  this.dgvHDV.Size=new System.Drawing.Size(930,345);
  this.dgvHDV.TabIndex=23;
  this.dgvHDV.ReadOnly = true;
  this.dgvHDV.AllowUserToAddRows = false;
  this.dgvHDV.AllowUserToDeleteRows = false;
  this.dgvHDV.MultiSelect = false;
  this.dgvHDV.RowHeadersVisible = true;
  this.dgvHDV.RowHeadersWidth = 28;
  this.dgvHDV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvHDV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvHDV.BackgroundColor = System.Drawing.Color.White;
  this.dgvHDV.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvHDV.EnableHeadersVisualStyles = false;
  this.dgvHDV.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvHDV.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvHDV.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvHDV.ColumnHeadersHeight = 26;
  this.tabHDV.Controls.Add(this.dgvHDV);
  this.label24.Name="label24";
  this.label24.Location=new System.Drawing.Point(15,388);
  this.label24.Size=new System.Drawing.Size(100,25);
  this.label24.TabIndex=24;
  this.label24.Text="Mã HDV:";
  this.tabHDV.Controls.Add(this.label24);
  this.txtHDVMa.Name="txtHDVMa";
  this.txtHDVMa.Location=new System.Drawing.Point(115,385);
  this.txtHDVMa.Size=new System.Drawing.Size(160,25);
  this.txtHDVMa.TabIndex=25;
  this.txtHDVMa.MaxLength = 1500;
  this.tabHDV.Controls.Add(this.txtHDVMa);
  this.label26.Name="label26";
  this.label26.Location=new System.Drawing.Point(345,388);
  this.label26.Size=new System.Drawing.Size(120,25);
  this.label26.TabIndex=26;
  this.label26.Text="Tên HDV:";
  this.tabHDV.Controls.Add(this.label26);
  this.txtHDVTen.Name="txtHDVTen";
  this.txtHDVTen.Location=new System.Drawing.Point(465,385);
  this.txtHDVTen.Size=new System.Drawing.Size(380,25);
  this.txtHDVTen.TabIndex=27;
  this.txtHDVTen.MaxLength = 1500;
  this.tabHDV.Controls.Add(this.txtHDVTen);
  this.label28.Name="label28";
  this.label28.Location=new System.Drawing.Point(15,428);
  this.label28.Size=new System.Drawing.Size(100,25);
  this.label28.TabIndex=28;
  this.label28.Text="Điện thoại:";
  this.tabHDV.Controls.Add(this.label28);
  this.txtHDVPhone.Name="txtHDVPhone";
  this.txtHDVPhone.Location=new System.Drawing.Point(115,425);
  this.txtHDVPhone.Size=new System.Drawing.Size(220,25);
  this.txtHDVPhone.TabIndex=29;
  this.txtHDVPhone.MaxLength = 1500;
  this.tabHDV.Controls.Add(this.txtHDVPhone);
  this.label30.Name="label30";
  this.label30.Location=new System.Drawing.Point(410,428);
  this.label30.Size=new System.Drawing.Size(100,25);
  this.label30.TabIndex=30;
  this.label30.Text="Lương cơ bản:";
  this.tabHDV.Controls.Add(this.label30);
  this.numLuong.Name="numLuong";
  this.numLuong.Location=new System.Drawing.Point(510,425);
  this.numLuong.Size=new System.Drawing.Size(180,25);
  this.numLuong.TabIndex=31;
  this.numLuong.Minimum = 0M;
  this.numLuong.Maximum = 999999999999M;
  this.numLuong.Value = 9000000M;
  this.numLuong.ThousandsSeparator = true;
  this.tabHDV.Controls.Add(this.numLuong);
  this.btnThemHDV.Name="btnThemHDV";
  this.btnThemHDV.Location=new System.Drawing.Point(800,465);
  this.btnThemHDV.Size=new System.Drawing.Size(130,34);
  this.btnThemHDV.TabIndex=32;
  this.btnThemHDV.Text="Thêm";
  this.btnThemHDV.UseVisualStyleBackColor = false;
  this.btnThemHDV.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnThemHDV.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnThemHDV.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabHDV.Controls.Add(this.btnThemHDV);
  this.dgvTQ.Name="dgvTQ";
  this.dgvTQ.Location=new System.Drawing.Point(12,15);
  this.dgvTQ.Size=new System.Drawing.Size(930,345);
  this.dgvTQ.TabIndex=33;
  this.dgvTQ.ReadOnly = true;
  this.dgvTQ.AllowUserToAddRows = false;
  this.dgvTQ.AllowUserToDeleteRows = false;
  this.dgvTQ.MultiSelect = false;
  this.dgvTQ.RowHeadersVisible = true;
  this.dgvTQ.RowHeadersWidth = 28;
  this.dgvTQ.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvTQ.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvTQ.BackgroundColor = System.Drawing.Color.White;
  this.dgvTQ.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvTQ.EnableHeadersVisualStyles = false;
  this.dgvTQ.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvTQ.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvTQ.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvTQ.ColumnHeadersHeight = 26;
  this.tabTQ.Controls.Add(this.dgvTQ);
  this.label34.Name="label34";
  this.label34.Location=new System.Drawing.Point(15,388);
  this.label34.Size=new System.Drawing.Size(100,25);
  this.label34.TabIndex=34;
  this.label34.Text="Mã Điểm tham quan:";
  this.tabTQ.Controls.Add(this.label34);
  this.txtTQMa.Name="txtTQMa";
  this.txtTQMa.Location=new System.Drawing.Point(115,385);
  this.txtTQMa.Size=new System.Drawing.Size(160,25);
  this.txtTQMa.TabIndex=35;
  this.txtTQMa.MaxLength = 1500;
  this.tabTQ.Controls.Add(this.txtTQMa);
  this.label36.Name="label36";
  this.label36.Location=new System.Drawing.Point(345,388);
  this.label36.Size=new System.Drawing.Size(120,25);
  this.label36.TabIndex=36;
  this.label36.Text="Tên Điểm tham quan:";
  this.tabTQ.Controls.Add(this.label36);
  this.txtTQTen.Name="txtTQTen";
  this.txtTQTen.Location=new System.Drawing.Point(465,385);
  this.txtTQTen.Size=new System.Drawing.Size(380,25);
  this.txtTQTen.TabIndex=37;
  this.txtTQTen.MaxLength = 1500;
  this.tabTQ.Controls.Add(this.txtTQTen);
  this.label38.Name="label38";
  this.label38.Location=new System.Drawing.Point(15,428);
  this.label38.Size=new System.Drawing.Size(100,25);
  this.label38.TabIndex=38;
  this.label38.Text="Địa điểm:";
  this.tabTQ.Controls.Add(this.label38);
  this.txtTQDia.Name="txtTQDia";
  this.txtTQDia.Location=new System.Drawing.Point(115,425);
  this.txtTQDia.Size=new System.Drawing.Size(540,25);
  this.txtTQDia.TabIndex=39;
  this.txtTQDia.MaxLength = 1500;
  this.tabTQ.Controls.Add(this.txtTQDia);
  this.label40.Name="label40";
  this.label40.Location=new System.Drawing.Point(15,466);
  this.label40.Size=new System.Drawing.Size(100,25);
  this.label40.TabIndex=40;
  this.label40.Text="Nội dung:";
  this.tabTQ.Controls.Add(this.label40);
  this.txtTQNoiDung.Name="txtTQNoiDung";
  this.txtTQNoiDung.Location=new System.Drawing.Point(115,463);
  this.txtTQNoiDung.Size=new System.Drawing.Size(330,25);
  this.txtTQNoiDung.TabIndex=41;
  this.txtTQNoiDung.MaxLength = 1500;
  this.tabTQ.Controls.Add(this.txtTQNoiDung);
  this.label42.Name="label42";
  this.label42.Location=new System.Drawing.Point(470,466);
  this.label42.Size=new System.Drawing.Size(100,25);
  this.label42.TabIndex=42;
  this.label42.Text="Ý nghĩa:";
  this.tabTQ.Controls.Add(this.label42);
  this.txtTQYNghia.Name="txtTQYNghia";
  this.txtTQYNghia.Location=new System.Drawing.Point(570,463);
  this.txtTQYNghia.Size=new System.Drawing.Size(290,25);
  this.txtTQYNghia.TabIndex=43;
  this.txtTQYNghia.MaxLength = 1500;
  this.tabTQ.Controls.Add(this.txtTQYNghia);
  this.btnThemTQ.Name="btnThemTQ";
  this.btnThemTQ.Location=new System.Drawing.Point(800,465);
  this.btnThemTQ.Size=new System.Drawing.Size(130,34);
  this.btnThemTQ.TabIndex=44;
  this.btnThemTQ.Text="Thêm";
  this.btnThemTQ.UseVisualStyleBackColor = false;
  this.btnThemTQ.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnThemTQ.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnThemTQ.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabTQ.Controls.Add(this.btnThemTQ);
  this.btnDong.Name="btnDong";
  this.btnDong.Location=new System.Drawing.Point(870,595);
  this.btnDong.Size=new System.Drawing.Size(110,32);
  this.btnDong.TabIndex=45;
  this.btnDong.Text="Đóng";
  this.btnDong.UseVisualStyleBackColor = false;
  this.btnDong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDong);
  this.AutoScaleDimensions=new System.Drawing.SizeF(7F,15F);
  this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
  this.ClientSize=new System.Drawing.Size(1000,640);
  this.Font=new System.Drawing.Font("Segoe UI",9F);
  this.BackColor=System.Drawing.Color.FromArgb(240,240,240);
  this.StartPosition=System.Windows.Forms.FormStartPosition.CenterParent;
  this.Name="FrmDanhMuc";
  this.Text="Danh mục";
  this.Load+=new System.EventHandler(this.FrmDanhMuc_Load);
  this.ResumeLayout(false);
  this.PerformLayout();
 }
 private System.Windows.Forms.TabControl tabs;
 private System.Windows.Forms.TabPage tabPT;
 private System.Windows.Forms.TabPage tabDB;
 private System.Windows.Forms.TabPage tabHDV;
 private System.Windows.Forms.TabPage tabTQ;
 private System.Windows.Forms.DataGridView dgvPT;
 private System.Windows.Forms.Label label6;
 private System.Windows.Forms.TextBox txtPTMa;
 private System.Windows.Forms.Label label8;
 private System.Windows.Forms.TextBox txtPTTen;
 private System.Windows.Forms.Label label10;
 private System.Windows.Forms.TextBox txtPTNote;
 private System.Windows.Forms.Button btnThemPT;
 private System.Windows.Forms.DataGridView dgvDB;
 private System.Windows.Forms.Label label14;
 private System.Windows.Forms.TextBox txtDBMa;
 private System.Windows.Forms.Label label16;
 private System.Windows.Forms.TextBox txtDBTen;
 private System.Windows.Forms.Label label18;
 private System.Windows.Forms.TextBox txtDBDia;
 private System.Windows.Forms.Label label20;
 private System.Windows.Forms.TextBox txtDBPhone;
 private System.Windows.Forms.Button btnThemDB;
 private System.Windows.Forms.DataGridView dgvHDV;
 private System.Windows.Forms.Label label24;
 private System.Windows.Forms.TextBox txtHDVMa;
 private System.Windows.Forms.Label label26;
 private System.Windows.Forms.TextBox txtHDVTen;
 private System.Windows.Forms.Label label28;
 private System.Windows.Forms.TextBox txtHDVPhone;
 private System.Windows.Forms.Label label30;
 private System.Windows.Forms.NumericUpDown numLuong;
 private System.Windows.Forms.Button btnThemHDV;
 private System.Windows.Forms.DataGridView dgvTQ;
 private System.Windows.Forms.Label label34;
 private System.Windows.Forms.TextBox txtTQMa;
 private System.Windows.Forms.Label label36;
 private System.Windows.Forms.TextBox txtTQTen;
 private System.Windows.Forms.Label label38;
 private System.Windows.Forms.TextBox txtTQDia;
 private System.Windows.Forms.Label label40;
 private System.Windows.Forms.TextBox txtTQNoiDung;
 private System.Windows.Forms.Label label42;
 private System.Windows.Forms.TextBox txtTQYNghia;
 private System.Windows.Forms.Button btnThemTQ;
 private System.Windows.Forms.Button btnDong;
 }
}