namespace QuanLyDuLich.Forms {
 partial class FrmDiemThamQuan {
  private System.ComponentModel.IContainer components = null;
  protected override void Dispose(bool disposing) { if(disposing && components!=null) components.Dispose(); base.Dispose(disposing); }
  private void InitializeComponent() {
   this.lblTitle = new System.Windows.Forms.Label();
   this.lbl1 = new System.Windows.Forms.Label();
   this.txtMa = new System.Windows.Forms.TextBox();
   this.lbl3 = new System.Windows.Forms.Label();
   this.txtTen = new System.Windows.Forms.TextBox();
   this.lbl5 = new System.Windows.Forms.Label();
   this.txtDia = new System.Windows.Forms.TextBox();
   this.lbl7 = new System.Windows.Forms.Label();
   this.txtNoiDung = new System.Windows.Forms.TextBox();
   this.lbl9 = new System.Windows.Forms.Label();
   this.txtYNghia = new System.Windows.Forms.TextBox();
   this.btnNew = new System.Windows.Forms.Button();
   this.btnAdd = new System.Windows.Forms.Button();
   this.btnEdit = new System.Windows.Forms.Button();
   this.btnDelete = new System.Windows.Forms.Button();
   this.btnReload = new System.Windows.Forms.Button();
   this.btnClose = new System.Windows.Forms.Button();
   this.dgv = new System.Windows.Forms.DataGridView();
   this.SuspendLayout();
   this.lblTitle.Name = "lblTitle";
   this.lblTitle.Location = new System.Drawing.Point(25,18);
   this.lblTitle.Size = new System.Drawing.Size(1080,38);
   this.lblTitle.TabIndex = 0;
   this.lblTitle.Text = "ĐIỂM THAM QUAN";
   this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
   this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(17,60,104);
   this.Controls.Add(this.lblTitle);
   this.lbl1.Name = "lbl1";
   this.lbl1.Location = new System.Drawing.Point(25,80);
   this.lbl1.Size = new System.Drawing.Size(145,26);
   this.lbl1.TabIndex = 1;
   this.lbl1.Text = "Mã *";
   this.Controls.Add(this.lbl1);
   this.txtMa.Name = "txtMa";
   this.txtMa.Location = new System.Drawing.Point(170,75);
   this.txtMa.Size = new System.Drawing.Size(220,28);
   this.txtMa.TabIndex = 2;
   this.txtMa.MaxLength = 1500;
   this.Controls.Add(this.txtMa);
   this.lbl3.Name = "lbl3";
   this.lbl3.Location = new System.Drawing.Point(570,80);
   this.lbl3.Size = new System.Drawing.Size(145,26);
   this.lbl3.TabIndex = 3;
   this.lbl3.Text = "Tên / họ tên *";
   this.Controls.Add(this.lbl3);
   this.txtTen.Name = "txtTen";
   this.txtTen.Location = new System.Drawing.Point(715,75);
   this.txtTen.Size = new System.Drawing.Size(380,28);
   this.txtTen.TabIndex = 4;
   this.txtTen.MaxLength = 1500;
   this.Controls.Add(this.txtTen);
   this.lbl5.Name = "lbl5";
   this.lbl5.Location = new System.Drawing.Point(25,120);
   this.lbl5.Size = new System.Drawing.Size(145,26);
   this.lbl5.TabIndex = 5;
   this.lbl5.Text = "Địa điểm *";
   this.Controls.Add(this.lbl5);
   this.txtDia.Name = "txtDia";
   this.txtDia.Location = new System.Drawing.Point(170,115);
   this.txtDia.Size = new System.Drawing.Size(850,28);
   this.txtDia.TabIndex = 6;
   this.txtDia.MaxLength = 1500;
   this.Controls.Add(this.txtDia);
   this.lbl7.Name = "lbl7";
   this.lbl7.Location = new System.Drawing.Point(25,160);
   this.lbl7.Size = new System.Drawing.Size(145,26);
   this.lbl7.TabIndex = 7;
   this.lbl7.Text = "Nội dung";
   this.Controls.Add(this.lbl7);
   this.txtNoiDung.Name = "txtNoiDung";
   this.txtNoiDung.Location = new System.Drawing.Point(170,155);
   this.txtNoiDung.Size = new System.Drawing.Size(850,28);
   this.txtNoiDung.TabIndex = 8;
   this.txtNoiDung.MaxLength = 1500;
   this.Controls.Add(this.txtNoiDung);
   this.lbl9.Name = "lbl9";
   this.lbl9.Location = new System.Drawing.Point(25,200);
   this.lbl9.Size = new System.Drawing.Size(145,26);
   this.lbl9.TabIndex = 9;
   this.lbl9.Text = "Ý nghĩa";
   this.Controls.Add(this.lbl9);
   this.txtYNghia.Name = "txtYNghia";
   this.txtYNghia.Location = new System.Drawing.Point(170,195);
   this.txtYNghia.Size = new System.Drawing.Size(850,28);
   this.txtYNghia.TabIndex = 10;
   this.txtYNghia.MaxLength = 1500;
   this.Controls.Add(this.txtYNghia);
   this.btnNew.Name = "btnNew";
   this.btnNew.Location = new System.Drawing.Point(25,240);
   this.btnNew.Size = new System.Drawing.Size(150,38);
   this.btnNew.TabIndex = 11;
   this.btnNew.Text = "Nhập mới";
   this.btnNew.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnNew);
   this.btnAdd.Name = "btnAdd";
   this.btnAdd.Location = new System.Drawing.Point(185,240);
   this.btnAdd.Size = new System.Drawing.Size(150,38);
   this.btnAdd.TabIndex = 12;
   this.btnAdd.Text = "Thêm";
   this.btnAdd.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnAdd);
   this.btnEdit.Name = "btnEdit";
   this.btnEdit.Location = new System.Drawing.Point(345,240);
   this.btnEdit.Size = new System.Drawing.Size(150,38);
   this.btnEdit.TabIndex = 13;
   this.btnEdit.Text = "Lưu sửa";
   this.btnEdit.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnEdit);
   this.btnDelete.Name = "btnDelete";
   this.btnDelete.Location = new System.Drawing.Point(505,240);
   this.btnDelete.Size = new System.Drawing.Size(150,38);
   this.btnDelete.TabIndex = 14;
   this.btnDelete.Text = "Xóa";
   this.btnDelete.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnDelete);
   this.btnReload.Name = "btnReload";
   this.btnReload.Location = new System.Drawing.Point(665,240);
   this.btnReload.Size = new System.Drawing.Size(150,38);
   this.btnReload.TabIndex = 15;
   this.btnReload.Text = "Tải lại";
   this.btnReload.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnReload);
   this.btnClose.Name = "btnClose";
   this.btnClose.Location = new System.Drawing.Point(955,240);
   this.btnClose.Size = new System.Drawing.Size(150,38);
   this.btnClose.TabIndex = 16;
   this.btnClose.Text = "Đóng";
   this.btnClose.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnClose);
   this.dgv.Name = "dgv";
   this.dgv.Location = new System.Drawing.Point(25,295);
   this.dgv.Size = new System.Drawing.Size(1080,405);
   this.dgv.TabIndex = 17;
   this.dgv.ReadOnly = true;
   this.dgv.AllowUserToAddRows = false;
   this.dgv.AllowUserToDeleteRows = false;
   this.dgv.MultiSelect = false;
   this.dgv.RowHeadersVisible = false;
   this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
   this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
   this.dgv.BackgroundColor = System.Drawing.Color.White;
   this.dgv.EnableHeadersVisualStyles = false;
   this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(232,239,244);
   this.dgv.ColumnHeadersHeight = 32;
   this.dgv.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(248,250,252);
   this.Controls.Add(this.dgv);
   this.AutoScaleDimensions = new System.Drawing.SizeF(7F,15F);
   this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
   this.ClientSize = new System.Drawing.Size(1140,730);
   this.Font = new System.Drawing.Font("Segoe UI",9F);
   this.BackColor = System.Drawing.Color.FromArgb(248,250,252);
   this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
   this.Text = "LAB5 - ĐIỂM THAM QUAN";
   this.Name = "FrmDiemThamQuan";
   this.Load += new System.EventHandler(this.FrmDiemThamQuan_Load);
   this.ResumeLayout(false);
   this.PerformLayout();
  }
  private System.Windows.Forms.Label lblTitle;
  private System.Windows.Forms.Label lbl1;
  private System.Windows.Forms.TextBox txtMa;
  private System.Windows.Forms.Label lbl3;
  private System.Windows.Forms.TextBox txtTen;
  private System.Windows.Forms.Label lbl5;
  private System.Windows.Forms.TextBox txtDia;
  private System.Windows.Forms.Label lbl7;
  private System.Windows.Forms.TextBox txtNoiDung;
  private System.Windows.Forms.Label lbl9;
  private System.Windows.Forms.TextBox txtYNghia;
  private System.Windows.Forms.Button btnNew;
  private System.Windows.Forms.Button btnAdd;
  private System.Windows.Forms.Button btnEdit;
  private System.Windows.Forms.Button btnDelete;
  private System.Windows.Forms.Button btnReload;
  private System.Windows.Forms.Button btnClose;
  private System.Windows.Forms.DataGridView dgv;
 }
}