namespace QuanLyDuLich.Forms {
 partial class FrmDangKyLe {
 private System.ComponentModel.IContainer components=null;
 protected override void Dispose(bool disposing){if(disposing && components!=null)components.Dispose();base.Dispose(disposing);}
 private void InitializeComponent(){
  this.label0=new System.Windows.Forms.Label();
  this.txtSo=new System.Windows.Forms.TextBox();
  this.label2=new System.Windows.Forms.Label();
  this.cboChuyen=new System.Windows.Forms.ComboBox();
  this.label4=new System.Windows.Forms.Label();
  this.cboDB=new System.Windows.Forms.ComboBox();
  this.label6=new System.Windows.Forms.Label();
  this.txtTen=new System.Windows.Forms.TextBox();
  this.label8=new System.Windows.Forms.Label();
  this.txtPhone=new System.Windows.Forms.TextBox();
  this.label10=new System.Windows.Forms.Label();
  this.numNguoi=new System.Windows.Forms.NumericUpDown();
  this.label12=new System.Windows.Forms.Label();
  this.lblTien=new System.Windows.Forms.Label();
  this.btnDangKy=new System.Windows.Forms.Button();
  this.dgv=new System.Windows.Forms.DataGridView();
  this.btnDong=new System.Windows.Forms.Button();
  this.SuspendLayout();
  this.label0.Name="label0";
  this.label0.Location=new System.Drawing.Point(25,28);
  this.label0.Size=new System.Drawing.Size(100,25);
  this.label0.TabIndex=0;
  this.label0.Text="Số đăng ký:";
  this.Controls.Add(this.label0);
  this.txtSo.Name="txtSo";
  this.txtSo.Location=new System.Drawing.Point(125,25);
  this.txtSo.Size=new System.Drawing.Size(150,25);
  this.txtSo.TabIndex=1;
  this.txtSo.MaxLength = 1500;
  this.Controls.Add(this.txtSo);
  this.label2.Name="label2";
  this.label2.Location=new System.Drawing.Point(350,28);
  this.label2.Size=new System.Drawing.Size(75,25);
  this.label2.TabIndex=2;
  this.label2.Text="Chuyến:";
  this.Controls.Add(this.label2);
  this.cboChuyen.Name="cboChuyen";
  this.cboChuyen.Location=new System.Drawing.Point(425,25);
  this.cboChuyen.Size=new System.Drawing.Size(535,25);
  this.cboChuyen.TabIndex=3;
  this.cboChuyen.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.Controls.Add(this.cboChuyen);
  this.label4.Name="label4";
  this.label4.Location=new System.Drawing.Point(25,68);
  this.label4.Size=new System.Drawing.Size(100,25);
  this.label4.TabIndex=4;
  this.label4.Text="Điểm bán vé:";
  this.Controls.Add(this.label4);
  this.cboDB.Name="cboDB";
  this.cboDB.Location=new System.Drawing.Point(125,65);
  this.cboDB.Size=new System.Drawing.Size(240,25);
  this.cboDB.TabIndex=5;
  this.cboDB.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.Controls.Add(this.cboDB);
  this.label6.Name="label6";
  this.label6.Location=new System.Drawing.Point(390,68);
  this.label6.Size=new System.Drawing.Size(125,25);
  this.label6.TabIndex=6;
  this.label6.Text="Người đăng ký:";
  this.Controls.Add(this.label6);
  this.txtTen.Name="txtTen";
  this.txtTen.Location=new System.Drawing.Point(515,65);
  this.txtTen.Size=new System.Drawing.Size(230,25);
  this.txtTen.TabIndex=7;
  this.txtTen.MaxLength = 1500;
  this.Controls.Add(this.txtTen);
  this.label8.Name="label8";
  this.label8.Location=new System.Drawing.Point(770,68);
  this.label8.Size=new System.Drawing.Size(75,25);
  this.label8.TabIndex=8;
  this.label8.Text="Điện thoại:";
  this.Controls.Add(this.label8);
  this.txtPhone.Name="txtPhone";
  this.txtPhone.Location=new System.Drawing.Point(845,65);
  this.txtPhone.Size=new System.Drawing.Size(130,25);
  this.txtPhone.TabIndex=9;
  this.txtPhone.MaxLength = 1500;
  this.Controls.Add(this.txtPhone);
  this.label10.Name="label10";
  this.label10.Location=new System.Drawing.Point(25,108);
  this.label10.Size=new System.Drawing.Size(100,25);
  this.label10.TabIndex=10;
  this.label10.Text="Số người:";
  this.Controls.Add(this.label10);
  this.numNguoi.Name="numNguoi";
  this.numNguoi.Location=new System.Drawing.Point(125,105);
  this.numNguoi.Size=new System.Drawing.Size(85,25);
  this.numNguoi.TabIndex=11;
  this.numNguoi.Minimum = 1M;
  this.numNguoi.Maximum = 11M;
  this.numNguoi.Value = 4M;
  this.numNguoi.ThousandsSeparator = true;
  this.Controls.Add(this.numNguoi);
  this.label12.Name="label12";
  this.label12.Location=new System.Drawing.Point(235,108);
  this.label12.Size=new System.Drawing.Size(85,25);
  this.label12.TabIndex=12;
  this.label12.Text="Thành tiền:";
  this.label12.Font = new System.Drawing.Font("Segoe UI",9F,System.Drawing.FontStyle.Bold);
  this.Controls.Add(this.label12);
  this.lblTien.Name="lblTien";
  this.lblTien.Location=new System.Drawing.Point(325,108);
  this.lblTien.Size=new System.Drawing.Size(275,25);
  this.lblTien.TabIndex=13;
  this.lblTien.Text="0 đ";
  this.lblTien.ForeColor = System.Drawing.Color.DarkRed;
  this.lblTien.Font = new System.Drawing.Font("Segoe UI",9F,System.Drawing.FontStyle.Bold);
  this.Controls.Add(this.lblTien);
  this.btnDangKy.Name="btnDangKy";
  this.btnDangKy.Location=new System.Drawing.Point(710,100);
  this.btnDangKy.Size=new System.Drawing.Size(265,36);
  this.btnDangKy.TabIndex=14;
  this.btnDangKy.Text="Đăng ký và thanh toán vé";
  this.btnDangKy.UseVisualStyleBackColor = false;
  this.btnDangKy.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDangKy.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDangKy.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDangKy);
  this.dgv.Name="dgv";
  this.dgv.Location=new System.Drawing.Point(25,155);
  this.dgv.Size=new System.Drawing.Size(950,455);
  this.dgv.TabIndex=15;
  this.dgv.ReadOnly = true;
  this.dgv.AllowUserToAddRows = false;
  this.dgv.AllowUserToDeleteRows = false;
  this.dgv.MultiSelect = false;
  this.dgv.RowHeadersVisible = true;
  this.dgv.RowHeadersWidth = 28;
  this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgv.BackgroundColor = System.Drawing.Color.White;
  this.dgv.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgv.EnableHeadersVisualStyles = false;
  this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgv.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgv.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgv.ColumnHeadersHeight = 26;
  this.Controls.Add(this.dgv);
  this.btnDong.Name="btnDong";
  this.btnDong.Location=new System.Drawing.Point(865,625);
  this.btnDong.Size=new System.Drawing.Size(110,32);
  this.btnDong.TabIndex=16;
  this.btnDong.Text="Đóng";
  this.btnDong.UseVisualStyleBackColor = false;
  this.btnDong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDong);
  this.AutoScaleDimensions=new System.Drawing.SizeF(7F,15F);
  this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
  this.ClientSize=new System.Drawing.Size(1000,670);
  this.Font=new System.Drawing.Font("Segoe UI",9F);
  this.BackColor=System.Drawing.Color.FromArgb(240,240,240);
  this.StartPosition=System.Windows.Forms.FormStartPosition.CenterParent;
  this.Name="FrmDangKyLe";
  this.Text="Đăng ký khách lẻ theo chuyến";
  this.Load+=new System.EventHandler(this.FrmDangKyLe_Load);
  this.ResumeLayout(false);
  this.PerformLayout();
 }
 private System.Windows.Forms.Label label0;
 private System.Windows.Forms.TextBox txtSo;
 private System.Windows.Forms.Label label2;
 private System.Windows.Forms.ComboBox cboChuyen;
 private System.Windows.Forms.Label label4;
 private System.Windows.Forms.ComboBox cboDB;
 private System.Windows.Forms.Label label6;
 private System.Windows.Forms.TextBox txtTen;
 private System.Windows.Forms.Label label8;
 private System.Windows.Forms.TextBox txtPhone;
 private System.Windows.Forms.Label label10;
 private System.Windows.Forms.NumericUpDown numNguoi;
 private System.Windows.Forms.Label label12;
 private System.Windows.Forms.Label lblTien;
 private System.Windows.Forms.Button btnDangKy;
 private System.Windows.Forms.DataGridView dgv;
 private System.Windows.Forms.Button btnDong;
 }
}