namespace QuanLyDuLich.Forms {
 partial class FrmHuongDanVien {
  private System.ComponentModel.IContainer components = null;
  protected override void Dispose(bool disposing) { if(disposing && components!=null) components.Dispose(); base.Dispose(disposing); }
  private void InitializeComponent() {
   this.lblTitle = new System.Windows.Forms.Label();
   this.lbl1 = new System.Windows.Forms.Label();
   this.txtMa = new System.Windows.Forms.TextBox();
   this.lbl3 = new System.Windows.Forms.Label();
   this.txtTen = new System.Windows.Forms.TextBox();
   this.lbl5 = new System.Windows.Forms.Label();
   this.txtPhone = new System.Windows.Forms.TextBox();
   this.lbl7 = new System.Windows.Forms.Label();
   this.numLuong = new System.Windows.Forms.NumericUpDown();
   this.chkLam = new System.Windows.Forms.CheckBox();
   this.btnNew = new System.Windows.Forms.Button();
   this.btnAdd = new System.Windows.Forms.Button();
   this.btnEdit = new System.Windows.Forms.Button();
   this.btnDelete = new System.Windows.Forms.Button();
   this.btnReload = new System.Windows.Forms.Button();
   this.btnClose = new System.Windows.Forms.Button();
   this.dgv = new System.Windows.Forms.DataGridView();
   this.SuspendLayout();
   this.lblTitle.Name = "lblTitle";
   this.lblTitle.Location = new System.Drawing.Point(25,18);
   this.lblTitle.Size = new System.Drawing.Size(1080,38);
   this.lblTitle.TabIndex = 0;
   this.lblTitle.Text = "HƯỚNG DẪN VIÊN";
   this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
   this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(17,60,104);
   this.Controls.Add(this.lblTitle);
   this.lbl1.Name = "lbl1";
   this.lbl1.Location = new System.Drawing.Point(25,80);
   this.lbl1.Size = new System.Drawing.Size(145,26);
   this.lbl1.TabIndex = 1;
   this.lbl1.Text = "Mã *";
   this.Controls.Add(this.lbl1);
   this.txtMa.Name = "txtMa";
   this.txtMa.Location = new System.Drawing.Point(170,75);
   this.txtMa.Size = new System.Drawing.Size(220,28);
   this.txtMa.TabIndex = 2;
   this.txtMa.MaxLength = 1500;
   this.Controls.Add(this.txtMa);
   this.lbl3.Name = "lbl3";
   this.lbl3.Location = new System.Drawing.Point(570,80);
   this.lbl3.Size = new System.Drawing.Size(145,26);
   this.lbl3.TabIndex = 3;
   this.lbl3.Text = "Tên / họ tên *";
   this.Controls.Add(this.lbl3);
   this.txtTen.Name = "txtTen";
   this.txtTen.Location = new System.Drawing.Point(715,75);
   this.txtTen.Size = new System.Drawing.Size(380,28);
   this.txtTen.TabIndex = 4;
   this.txtTen.MaxLength = 1500;
   this.Controls.Add(this.txtTen);
   this.lbl5.Name = "lbl5";
   this.lbl5.Location = new System.Drawing.Point(25,120);
   this.lbl5.Size = new System.Drawing.Size(145,26);
   this.lbl5.TabIndex = 5;
   this.lbl5.Text = "Điện thoại *";
   this.Controls.Add(this.lbl5);
   this.txtPhone.Name = "txtPhone";
   this.txtPhone.Location = new System.Drawing.Point(170,115);
   this.txtPhone.Size = new System.Drawing.Size(220,28);
   this.txtPhone.TabIndex = 6;
   this.txtPhone.MaxLength = 1500;
   this.Controls.Add(this.txtPhone);
   this.lbl7.Name = "lbl7";
   this.lbl7.Location = new System.Drawing.Point(570,120);
   this.lbl7.Size = new System.Drawing.Size(145,26);
   this.lbl7.TabIndex = 7;
   this.lbl7.Text = "Lương cơ bản";
   this.Controls.Add(this.lbl7);
   this.numLuong.Name = "numLuong";
   this.numLuong.Location = new System.Drawing.Point(715,115);
   this.numLuong.Size = new System.Drawing.Size(150,28);
   this.numLuong.TabIndex = 8;
   this.numLuong.Minimum = 0M;
   this.numLuong.Maximum = 999999999999M;
   this.numLuong.Value = 0M;
   this.numLuong.ThousandsSeparator = true;
   this.Controls.Add(this.numLuong);
   this.chkLam.Name = "chkLam";
   this.chkLam.Location = new System.Drawing.Point(170,155);
   this.chkLam.Size = new System.Drawing.Size(225,28);
   this.chkLam.TabIndex = 9;
   this.chkLam.Text = "Đang làm việc";
   this.chkLam.Checked = true;
   this.Controls.Add(this.chkLam);
   this.btnNew.Name = "btnNew";
   this.btnNew.Location = new System.Drawing.Point(25,240);
   this.btnNew.Size = new System.Drawing.Size(150,38);
   this.btnNew.TabIndex = 10;
   this.btnNew.Text = "Nhập mới";
   this.btnNew.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnNew);
   this.btnAdd.Name = "btnAdd";
   this.btnAdd.Location = new System.Drawing.Point(185,240);
   this.btnAdd.Size = new System.Drawing.Size(150,38);
   this.btnAdd.TabIndex = 11;
   this.btnAdd.Text = "Thêm";
   this.btnAdd.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnAdd);
   this.btnEdit.Name = "btnEdit";
   this.btnEdit.Location = new System.Drawing.Point(345,240);
   this.btnEdit.Size = new System.Drawing.Size(150,38);
   this.btnEdit.TabIndex = 12;
   this.btnEdit.Text = "Lưu sửa";
   this.btnEdit.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnEdit);
   this.btnDelete.Name = "btnDelete";
   this.btnDelete.Location = new System.Drawing.Point(505,240);
   this.btnDelete.Size = new System.Drawing.Size(150,38);
   this.btnDelete.TabIndex = 13;
   this.btnDelete.Text = "Xóa";
   this.btnDelete.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnDelete);
   this.btnReload.Name = "btnReload";
   this.btnReload.Location = new System.Drawing.Point(665,240);
   this.btnReload.Size = new System.Drawing.Size(150,38);
   this.btnReload.TabIndex = 14;
   this.btnReload.Text = "Tải lại";
   this.btnReload.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnReload);
   this.btnClose.Name = "btnClose";
   this.btnClose.Location = new System.Drawing.Point(955,240);
   this.btnClose.Size = new System.Drawing.Size(150,38);
   this.btnClose.TabIndex = 15;
   this.btnClose.Text = "Đóng";
   this.btnClose.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnClose);
   this.dgv.Name = "dgv";
   this.dgv.Location = new System.Drawing.Point(25,295);
   this.dgv.Size = new System.Drawing.Size(1080,405);
   this.dgv.TabIndex = 16;
   this.dgv.ReadOnly = true;
   this.dgv.AllowUserToAddRows = false;
   this.dgv.AllowUserToDeleteRows = false;
   this.dgv.MultiSelect = false;
   this.dgv.RowHeadersVisible = false;
   this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
   this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
   this.dgv.BackgroundColor = System.Drawing.Color.White;
   this.dgv.EnableHeadersVisualStyles = false;
   this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(232,239,244);
   this.dgv.ColumnHeadersHeight = 32;
   this.dgv.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(248,250,252);
   this.Controls.Add(this.dgv);
   this.AutoScaleDimensions = new System.Drawing.SizeF(7F,15F);
   this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
   this.ClientSize = new System.Drawing.Size(1140,730);
   this.Font = new System.Drawing.Font("Segoe UI",9F);
   this.BackColor = System.Drawing.Color.FromArgb(248,250,252);
   this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
   this.Text = "LAB5 - HƯỚNG DẪN VIÊN";
   this.Name = "FrmHuongDanVien";
   this.Load += new System.EventHandler(this.FrmHuongDanVien_Load);
   this.ResumeLayout(false);
   this.PerformLayout();
  }
  private System.Windows.Forms.Label lblTitle;
  private System.Windows.Forms.Label lbl1;
  private System.Windows.Forms.TextBox txtMa;
  private System.Windows.Forms.Label lbl3;
  private System.Windows.Forms.TextBox txtTen;
  private System.Windows.Forms.Label lbl5;
  private System.Windows.Forms.TextBox txtPhone;
  private System.Windows.Forms.Label lbl7;
  private System.Windows.Forms.NumericUpDown numLuong;
  private System.Windows.Forms.CheckBox chkLam;
  private System.Windows.Forms.Button btnNew;
  private System.Windows.Forms.Button btnAdd;
  private System.Windows.Forms.Button btnEdit;
  private System.Windows.Forms.Button btnDelete;
  private System.Windows.Forms.Button btnReload;
  private System.Windows.Forms.Button btnClose;
  private System.Windows.Forms.DataGridView dgv;
 }
}