namespace QuanLyDuLich.Forms {
 partial class FrmKetThucKhaoSat {
 private System.ComponentModel.IContainer components=null;
 protected override void Dispose(bool disposing){if(disposing && components!=null)components.Dispose();base.Dispose(disposing);}
 private void InitializeComponent(){
  this.tabs=new System.Windows.Forms.TabControl();
  this.tabTT=new System.Windows.Forms.TabPage();
  this.tabKS=new System.Windows.Forms.TabPage();
  this.dgvDoan=new System.Windows.Forms.DataGridView();
  this.label4=new System.Windows.Forms.Label();
  this.txtSoTT=new System.Windows.Forms.TextBox();
  this.label6=new System.Windows.Forms.Label();
  this.txtSoDK=new System.Windows.Forms.TextBox();
  this.label8=new System.Windows.Forms.Label();
  this.dtTT=new System.Windows.Forms.DateTimePicker();
  this.label10=new System.Windows.Forms.Label();
  this.numTien=new System.Windows.Forms.NumericUpDown();
  this.label12=new System.Windows.Forms.Label();
  this.txtNote=new System.Windows.Forms.TextBox();
  this.btnThanhToan=new System.Windows.Forms.Button();
  this.label15=new System.Windows.Forms.Label();
  this.cboLoai=new System.Windows.Forms.ComboBox();
  this.label17=new System.Windows.Forms.Label();
  this.cboDK=new System.Windows.Forms.ComboBox();
  this.label19=new System.Windows.Forms.Label();
  this.txtMaKS=new System.Windows.Forms.TextBox();
  this.label21=new System.Windows.Forms.Label();
  this.dtGui=new System.Windows.Forms.DateTimePicker();
  this.btnGui=new System.Windows.Forms.Button();
  this.dgvKS=new System.Windows.Forms.DataGridView();
  this.label25=new System.Windows.Forms.Label();
  this.txtKSChon=new System.Windows.Forms.TextBox();
  this.label27=new System.Windows.Forms.Label();
  this.dtPH=new System.Windows.Forms.DateTimePicker();
  this.label29=new System.Windows.Forms.Label();
  this.numDiem=new System.Windows.Forms.NumericUpDown();
  this.label31=new System.Windows.Forms.Label();
  this.txtGopY=new System.Windows.Forms.TextBox();
  this.btnGhiPH=new System.Windows.Forms.Button();
  this.btnDong=new System.Windows.Forms.Button();
  this.SuspendLayout();
  this.tabs.Name="tabs";
  this.tabs.Location=new System.Drawing.Point(20,15);
  this.tabs.Size=new System.Drawing.Size(1000,610);
  this.tabs.TabIndex=0;
  this.Controls.Add(this.tabs);
  this.tabTT.Name="tabTT";
  this.tabTT.Location=new System.Drawing.Point(0,0);
  this.tabTT.Size=new System.Drawing.Size(990,585);
  this.tabTT.TabIndex=1;
  this.tabTT.Text="Thanh toán sau tour (đoàn)";
  this.tabTT.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabTT);
  this.tabKS.Name="tabKS";
  this.tabKS.Location=new System.Drawing.Point(0,0);
  this.tabKS.Size=new System.Drawing.Size(990,585);
  this.tabKS.TabIndex=2;
  this.tabKS.Text="Khảo sát khách hàng";
  this.tabKS.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabKS);
  this.dgvDoan.Name="dgvDoan";
  this.dgvDoan.Location=new System.Drawing.Point(12,15);
  this.dgvDoan.Size=new System.Drawing.Size(965,370);
  this.dgvDoan.TabIndex=3;
  this.dgvDoan.ReadOnly = true;
  this.dgvDoan.AllowUserToAddRows = false;
  this.dgvDoan.AllowUserToDeleteRows = false;
  this.dgvDoan.MultiSelect = false;
  this.dgvDoan.RowHeadersVisible = true;
  this.dgvDoan.RowHeadersWidth = 28;
  this.dgvDoan.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvDoan.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvDoan.BackgroundColor = System.Drawing.Color.White;
  this.dgvDoan.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvDoan.EnableHeadersVisualStyles = false;
  this.dgvDoan.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvDoan.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvDoan.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvDoan.ColumnHeadersHeight = 26;
  this.tabTT.Controls.Add(this.dgvDoan);
  this.label4.Name="label4";
  this.label4.Location=new System.Drawing.Point(15,408);
  this.label4.Size=new System.Drawing.Size(110,25);
  this.label4.TabIndex=4;
  this.label4.Text="Số thanh toán:";
  this.tabTT.Controls.Add(this.label4);
  this.txtSoTT.Name="txtSoTT";
  this.txtSoTT.Location=new System.Drawing.Point(125,405);
  this.txtSoTT.Size=new System.Drawing.Size(150,25);
  this.txtSoTT.TabIndex=5;
  this.txtSoTT.MaxLength = 1500;
  this.tabTT.Controls.Add(this.txtSoTT);
  this.label6.Name="label6";
  this.label6.Location=new System.Drawing.Point(320,408);
  this.label6.Size=new System.Drawing.Size(90,25);
  this.label6.TabIndex=6;
  this.label6.Text="Phiếu đoàn:";
  this.tabTT.Controls.Add(this.label6);
  this.txtSoDK.Name="txtSoDK";
  this.txtSoDK.Location=new System.Drawing.Point(410,405);
  this.txtSoDK.Size=new System.Drawing.Size(150,25);
  this.txtSoDK.TabIndex=7;
  this.txtSoDK.MaxLength = 1500;
  this.tabTT.Controls.Add(this.txtSoDK);
  this.label8.Name="label8";
  this.label8.Location=new System.Drawing.Point(595,408);
  this.label8.Size=new System.Drawing.Size(140,25);
  this.label8.TabIndex=8;
  this.label8.Text="Ngày thanh toán:";
  this.tabTT.Controls.Add(this.label8);
  this.dtTT.Name="dtTT";
  this.dtTT.Location=new System.Drawing.Point(735,405);
  this.dtTT.Size=new System.Drawing.Size(160,25);
  this.dtTT.TabIndex=9;
  this.dtTT.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
  this.dtTT.CustomFormat = "dd/MM/yyyy";
  this.tabTT.Controls.Add(this.dtTT);
  this.label10.Name="label10";
  this.label10.Location=new System.Drawing.Point(15,450);
  this.label10.Size=new System.Drawing.Size(110,25);
  this.label10.TabIndex=10;
  this.label10.Text="Số tiền:";
  this.tabTT.Controls.Add(this.label10);
  this.numTien.Name="numTien";
  this.numTien.Location=new System.Drawing.Point(125,447);
  this.numTien.Size=new System.Drawing.Size(175,25);
  this.numTien.TabIndex=11;
  this.numTien.Minimum = 0M;
  this.numTien.Maximum = 999999999999M;
  this.numTien.Value = 0M;
  this.numTien.ThousandsSeparator = true;
  this.tabTT.Controls.Add(this.numTien);
  this.label12.Name="label12";
  this.label12.Location=new System.Drawing.Point(320,450);
  this.label12.Size=new System.Drawing.Size(90,25);
  this.label12.TabIndex=12;
  this.label12.Text="Ghi chú:";
  this.tabTT.Controls.Add(this.label12);
  this.txtNote.Name="txtNote";
  this.txtNote.Location=new System.Drawing.Point(410,447);
  this.txtNote.Size=new System.Drawing.Size(340,25);
  this.txtNote.TabIndex=13;
  this.txtNote.MaxLength = 1500;
  this.tabTT.Controls.Add(this.txtNote);
  this.btnThanhToan.Name="btnThanhToan";
  this.btnThanhToan.Location=new System.Drawing.Point(810,444);
  this.btnThanhToan.Size=new System.Drawing.Size(160,34);
  this.btnThanhToan.TabIndex=14;
  this.btnThanhToan.Text="Ghi nhận thanh toán";
  this.btnThanhToan.UseVisualStyleBackColor = false;
  this.btnThanhToan.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnThanhToan.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnThanhToan.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabTT.Controls.Add(this.btnThanhToan);
  this.label15.Name="label15";
  this.label15.Location=new System.Drawing.Point(15,23);
  this.label15.Size=new System.Drawing.Size(90,25);
  this.label15.TabIndex=15;
  this.label15.Text="Loại khách:";
  this.tabKS.Controls.Add(this.label15);
  this.cboLoai.Name="cboLoai";
  this.cboLoai.Location=new System.Drawing.Point(105,20);
  this.cboLoai.Size=new System.Drawing.Size(95,25);
  this.cboLoai.TabIndex=16;
  this.cboLoai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.tabKS.Controls.Add(this.cboLoai);
  this.label17.Name="label17";
  this.label17.Location=new System.Drawing.Point(230,23);
  this.label17.Size=new System.Drawing.Size(155,25);
  this.label17.TabIndex=17;
  this.label17.Text="Đăng ký đã kết thúc:";
  this.tabKS.Controls.Add(this.label17);
  this.cboDK.Name="cboDK";
  this.cboDK.Location=new System.Drawing.Point(385,20);
  this.cboDK.Size=new System.Drawing.Size(285,25);
  this.cboDK.TabIndex=18;
  this.cboDK.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.tabKS.Controls.Add(this.cboDK);
  this.label19.Name="label19";
  this.label19.Location=new System.Drawing.Point(730,23);
  this.label19.Size=new System.Drawing.Size(65,25);
  this.label19.TabIndex=19;
  this.label19.Text="Mã KS:";
  this.tabKS.Controls.Add(this.label19);
  this.txtMaKS.Name="txtMaKS";
  this.txtMaKS.Location=new System.Drawing.Point(795,20);
  this.txtMaKS.Size=new System.Drawing.Size(160,25);
  this.txtMaKS.TabIndex=20;
  this.txtMaKS.MaxLength = 1500;
  this.tabKS.Controls.Add(this.txtMaKS);
  this.label21.Name="label21";
  this.label21.Location=new System.Drawing.Point(15,61);
  this.label21.Size=new System.Drawing.Size(90,25);
  this.label21.TabIndex=21;
  this.label21.Text="Ngày gửi:";
  this.tabKS.Controls.Add(this.label21);
  this.dtGui.Name="dtGui";
  this.dtGui.Location=new System.Drawing.Point(105,58);
  this.dtGui.Size=new System.Drawing.Size(160,25);
  this.dtGui.TabIndex=22;
  this.dtGui.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
  this.dtGui.CustomFormat = "dd/MM/yyyy";
  this.tabKS.Controls.Add(this.dtGui);
  this.btnGui.Name="btnGui";
  this.btnGui.Location=new System.Drawing.Point(810,55);
  this.btnGui.Size=new System.Drawing.Size(160,34);
  this.btnGui.TabIndex=23;
  this.btnGui.Text="Gửi phiếu khảo sát";
  this.btnGui.UseVisualStyleBackColor = false;
  this.btnGui.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnGui.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnGui.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabKS.Controls.Add(this.btnGui);
  this.dgvKS.Name="dgvKS";
  this.dgvKS.Location=new System.Drawing.Point(12,105);
  this.dgvKS.Size=new System.Drawing.Size(965,335);
  this.dgvKS.TabIndex=24;
  this.dgvKS.ReadOnly = true;
  this.dgvKS.AllowUserToAddRows = false;
  this.dgvKS.AllowUserToDeleteRows = false;
  this.dgvKS.MultiSelect = false;
  this.dgvKS.RowHeadersVisible = true;
  this.dgvKS.RowHeadersWidth = 28;
  this.dgvKS.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvKS.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvKS.BackgroundColor = System.Drawing.Color.White;
  this.dgvKS.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvKS.EnableHeadersVisualStyles = false;
  this.dgvKS.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvKS.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvKS.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvKS.ColumnHeadersHeight = 26;
  this.tabKS.Controls.Add(this.dgvKS);
  this.label25.Name="label25";
  this.label25.Location=new System.Drawing.Point(15,458);
  this.label25.Size=new System.Drawing.Size(90,25);
  this.label25.TabIndex=25;
  this.label25.Text="Phiếu chọn:";
  this.tabKS.Controls.Add(this.label25);
  this.txtKSChon.Name="txtKSChon";
  this.txtKSChon.Location=new System.Drawing.Point(105,455);
  this.txtKSChon.Size=new System.Drawing.Size(150,25);
  this.txtKSChon.TabIndex=26;
  this.txtKSChon.MaxLength = 1500;
  this.tabKS.Controls.Add(this.txtKSChon);
  this.label27.Name="label27";
  this.label27.Location=new System.Drawing.Point(320,458);
  this.label27.Size=new System.Drawing.Size(120,25);
  this.label27.TabIndex=27;
  this.label27.Text="Ngày phản hồi:";
  this.tabKS.Controls.Add(this.label27);
  this.dtPH.Name="dtPH";
  this.dtPH.Location=new System.Drawing.Point(440,455);
  this.dtPH.Size=new System.Drawing.Size(160,25);
  this.dtPH.TabIndex=28;
  this.dtPH.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
  this.dtPH.CustomFormat = "dd/MM/yyyy";
  this.tabKS.Controls.Add(this.dtPH);
  this.label29.Name="label29";
  this.label29.Location=new System.Drawing.Point(660,458);
  this.label29.Size=new System.Drawing.Size(115,25);
  this.label29.TabIndex=29;
  this.label29.Text="Điểm (1 - 5):";
  this.tabKS.Controls.Add(this.label29);
  this.numDiem.Name="numDiem";
  this.numDiem.Location=new System.Drawing.Point(775,455);
  this.numDiem.Size=new System.Drawing.Size(90,25);
  this.numDiem.TabIndex=30;
  this.numDiem.Minimum = 1M;
  this.numDiem.Maximum = 5M;
  this.numDiem.Value = 4M;
  this.numDiem.ThousandsSeparator = true;
  this.tabKS.Controls.Add(this.numDiem);
  this.label31.Name="label31";
  this.label31.Location=new System.Drawing.Point(15,501);
  this.label31.Size=new System.Drawing.Size(90,25);
  this.label31.TabIndex=31;
  this.label31.Text="Góp ý:";
  this.tabKS.Controls.Add(this.label31);
  this.txtGopY.Name="txtGopY";
  this.txtGopY.Location=new System.Drawing.Point(105,498);
  this.txtGopY.Size=new System.Drawing.Size(650,25);
  this.txtGopY.TabIndex=32;
  this.txtGopY.MaxLength = 1500;
  this.tabKS.Controls.Add(this.txtGopY);
  this.btnGhiPH.Name="btnGhiPH";
  this.btnGhiPH.Location=new System.Drawing.Point(810,494);
  this.btnGhiPH.Size=new System.Drawing.Size(160,34);
  this.btnGhiPH.TabIndex=33;
  this.btnGhiPH.Text="Ghi nhận góp ý";
  this.btnGhiPH.UseVisualStyleBackColor = false;
  this.btnGhiPH.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnGhiPH.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnGhiPH.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabKS.Controls.Add(this.btnGhiPH);
  this.btnDong.Name="btnDong";
  this.btnDong.Location=new System.Drawing.Point(910,640);
  this.btnDong.Size=new System.Drawing.Size(110,32);
  this.btnDong.TabIndex=34;
  this.btnDong.Text="Đóng";
  this.btnDong.UseVisualStyleBackColor = false;
  this.btnDong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDong);
  this.AutoScaleDimensions=new System.Drawing.SizeF(7F,15F);
  this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
  this.ClientSize=new System.Drawing.Size(1040,680);
  this.Font=new System.Drawing.Font("Segoe UI",9F);
  this.BackColor=System.Drawing.Color.FromArgb(240,240,240);
  this.StartPosition=System.Windows.Forms.FormStartPosition.CenterParent;
  this.Name="FrmKetThucKhaoSat";
  this.Text="Kết thúc tour - thanh toán đoàn - khảo sát";
  this.Load+=new System.EventHandler(this.FrmKetThucKhaoSat_Load);
  this.ResumeLayout(false);
  this.PerformLayout();
 }
 private System.Windows.Forms.TabControl tabs;
 private System.Windows.Forms.TabPage tabTT;
 private System.Windows.Forms.TabPage tabKS;
 private System.Windows.Forms.DataGridView dgvDoan;
 private System.Windows.Forms.Label label4;
 private System.Windows.Forms.TextBox txtSoTT;
 private System.Windows.Forms.Label label6;
 private System.Windows.Forms.TextBox txtSoDK;
 private System.Windows.Forms.Label label8;
 private System.Windows.Forms.DateTimePicker dtTT;
 private System.Windows.Forms.Label label10;
 private System.Windows.Forms.NumericUpDown numTien;
 private System.Windows.Forms.Label label12;
 private System.Windows.Forms.TextBox txtNote;
 private System.Windows.Forms.Button btnThanhToan;
 private System.Windows.Forms.Label label15;
 private System.Windows.Forms.ComboBox cboLoai;
 private System.Windows.Forms.Label label17;
 private System.Windows.Forms.ComboBox cboDK;
 private System.Windows.Forms.Label label19;
 private System.Windows.Forms.TextBox txtMaKS;
 private System.Windows.Forms.Label label21;
 private System.Windows.Forms.DateTimePicker dtGui;
 private System.Windows.Forms.Button btnGui;
 private System.Windows.Forms.DataGridView dgvKS;
 private System.Windows.Forms.Label label25;
 private System.Windows.Forms.TextBox txtKSChon;
 private System.Windows.Forms.Label label27;
 private System.Windows.Forms.DateTimePicker dtPH;
 private System.Windows.Forms.Label label29;
 private System.Windows.Forms.NumericUpDown numDiem;
 private System.Windows.Forms.Label label31;
 private System.Windows.Forms.TextBox txtGopY;
 private System.Windows.Forms.Button btnGhiPH;
 private System.Windows.Forms.Button btnDong;
 }
}