namespace QuanLyDuLich.Forms {
 partial class FrmKhaoSat {
  private System.ComponentModel.IContainer components = null;
  protected override void Dispose(bool disposing) { if(disposing && components!=null) components.Dispose(); base.Dispose(disposing); }
  private void InitializeComponent() {
   this.lblTitle = new System.Windows.Forms.Label();
   this.lbl1 = new System.Windows.Forms.Label();
   this.txtMa = new System.Windows.Forms.TextBox();
   this.lbl3 = new System.Windows.Forms.Label();
   this.cboLoai = new System.Windows.Forms.ComboBox();
   this.lbl5 = new System.Windows.Forms.Label();
   this.cboDK = new System.Windows.Forms.ComboBox();
   this.lbl7 = new System.Windows.Forms.Label();
   this.dtGui = new System.Windows.Forms.DateTimePicker();
   this.btnGui = new System.Windows.Forms.Button();
   this.btnReload = new System.Windows.Forms.Button();
   this.btnClose = new System.Windows.Forms.Button();
   this.dgv = new System.Windows.Forms.DataGridView();
   this.lbl13 = new System.Windows.Forms.Label();
   this.txtChon = new System.Windows.Forms.TextBox();
   this.lbl15 = new System.Windows.Forms.Label();
   this.dtPhanHoi = new System.Windows.Forms.DateTimePicker();
   this.lbl17 = new System.Windows.Forms.Label();
   this.numDiem = new System.Windows.Forms.NumericUpDown();
   this.lbl19 = new System.Windows.Forms.Label();
   this.txtY = new System.Windows.Forms.TextBox();
   this.btnGhi = new System.Windows.Forms.Button();
   this.lblGhiChu = new System.Windows.Forms.Label();
   this.SuspendLayout();
   this.lblTitle.Name = "lblTitle";
   this.lblTitle.Location = new System.Drawing.Point(25,18);
   this.lblTitle.Size = new System.Drawing.Size(1080,38);
   this.lblTitle.TabIndex = 0;
   this.lblTitle.Text = "KHẢO SÁT VÀ GHI NHẬN GÓP Ý";
   this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
   this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(17,60,104);
   this.Controls.Add(this.lblTitle);
   this.lbl1.Name = "lbl1";
   this.lbl1.Location = new System.Drawing.Point(25,80);
   this.lbl1.Size = new System.Drawing.Size(145,26);
   this.lbl1.TabIndex = 1;
   this.lbl1.Text = "Mã khảo sát *";
   this.Controls.Add(this.lbl1);
   this.txtMa.Name = "txtMa";
   this.txtMa.Location = new System.Drawing.Point(170,75);
   this.txtMa.Size = new System.Drawing.Size(220,28);
   this.txtMa.TabIndex = 2;
   this.txtMa.MaxLength = 1500;
   this.Controls.Add(this.txtMa);
   this.lbl3.Name = "lbl3";
   this.lbl3.Location = new System.Drawing.Point(570,80);
   this.lbl3.Size = new System.Drawing.Size(145,26);
   this.lbl3.TabIndex = 3;
   this.lbl3.Text = "Loại (LE / DOAN)";
   this.Controls.Add(this.lbl3);
   this.cboLoai.Name = "cboLoai";
   this.cboLoai.Location = new System.Drawing.Point(715,75);
   this.cboLoai.Size = new System.Drawing.Size(370,28);
   this.cboLoai.TabIndex = 4;
   this.cboLoai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
   this.Controls.Add(this.cboLoai);
   this.lbl5.Name = "lbl5";
   this.lbl5.Location = new System.Drawing.Point(25,120);
   this.lbl5.Size = new System.Drawing.Size(145,26);
   this.lbl5.TabIndex = 5;
   this.lbl5.Text = "Đăng ký đã kết thúc";
   this.Controls.Add(this.lbl5);
   this.cboDK.Name = "cboDK";
   this.cboDK.Location = new System.Drawing.Point(170,115);
   this.cboDK.Size = new System.Drawing.Size(335,28);
   this.cboDK.TabIndex = 6;
   this.cboDK.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
   this.Controls.Add(this.cboDK);
   this.lbl7.Name = "lbl7";
   this.lbl7.Location = new System.Drawing.Point(570,120);
   this.lbl7.Size = new System.Drawing.Size(145,26);
   this.lbl7.TabIndex = 7;
   this.lbl7.Text = "Ngày gửi";
   this.Controls.Add(this.lbl7);
   this.dtGui.Name = "dtGui";
   this.dtGui.Location = new System.Drawing.Point(715,115);
   this.dtGui.Size = new System.Drawing.Size(170,28);
   this.dtGui.TabIndex = 8;
   this.dtGui.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
   this.dtGui.CustomFormat = "dd/MM/yyyy";
   this.Controls.Add(this.dtGui);
   this.btnGui.Name = "btnGui";
   this.btnGui.Location = new System.Drawing.Point(25,165);
   this.btnGui.Size = new System.Drawing.Size(200,38);
   this.btnGui.TabIndex = 9;
   this.btnGui.Text = "Ghi nhận gửi phiếu";
   this.btnGui.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnGui);
   this.btnReload.Name = "btnReload";
   this.btnReload.Location = new System.Drawing.Point(240,165);
   this.btnReload.Size = new System.Drawing.Size(150,38);
   this.btnReload.TabIndex = 10;
   this.btnReload.Text = "Tải lại";
   this.btnReload.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnReload);
   this.btnClose.Name = "btnClose";
   this.btnClose.Location = new System.Drawing.Point(955,165);
   this.btnClose.Size = new System.Drawing.Size(150,38);
   this.btnClose.TabIndex = 11;
   this.btnClose.Text = "Đóng";
   this.btnClose.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnClose);
   this.dgv.Name = "dgv";
   this.dgv.Location = new System.Drawing.Point(25,220);
   this.dgv.Size = new System.Drawing.Size(1080,290);
   this.dgv.TabIndex = 12;
   this.dgv.ReadOnly = true;
   this.dgv.AllowUserToAddRows = false;
   this.dgv.AllowUserToDeleteRows = false;
   this.dgv.MultiSelect = false;
   this.dgv.RowHeadersVisible = false;
   this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
   this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
   this.dgv.BackgroundColor = System.Drawing.Color.White;
   this.dgv.EnableHeadersVisualStyles = false;
   this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(232,239,244);
   this.dgv.ColumnHeadersHeight = 32;
   this.dgv.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(248,250,252);
   this.Controls.Add(this.dgv);
   this.lbl13.Name = "lbl13";
   this.lbl13.Location = new System.Drawing.Point(25,545);
   this.lbl13.Size = new System.Drawing.Size(145,26);
   this.lbl13.TabIndex = 13;
   this.lbl13.Text = "Phiếu được chọn";
   this.Controls.Add(this.lbl13);
   this.txtChon.Name = "txtChon";
   this.txtChon.Location = new System.Drawing.Point(170,540);
   this.txtChon.Size = new System.Drawing.Size(220,28);
   this.txtChon.TabIndex = 14;
   this.txtChon.MaxLength = 1500;
   this.Controls.Add(this.txtChon);
   this.lbl15.Name = "lbl15";
   this.lbl15.Location = new System.Drawing.Point(570,545);
   this.lbl15.Size = new System.Drawing.Size(145,26);
   this.lbl15.TabIndex = 15;
   this.lbl15.Text = "Ngày phản hồi";
   this.Controls.Add(this.lbl15);
   this.dtPhanHoi.Name = "dtPhanHoi";
   this.dtPhanHoi.Location = new System.Drawing.Point(715,540);
   this.dtPhanHoi.Size = new System.Drawing.Size(170,28);
   this.dtPhanHoi.TabIndex = 16;
   this.dtPhanHoi.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
   this.dtPhanHoi.CustomFormat = "dd/MM/yyyy";
   this.Controls.Add(this.dtPhanHoi);
   this.lbl17.Name = "lbl17";
   this.lbl17.Location = new System.Drawing.Point(25,585);
   this.lbl17.Size = new System.Drawing.Size(145,26);
   this.lbl17.TabIndex = 17;
   this.lbl17.Text = "Điểm đánh giá";
   this.Controls.Add(this.lbl17);
   this.numDiem.Name = "numDiem";
   this.numDiem.Location = new System.Drawing.Point(170,580);
   this.numDiem.Size = new System.Drawing.Size(150,28);
   this.numDiem.TabIndex = 18;
   this.numDiem.Minimum = 1M;
   this.numDiem.Maximum = 5M;
   this.numDiem.Value = 4M;
   this.numDiem.ThousandsSeparator = true;
   this.Controls.Add(this.numDiem);
   this.lbl19.Name = "lbl19";
   this.lbl19.Location = new System.Drawing.Point(570,585);
   this.lbl19.Size = new System.Drawing.Size(145,26);
   this.lbl19.TabIndex = 19;
   this.lbl19.Text = "Góp ý";
   this.Controls.Add(this.lbl19);
   this.txtY.Name = "txtY";
   this.txtY.Location = new System.Drawing.Point(715,580);
   this.txtY.Size = new System.Drawing.Size(370,65);
   this.txtY.TabIndex = 20;
   this.txtY.MaxLength = 1500;
   this.txtY.Multiline = true;
   this.txtY.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
   this.Controls.Add(this.txtY);
   this.btnGhi.Name = "btnGhi";
   this.btnGhi.Location = new System.Drawing.Point(25,665);
   this.btnGhi.Size = new System.Drawing.Size(200,38);
   this.btnGhi.TabIndex = 21;
   this.btnGhi.Text = "Lưu phản hồi";
   this.btnGhi.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnGhi);
   this.lblGhiChu.Name = "lblGhiChu";
   this.lblGhiChu.Location = new System.Drawing.Point(25,725);
   this.lblGhiChu.Size = new System.Drawing.Size(1080,42);
   this.lblGhiChu.TabIndex = 22;
   this.lblGhiChu.Text = "Gửi phiếu trong bài LAB là ghi nhận trong CSDL; nhân viên gửi phiếu cho khách qua kênh của công ty.";
   this.Controls.Add(this.lblGhiChu);
   this.AutoScaleDimensions = new System.Drawing.SizeF(7F,15F);
   this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
   this.ClientSize = new System.Drawing.Size(1140,800);
   this.Font = new System.Drawing.Font("Segoe UI",9F);
   this.BackColor = System.Drawing.Color.FromArgb(248,250,252);
   this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
   this.Text = "LAB5 - KHẢO SÁT VÀ GHI NHẬN GÓP Ý";
   this.Name = "FrmKhaoSat";
   this.Load += new System.EventHandler(this.FrmKhaoSat_Load);
   this.ResumeLayout(false);
   this.PerformLayout();
  }
  private System.Windows.Forms.Label lblTitle;
  private System.Windows.Forms.Label lbl1;
  private System.Windows.Forms.TextBox txtMa;
  private System.Windows.Forms.Label lbl3;
  private System.Windows.Forms.ComboBox cboLoai;
  private System.Windows.Forms.Label lbl5;
  private System.Windows.Forms.ComboBox cboDK;
  private System.Windows.Forms.Label lbl7;
  private System.Windows.Forms.DateTimePicker dtGui;
  private System.Windows.Forms.Button btnGui;
  private System.Windows.Forms.Button btnReload;
  private System.Windows.Forms.Button btnClose;
  private System.Windows.Forms.DataGridView dgv;
  private System.Windows.Forms.Label lbl13;
  private System.Windows.Forms.TextBox txtChon;
  private System.Windows.Forms.Label lbl15;
  private System.Windows.Forms.DateTimePicker dtPhanHoi;
  private System.Windows.Forms.Label lbl17;
  private System.Windows.Forms.NumericUpDown numDiem;
  private System.Windows.Forms.Label lbl19;
  private System.Windows.Forms.TextBox txtY;
  private System.Windows.Forms.Button btnGhi;
  private System.Windows.Forms.Label lblGhiChu;
 }
}