namespace QuanLyDuLich.Forms {
 partial class FrmLuongThongKe {
 private System.ComponentModel.IContainer components=null;
 protected override void Dispose(bool disposing){if(disposing && components!=null)components.Dispose();base.Dispose(disposing);}
 private void InitializeComponent(){
  this.tabs=new System.Windows.Forms.TabControl();
  this.tabLuong=new System.Windows.Forms.TabPage();
  this.tabTK=new System.Windows.Forms.TabPage();
  this.label3=new System.Windows.Forms.Label();
  this.numThang=new System.Windows.Forms.NumericUpDown();
  this.label5=new System.Windows.Forms.Label();
  this.numNam=new System.Windows.Forms.NumericUpDown();
  this.btnLuong=new System.Windows.Forms.Button();
  this.label8=new System.Windows.Forms.Label();
  this.dgvLuong=new System.Windows.Forms.DataGridView();
  this.label10=new System.Windows.Forms.Label();
  this.dtTu=new System.Windows.Forms.DateTimePicker();
  this.label12=new System.Windows.Forms.Label();
  this.dtDen=new System.Windows.Forms.DateTimePicker();
  this.btnTK=new System.Windows.Forms.Button();
  this.dgvTK=new System.Windows.Forms.DataGridView();
  this.btnDong=new System.Windows.Forms.Button();
  this.SuspendLayout();
  this.tabs.Name="tabs";
  this.tabs.Location=new System.Drawing.Point(20,15);
  this.tabs.Size=new System.Drawing.Size(960,560);
  this.tabs.TabIndex=0;
  this.Controls.Add(this.tabs);
  this.tabLuong.Name="tabLuong";
  this.tabLuong.Location=new System.Drawing.Point(0,0);
  this.tabLuong.Size=new System.Drawing.Size(950,535);
  this.tabLuong.TabIndex=1;
  this.tabLuong.Text="Lương hướng dẫn viên";
  this.tabLuong.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabLuong);
  this.tabTK.Name="tabTK";
  this.tabTK.Location=new System.Drawing.Point(0,0);
  this.tabTK.Size=new System.Drawing.Size(950,535);
  this.tabTK.TabIndex=2;
  this.tabTK.Text="Thống kê tổng hợp";
  this.tabTK.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabTK);
  this.label3.Name="label3";
  this.label3.Location=new System.Drawing.Point(15,28);
  this.label3.Size=new System.Drawing.Size(70,25);
  this.label3.TabIndex=3;
  this.label3.Text="Tháng:";
  this.tabLuong.Controls.Add(this.label3);
  this.numThang.Name="numThang";
  this.numThang.Location=new System.Drawing.Point(85,25);
  this.numThang.Size=new System.Drawing.Size(75,25);
  this.numThang.TabIndex=4;
  this.numThang.Minimum = 1M;
  this.numThang.Maximum = 12M;
  this.numThang.Value = 9M;
  this.numThang.ThousandsSeparator = true;
  this.tabLuong.Controls.Add(this.numThang);
  this.label5.Name="label5";
  this.label5.Location=new System.Drawing.Point(190,28);
  this.label5.Size=new System.Drawing.Size(65,25);
  this.label5.TabIndex=5;
  this.label5.Text="Năm:";
  this.tabLuong.Controls.Add(this.label5);
  this.numNam.Name="numNam";
  this.numNam.Location=new System.Drawing.Point(255,25);
  this.numNam.Size=new System.Drawing.Size(95,25);
  this.numNam.TabIndex=6;
  this.numNam.Minimum = 1900M;
  this.numNam.Maximum = 9998M;
  this.numNam.Value = 2026M;
  this.numNam.ThousandsSeparator = true;
  this.tabLuong.Controls.Add(this.numNam);
  this.btnLuong.Name="btnLuong";
  this.btnLuong.Location=new System.Drawing.Point(370,20);
  this.btnLuong.Size=new System.Drawing.Size(145,34);
  this.btnLuong.TabIndex=7;
  this.btnLuong.Text="Tính lương";
  this.btnLuong.UseVisualStyleBackColor = false;
  this.btnLuong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnLuong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnLuong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabLuong.Controls.Add(this.btnLuong);
  this.label8.Name="label8";
  this.label8.Location=new System.Drawing.Point(540,29);
  this.label8.Size=new System.Drawing.Size(400,25);
  this.label8.TabIndex=8;
  this.label8.Text="Lương = lương cơ bản + thù lao các tour kết thúc trong tháng";
  this.tabLuong.Controls.Add(this.label8);
  this.dgvLuong.Name="dgvLuong";
  this.dgvLuong.Location=new System.Drawing.Point(12,80);
  this.dgvLuong.Size=new System.Drawing.Size(930,430);
  this.dgvLuong.TabIndex=9;
  this.dgvLuong.ReadOnly = true;
  this.dgvLuong.AllowUserToAddRows = false;
  this.dgvLuong.AllowUserToDeleteRows = false;
  this.dgvLuong.MultiSelect = false;
  this.dgvLuong.RowHeadersVisible = true;
  this.dgvLuong.RowHeadersWidth = 28;
  this.dgvLuong.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvLuong.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvLuong.BackgroundColor = System.Drawing.Color.White;
  this.dgvLuong.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvLuong.EnableHeadersVisualStyles = false;
  this.dgvLuong.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvLuong.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvLuong.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvLuong.ColumnHeadersHeight = 26;
  this.tabLuong.Controls.Add(this.dgvLuong);
  this.label10.Name="label10";
  this.label10.Location=new System.Drawing.Point(15,28);
  this.label10.Size=new System.Drawing.Size(70,25);
  this.label10.TabIndex=10;
  this.label10.Text="Từ ngày:";
  this.tabTK.Controls.Add(this.label10);
  this.dtTu.Name="dtTu";
  this.dtTu.Location=new System.Drawing.Point(85,25);
  this.dtTu.Size=new System.Drawing.Size(160,25);
  this.dtTu.TabIndex=11;
  this.dtTu.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
  this.dtTu.CustomFormat = "dd/MM/yyyy";
  this.tabTK.Controls.Add(this.dtTu);
  this.label12.Name="label12";
  this.label12.Location=new System.Drawing.Point(285,28);
  this.label12.Size=new System.Drawing.Size(90,25);
  this.label12.TabIndex=12;
  this.label12.Text="Đến ngày:";
  this.tabTK.Controls.Add(this.label12);
  this.dtDen.Name="dtDen";
  this.dtDen.Location=new System.Drawing.Point(375,25);
  this.dtDen.Size=new System.Drawing.Size(160,25);
  this.dtDen.TabIndex=13;
  this.dtDen.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
  this.dtDen.CustomFormat = "dd/MM/yyyy";
  this.tabTK.Controls.Add(this.dtDen);
  this.btnTK.Name="btnTK";
  this.btnTK.Location=new System.Drawing.Point(600,20);
  this.btnTK.Size=new System.Drawing.Size(145,34);
  this.btnTK.TabIndex=14;
  this.btnTK.Text="Thống kê";
  this.btnTK.UseVisualStyleBackColor = false;
  this.btnTK.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnTK.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnTK.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabTK.Controls.Add(this.btnTK);
  this.dgvTK.Name="dgvTK";
  this.dgvTK.Location=new System.Drawing.Point(12,80);
  this.dgvTK.Size=new System.Drawing.Size(930,430);
  this.dgvTK.TabIndex=15;
  this.dgvTK.ReadOnly = true;
  this.dgvTK.AllowUserToAddRows = false;
  this.dgvTK.AllowUserToDeleteRows = false;
  this.dgvTK.MultiSelect = false;
  this.dgvTK.RowHeadersVisible = true;
  this.dgvTK.RowHeadersWidth = 28;
  this.dgvTK.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvTK.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvTK.BackgroundColor = System.Drawing.Color.White;
  this.dgvTK.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvTK.EnableHeadersVisualStyles = false;
  this.dgvTK.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvTK.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvTK.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvTK.ColumnHeadersHeight = 26;
  this.tabTK.Controls.Add(this.dgvTK);
  this.btnDong.Name="btnDong";
  this.btnDong.Location=new System.Drawing.Point(870,595);
  this.btnDong.Size=new System.Drawing.Size(110,32);
  this.btnDong.TabIndex=16;
  this.btnDong.Text="Đóng";
  this.btnDong.UseVisualStyleBackColor = false;
  this.btnDong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDong);
  this.AutoScaleDimensions=new System.Drawing.SizeF(7F,15F);
  this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
  this.ClientSize=new System.Drawing.Size(1000,640);
  this.Font=new System.Drawing.Font("Segoe UI",9F);
  this.BackColor=System.Drawing.Color.FromArgb(240,240,240);
  this.StartPosition=System.Windows.Forms.FormStartPosition.CenterParent;
  this.Name="FrmLuongThongKe";
  this.Text="Lương hướng dẫn viên - thống kê";
  this.Load+=new System.EventHandler(this.FrmLuongThongKe_Load);
  this.ResumeLayout(false);
  this.PerformLayout();
 }
 private System.Windows.Forms.TabControl tabs;
 private System.Windows.Forms.TabPage tabLuong;
 private System.Windows.Forms.TabPage tabTK;
 private System.Windows.Forms.Label label3;
 private System.Windows.Forms.NumericUpDown numThang;
 private System.Windows.Forms.Label label5;
 private System.Windows.Forms.NumericUpDown numNam;
 private System.Windows.Forms.Button btnLuong;
 private System.Windows.Forms.Label label8;
 private System.Windows.Forms.DataGridView dgvLuong;
 private System.Windows.Forms.Label label10;
 private System.Windows.Forms.DateTimePicker dtTu;
 private System.Windows.Forms.Label label12;
 private System.Windows.Forms.DateTimePicker dtDen;
 private System.Windows.Forms.Button btnTK;
 private System.Windows.Forms.DataGridView dgvTK;
 private System.Windows.Forms.Button btnDong;
 }
}