namespace QuanLyDuLich.Forms {
 partial class FrmMain {
 private System.ComponentModel.IContainer components=null;
 protected override void Dispose(bool disposing){if(disposing && components!=null)components.Dispose();base.Dispose(disposing);}
 private void InitializeComponent(){
  this.lblTitle=new System.Windows.Forms.Label();
  this.btnFrmDanhMuc=new System.Windows.Forms.Button();
  this.btnFrmTour=new System.Windows.Forms.Button();
  this.btnFrmChuyenLe=new System.Windows.Forms.Button();
  this.btnFrmDangKyLe=new System.Windows.Forms.Button();
  this.btnFrmDangKyDoan=new System.Windows.Forms.Button();
  this.btnFrmPhanCongHDV=new System.Windows.Forms.Button();
  this.btnFrmKetThucKhaoSat=new System.Windows.Forms.Button();
  this.btnFrmLuongThongKe=new System.Windows.Forms.Button();
  this.btnThoat=new System.Windows.Forms.Button();
  this.SuspendLayout();
  this.lblTitle.Name="lblTitle";
  this.lblTitle.Location=new System.Drawing.Point(20,25);
  this.lblTitle.Size=new System.Drawing.Size(640,25);
  this.lblTitle.TabIndex=0;
  this.lblTitle.Text="CÔNG TY DU LỊCH VĂN HÓA VIỆT";
  this.lblTitle.Font = new System.Drawing.Font("Segoe UI",14F,System.Drawing.FontStyle.Bold);
  this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(0,64,112);
  this.lblTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
  this.Controls.Add(this.lblTitle);
  this.btnFrmDanhMuc.Name="btnFrmDanhMuc";
  this.btnFrmDanhMuc.Location=new System.Drawing.Point(60,85);
  this.btnFrmDanhMuc.Size=new System.Drawing.Size(270,58);
  this.btnFrmDanhMuc.TabIndex=1;
  this.btnFrmDanhMuc.Text="Danh mục";
  this.btnFrmDanhMuc.UseVisualStyleBackColor = false;
  this.btnFrmDanhMuc.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnFrmDanhMuc.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnFrmDanhMuc.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnFrmDanhMuc);
  this.btnFrmTour.Name="btnFrmTour";
  this.btnFrmTour.Location=new System.Drawing.Point(350,85);
  this.btnFrmTour.Size=new System.Drawing.Size(270,58);
  this.btnFrmTour.TabIndex=2;
  this.btnFrmTour.Text="Tour - hành trình";
  this.btnFrmTour.UseVisualStyleBackColor = false;
  this.btnFrmTour.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnFrmTour.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnFrmTour.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnFrmTour);
  this.btnFrmChuyenLe.Name="btnFrmChuyenLe";
  this.btnFrmChuyenLe.Location=new System.Drawing.Point(60,160);
  this.btnFrmChuyenLe.Size=new System.Drawing.Size(270,58);
  this.btnFrmChuyenLe.TabIndex=3;
  this.btnFrmChuyenLe.Text="Lịch chuyến khách lẻ";
  this.btnFrmChuyenLe.UseVisualStyleBackColor = false;
  this.btnFrmChuyenLe.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnFrmChuyenLe.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnFrmChuyenLe.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnFrmChuyenLe);
  this.btnFrmDangKyLe.Name="btnFrmDangKyLe";
  this.btnFrmDangKyLe.Location=new System.Drawing.Point(350,160);
  this.btnFrmDangKyLe.Size=new System.Drawing.Size(270,58);
  this.btnFrmDangKyLe.TabIndex=4;
  this.btnFrmDangKyLe.Text="Đăng ký khách lẻ";
  this.btnFrmDangKyLe.UseVisualStyleBackColor = false;
  this.btnFrmDangKyLe.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnFrmDangKyLe.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnFrmDangKyLe.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnFrmDangKyLe);
  this.btnFrmDangKyDoan.Name="btnFrmDangKyDoan";
  this.btnFrmDangKyDoan.Location=new System.Drawing.Point(60,235);
  this.btnFrmDangKyDoan.Size=new System.Drawing.Size(270,58);
  this.btnFrmDangKyDoan.TabIndex=5;
  this.btnFrmDangKyDoan.Text="Đăng ký theo đoàn";
  this.btnFrmDangKyDoan.UseVisualStyleBackColor = false;
  this.btnFrmDangKyDoan.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnFrmDangKyDoan.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnFrmDangKyDoan.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnFrmDangKyDoan);
  this.btnFrmPhanCongHDV.Name="btnFrmPhanCongHDV";
  this.btnFrmPhanCongHDV.Location=new System.Drawing.Point(350,235);
  this.btnFrmPhanCongHDV.Size=new System.Drawing.Size(270,58);
  this.btnFrmPhanCongHDV.TabIndex=6;
  this.btnFrmPhanCongHDV.Text="Phân công hướng dẫn viên";
  this.btnFrmPhanCongHDV.UseVisualStyleBackColor = false;
  this.btnFrmPhanCongHDV.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnFrmPhanCongHDV.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnFrmPhanCongHDV.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnFrmPhanCongHDV);
  this.btnFrmKetThucKhaoSat.Name="btnFrmKetThucKhaoSat";
  this.btnFrmKetThucKhaoSat.Location=new System.Drawing.Point(60,310);
  this.btnFrmKetThucKhaoSat.Size=new System.Drawing.Size(270,58);
  this.btnFrmKetThucKhaoSat.TabIndex=7;
  this.btnFrmKetThucKhaoSat.Text="Kết thúc tour - khảo sát";
  this.btnFrmKetThucKhaoSat.UseVisualStyleBackColor = false;
  this.btnFrmKetThucKhaoSat.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnFrmKetThucKhaoSat.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnFrmKetThucKhaoSat.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnFrmKetThucKhaoSat);
  this.btnFrmLuongThongKe.Name="btnFrmLuongThongKe";
  this.btnFrmLuongThongKe.Location=new System.Drawing.Point(350,310);
  this.btnFrmLuongThongKe.Size=new System.Drawing.Size(270,58);
  this.btnFrmLuongThongKe.TabIndex=8;
  this.btnFrmLuongThongKe.Text="Lương - thống kê";
  this.btnFrmLuongThongKe.UseVisualStyleBackColor = false;
  this.btnFrmLuongThongKe.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnFrmLuongThongKe.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnFrmLuongThongKe.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnFrmLuongThongKe);
  this.btnThoat.Name="btnThoat";
  this.btnThoat.Location=new System.Drawing.Point(205,405);
  this.btnThoat.Size=new System.Drawing.Size(270,58);
  this.btnThoat.TabIndex=9;
  this.btnThoat.Text="Thoát";
  this.btnThoat.UseVisualStyleBackColor = false;
  this.btnThoat.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnThoat.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnThoat.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnThoat);
  this.AutoScaleDimensions=new System.Drawing.SizeF(7F,15F);
  this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
  this.ClientSize=new System.Drawing.Size(680,535);
  this.Font=new System.Drawing.Font("Segoe UI",9F);
  this.BackColor=System.Drawing.Color.FromArgb(240,240,240);
  this.StartPosition=System.Windows.Forms.FormStartPosition.CenterParent;
  this.Name="FrmMain";
  this.Text="Quản lý công ty du lịch Văn Hóa Việt";
  this.Load+=new System.EventHandler(this.FrmMain_Load);
  this.ResumeLayout(false);
  this.PerformLayout();
 }
 private System.Windows.Forms.Label lblTitle;
 private System.Windows.Forms.Button btnFrmDanhMuc;
 private System.Windows.Forms.Button btnFrmTour;
 private System.Windows.Forms.Button btnFrmChuyenLe;
 private System.Windows.Forms.Button btnFrmDangKyLe;
 private System.Windows.Forms.Button btnFrmDangKyDoan;
 private System.Windows.Forms.Button btnFrmPhanCongHDV;
 private System.Windows.Forms.Button btnFrmKetThucKhaoSat;
 private System.Windows.Forms.Button btnFrmLuongThongKe;
 private System.Windows.Forms.Button btnThoat;
 }
}