namespace QuanLyDuLich.Forms {
 partial class FrmPhanCongHDV {
 private System.ComponentModel.IContainer components=null;
 protected override void Dispose(bool disposing){if(disposing && components!=null)components.Dispose();base.Dispose(disposing);}
 private void InitializeComponent(){
  this.label0=new System.Windows.Forms.Label();
  this.txtMa=new System.Windows.Forms.TextBox();
  this.label2=new System.Windows.Forms.Label();
  this.cboHDV=new System.Windows.Forms.ComboBox();
  this.label4=new System.Windows.Forms.Label();
  this.cboLoai=new System.Windows.Forms.ComboBox();
  this.label6=new System.Windows.Forms.Label();
  this.cboDT=new System.Windows.Forms.ComboBox();
  this.label8=new System.Windows.Forms.Label();
  this.numThuLao=new System.Windows.Forms.NumericUpDown();
  this.btnPhanCong=new System.Windows.Forms.Button();
  this.dgv=new System.Windows.Forms.DataGridView();
  this.btnDong=new System.Windows.Forms.Button();
  this.SuspendLayout();
  this.label0.Name="label0";
  this.label0.Location=new System.Drawing.Point(25,28);
  this.label0.Size=new System.Drawing.Size(100,25);
  this.label0.TabIndex=0;
  this.label0.Text="Mã phân công:";
  this.Controls.Add(this.label0);
  this.txtMa.Name="txtMa";
  this.txtMa.Location=new System.Drawing.Point(125,25);
  this.txtMa.Size=new System.Drawing.Size(150,25);
  this.txtMa.TabIndex=1;
  this.txtMa.MaxLength = 1500;
  this.Controls.Add(this.txtMa);
  this.label2.Name="label2";
  this.label2.Location=new System.Drawing.Point(355,28);
  this.label2.Size=new System.Drawing.Size(140,25);
  this.label2.TabIndex=2;
  this.label2.Text="Hướng dẫn viên:";
  this.Controls.Add(this.label2);
  this.cboHDV.Name="cboHDV";
  this.cboHDV.Location=new System.Drawing.Point(495,25);
  this.cboHDV.Size=new System.Drawing.Size(420,25);
  this.cboHDV.TabIndex=3;
  this.cboHDV.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.Controls.Add(this.cboHDV);
  this.label4.Name="label4";
  this.label4.Location=new System.Drawing.Point(25,68);
  this.label4.Size=new System.Drawing.Size(100,25);
  this.label4.TabIndex=4;
  this.label4.Text="Loại:";
  this.Controls.Add(this.label4);
  this.cboLoai.Name="cboLoai";
  this.cboLoai.Location=new System.Drawing.Point(125,65);
  this.cboLoai.Size=new System.Drawing.Size(150,25);
  this.cboLoai.TabIndex=5;
  this.cboLoai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.Controls.Add(this.cboLoai);
  this.label6.Name="label6";
  this.label6.Location=new System.Drawing.Point(355,68);
  this.label6.Size=new System.Drawing.Size(140,25);
  this.label6.TabIndex=6;
  this.label6.Text="Chuyến / đoàn:";
  this.Controls.Add(this.label6);
  this.cboDT.Name="cboDT";
  this.cboDT.Location=new System.Drawing.Point(495,65);
  this.cboDT.Size=new System.Drawing.Size(420,25);
  this.cboDT.TabIndex=7;
  this.cboDT.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.Controls.Add(this.cboDT);
  this.label8.Name="label8";
  this.label8.Location=new System.Drawing.Point(25,108);
  this.label8.Size=new System.Drawing.Size(100,25);
  this.label8.TabIndex=8;
  this.label8.Text="Thù lao tour:";
  this.Controls.Add(this.label8);
  this.numThuLao.Name="numThuLao";
  this.numThuLao.Location=new System.Drawing.Point(125,105);
  this.numThuLao.Size=new System.Drawing.Size(180,25);
  this.numThuLao.TabIndex=9;
  this.numThuLao.Minimum = 0M;
  this.numThuLao.Maximum = 999999999999M;
  this.numThuLao.Value = 1500000M;
  this.numThuLao.ThousandsSeparator = true;
  this.Controls.Add(this.numThuLao);
  this.btnPhanCong.Name="btnPhanCong";
  this.btnPhanCong.Location=new System.Drawing.Point(800,100);
  this.btnPhanCong.Size=new System.Drawing.Size(175,34);
  this.btnPhanCong.TabIndex=10;
  this.btnPhanCong.Text="Phân công";
  this.btnPhanCong.UseVisualStyleBackColor = false;
  this.btnPhanCong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnPhanCong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnPhanCong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnPhanCong);
  this.dgv.Name="dgv";
  this.dgv.Location=new System.Drawing.Point(25,155);
  this.dgv.Size=new System.Drawing.Size(950,425);
  this.dgv.TabIndex=11;
  this.dgv.ReadOnly = true;
  this.dgv.AllowUserToAddRows = false;
  this.dgv.AllowUserToDeleteRows = false;
  this.dgv.MultiSelect = false;
  this.dgv.RowHeadersVisible = true;
  this.dgv.RowHeadersWidth = 28;
  this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgv.BackgroundColor = System.Drawing.Color.White;
  this.dgv.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgv.EnableHeadersVisualStyles = false;
  this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgv.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgv.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgv.ColumnHeadersHeight = 26;
  this.Controls.Add(this.dgv);
  this.btnDong.Name="btnDong";
  this.btnDong.Location=new System.Drawing.Point(865,595);
  this.btnDong.Size=new System.Drawing.Size(110,32);
  this.btnDong.TabIndex=12;
  this.btnDong.Text="Đóng";
  this.btnDong.UseVisualStyleBackColor = false;
  this.btnDong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDong);
  this.AutoScaleDimensions=new System.Drawing.SizeF(7F,15F);
  this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
  this.ClientSize=new System.Drawing.Size(1000,640);
  this.Font=new System.Drawing.Font("Segoe UI",9F);
  this.BackColor=System.Drawing.Color.FromArgb(240,240,240);
  this.StartPosition=System.Windows.Forms.FormStartPosition.CenterParent;
  this.Name="FrmPhanCongHDV";
  this.Text="Phân công hướng dẫn viên";
  this.Load+=new System.EventHandler(this.FrmPhanCongHDV_Load);
  this.ResumeLayout(false);
  this.PerformLayout();
 }
 private System.Windows.Forms.Label label0;
 private System.Windows.Forms.TextBox txtMa;
 private System.Windows.Forms.Label label2;
 private System.Windows.Forms.ComboBox cboHDV;
 private System.Windows.Forms.Label label4;
 private System.Windows.Forms.ComboBox cboLoai;
 private System.Windows.Forms.Label label6;
 private System.Windows.Forms.ComboBox cboDT;
 private System.Windows.Forms.Label label8;
 private System.Windows.Forms.NumericUpDown numThuLao;
 private System.Windows.Forms.Button btnPhanCong;
 private System.Windows.Forms.DataGridView dgv;
 private System.Windows.Forms.Button btnDong;
 }
}