namespace QuanLyDuLich.Forms {
 partial class FrmThanhToanDoan {
  private System.ComponentModel.IContainer components = null;
  protected override void Dispose(bool disposing) { if(disposing && components!=null) components.Dispose(); base.Dispose(disposing); }
  private void InitializeComponent() {
   this.lblTitle = new System.Windows.Forms.Label();
   this.lbl1 = new System.Windows.Forms.Label();
   this.txtMa = new System.Windows.Forms.TextBox();
   this.lbl3 = new System.Windows.Forms.Label();
   this.txtSo = new System.Windows.Forms.TextBox();
   this.lbl5 = new System.Windows.Forms.Label();
   this.dtNgay = new System.Windows.Forms.DateTimePicker();
   this.lbl7 = new System.Windows.Forms.Label();
   this.numTien = new System.Windows.Forms.NumericUpDown();
   this.lbl9 = new System.Windows.Forms.Label();
   this.txtNote = new System.Windows.Forms.TextBox();
   this.btnPay = new System.Windows.Forms.Button();
   this.btnReload = new System.Windows.Forms.Button();
   this.btnClose = new System.Windows.Forms.Button();
   this.lblDoan = new System.Windows.Forms.Label();
   this.dgv = new System.Windows.Forms.DataGridView();
   this.lblTT = new System.Windows.Forms.Label();
   this.dgvTT = new System.Windows.Forms.DataGridView();
   this.SuspendLayout();
   this.lblTitle.Name = "lblTitle";
   this.lblTitle.Location = new System.Drawing.Point(25,18);
   this.lblTitle.Size = new System.Drawing.Size(1080,38);
   this.lblTitle.TabIndex = 0;
   this.lblTitle.Text = "THANH TOÁN KINH PHÍ ĐOÀN SAU TOUR";
   this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
   this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(17,60,104);
   this.Controls.Add(this.lblTitle);
   this.lbl1.Name = "lbl1";
   this.lbl1.Location = new System.Drawing.Point(25,80);
   this.lbl1.Size = new System.Drawing.Size(145,26);
   this.lbl1.TabIndex = 1;
   this.lbl1.Text = "Mã thanh toán *";
   this.Controls.Add(this.lbl1);
   this.txtMa.Name = "txtMa";
   this.txtMa.Location = new System.Drawing.Point(170,75);
   this.txtMa.Size = new System.Drawing.Size(220,28);
   this.txtMa.TabIndex = 2;
   this.txtMa.MaxLength = 1500;
   this.Controls.Add(this.txtMa);
   this.lbl3.Name = "lbl3";
   this.lbl3.Location = new System.Drawing.Point(570,80);
   this.lbl3.Size = new System.Drawing.Size(145,26);
   this.lbl3.TabIndex = 3;
   this.lbl3.Text = "Số phiếu đoàn *";
   this.Controls.Add(this.lbl3);
   this.txtSo.Name = "txtSo";
   this.txtSo.Location = new System.Drawing.Point(715,75);
   this.txtSo.Size = new System.Drawing.Size(370,28);
   this.txtSo.TabIndex = 4;
   this.txtSo.MaxLength = 1500;
   this.Controls.Add(this.txtSo);
   this.lbl5.Name = "lbl5";
   this.lbl5.Location = new System.Drawing.Point(25,120);
   this.lbl5.Size = new System.Drawing.Size(145,26);
   this.lbl5.TabIndex = 5;
   this.lbl5.Text = "Ngày thanh toán";
   this.Controls.Add(this.lbl5);
   this.dtNgay.Name = "dtNgay";
   this.dtNgay.Location = new System.Drawing.Point(170,115);
   this.dtNgay.Size = new System.Drawing.Size(170,28);
   this.dtNgay.TabIndex = 6;
   this.dtNgay.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
   this.dtNgay.CustomFormat = "dd/MM/yyyy";
   this.Controls.Add(this.dtNgay);
   this.lbl7.Name = "lbl7";
   this.lbl7.Location = new System.Drawing.Point(570,120);
   this.lbl7.Size = new System.Drawing.Size(145,26);
   this.lbl7.TabIndex = 7;
   this.lbl7.Text = "Số tiền *";
   this.Controls.Add(this.lbl7);
   this.numTien.Name = "numTien";
   this.numTien.Location = new System.Drawing.Point(715,115);
   this.numTien.Size = new System.Drawing.Size(150,28);
   this.numTien.TabIndex = 8;
   this.numTien.Minimum = 0M;
   this.numTien.Maximum = 999999999999M;
   this.numTien.Value = 0M;
   this.numTien.ThousandsSeparator = true;
   this.Controls.Add(this.numTien);
   this.lbl9.Name = "lbl9";
   this.lbl9.Location = new System.Drawing.Point(25,160);
   this.lbl9.Size = new System.Drawing.Size(145,26);
   this.lbl9.TabIndex = 9;
   this.lbl9.Text = "Ghi chú";
   this.Controls.Add(this.lbl9);
   this.txtNote.Name = "txtNote";
   this.txtNote.Location = new System.Drawing.Point(170,155);
   this.txtNote.Size = new System.Drawing.Size(850,28);
   this.txtNote.TabIndex = 10;
   this.txtNote.MaxLength = 1500;
   this.Controls.Add(this.txtNote);
   this.btnPay.Name = "btnPay";
   this.btnPay.Location = new System.Drawing.Point(25,200);
   this.btnPay.Size = new System.Drawing.Size(180,38);
   this.btnPay.TabIndex = 11;
   this.btnPay.Text = "Ghi thanh toán";
   this.btnPay.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnPay);
   this.btnReload.Name = "btnReload";
   this.btnReload.Location = new System.Drawing.Point(220,200);
   this.btnReload.Size = new System.Drawing.Size(150,38);
   this.btnReload.TabIndex = 12;
   this.btnReload.Text = "Tải lại";
   this.btnReload.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnReload);
   this.btnClose.Name = "btnClose";
   this.btnClose.Location = new System.Drawing.Point(955,200);
   this.btnClose.Size = new System.Drawing.Size(150,38);
   this.btnClose.TabIndex = 13;
   this.btnClose.Text = "Đóng";
   this.btnClose.UseVisualStyleBackColor = true;
   this.Controls.Add(this.btnClose);
   this.lblDoan.Name = "lblDoan";
   this.lblDoan.Location = new System.Drawing.Point(25,245);
   this.lblDoan.Size = new System.Drawing.Size(1080,28);
   this.lblDoan.TabIndex = 14;
   this.lblDoan.Text = "Chọn đoàn còn nợ đã kết thúc tour";
   this.Controls.Add(this.lblDoan);
   this.dgv.Name = "dgv";
   this.dgv.Location = new System.Drawing.Point(25,280);
   this.dgv.Size = new System.Drawing.Size(1080,220);
   this.dgv.TabIndex = 15;
   this.dgv.ReadOnly = true;
   this.dgv.AllowUserToAddRows = false;
   this.dgv.AllowUserToDeleteRows = false;
   this.dgv.MultiSelect = false;
   this.dgv.RowHeadersVisible = false;
   this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
   this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
   this.dgv.BackgroundColor = System.Drawing.Color.White;
   this.dgv.EnableHeadersVisualStyles = false;
   this.dgv.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(232,239,244);
   this.dgv.ColumnHeadersHeight = 32;
   this.dgv.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(248,250,252);
   this.Controls.Add(this.dgv);
   this.lblTT.Name = "lblTT";
   this.lblTT.Location = new System.Drawing.Point(25,515);
   this.lblTT.Size = new System.Drawing.Size(1080,28);
   this.lblTT.TabIndex = 16;
   this.lblTT.Text = "Lịch sử các lần thanh toán sau tour";
   this.Controls.Add(this.lblTT);
   this.dgvTT.Name = "dgvTT";
   this.dgvTT.Location = new System.Drawing.Point(25,550);
   this.dgvTT.Size = new System.Drawing.Size(1080,210);
   this.dgvTT.TabIndex = 17;
   this.dgvTT.ReadOnly = true;
   this.dgvTT.AllowUserToAddRows = false;
   this.dgvTT.AllowUserToDeleteRows = false;
   this.dgvTT.MultiSelect = false;
   this.dgvTT.RowHeadersVisible = false;
   this.dgvTT.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
   this.dgvTT.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.DisplayedCells;
   this.dgvTT.BackgroundColor = System.Drawing.Color.White;
   this.dgvTT.EnableHeadersVisualStyles = false;
   this.dgvTT.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(232,239,244);
   this.dgvTT.ColumnHeadersHeight = 32;
   this.dgvTT.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(248,250,252);
   this.Controls.Add(this.dgvTT);
   this.AutoScaleDimensions = new System.Drawing.SizeF(7F,15F);
   this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
   this.ClientSize = new System.Drawing.Size(1140,790);
   this.Font = new System.Drawing.Font("Segoe UI",9F);
   this.BackColor = System.Drawing.Color.FromArgb(248,250,252);
   this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
   this.Text = "LAB5 - THANH TOÁN KINH PHÍ ĐOÀN SAU TOUR";
   this.Name = "FrmThanhToanDoan";
   this.Load += new System.EventHandler(this.FrmThanhToanDoan_Load);
   this.ResumeLayout(false);
   this.PerformLayout();
  }
  private System.Windows.Forms.Label lblTitle;
  private System.Windows.Forms.Label lbl1;
  private System.Windows.Forms.TextBox txtMa;
  private System.Windows.Forms.Label lbl3;
  private System.Windows.Forms.TextBox txtSo;
  private System.Windows.Forms.Label lbl5;
  private System.Windows.Forms.DateTimePicker dtNgay;
  private System.Windows.Forms.Label lbl7;
  private System.Windows.Forms.NumericUpDown numTien;
  private System.Windows.Forms.Label lbl9;
  private System.Windows.Forms.TextBox txtNote;
  private System.Windows.Forms.Button btnPay;
  private System.Windows.Forms.Button btnReload;
  private System.Windows.Forms.Button btnClose;
  private System.Windows.Forms.Label lblDoan;
  private System.Windows.Forms.DataGridView dgv;
  private System.Windows.Forms.Label lblTT;
  private System.Windows.Forms.DataGridView dgvTT;
 }
}