namespace QuanLyDuLich.Forms {
 partial class FrmTour {
 private System.ComponentModel.IContainer components=null;
 protected override void Dispose(bool disposing){if(disposing && components!=null)components.Dispose();base.Dispose(disposing);}
 private void InitializeComponent(){
  this.label0=new System.Windows.Forms.Label();
  this.cboTour=new System.Windows.Forms.ComboBox();
  this.tabs=new System.Windows.Forms.TabControl();
  this.tabTour=new System.Windows.Forms.TabPage();
  this.tabDD=new System.Windows.Forms.TabPage();
  this.tabPT=new System.Windows.Forms.TabPage();
  this.tabTQ=new System.Windows.Forms.TabPage();
  this.dgvTour=new System.Windows.Forms.DataGridView();
  this.label8=new System.Windows.Forms.Label();
  this.txtMa=new System.Windows.Forms.TextBox();
  this.label10=new System.Windows.Forms.Label();
  this.txtTen=new System.Windows.Forms.TextBox();
  this.label12=new System.Windows.Forms.Label();
  this.numNgay=new System.Windows.Forms.NumericUpDown();
  this.label14=new System.Windows.Forms.Label();
  this.numDem=new System.Windows.Forms.NumericUpDown();
  this.label16=new System.Windows.Forms.Label();
  this.numGia=new System.Windows.Forms.NumericUpDown();
  this.label18=new System.Windows.Forms.Label();
  this.txtMoTa=new System.Windows.Forms.TextBox();
  this.btnThemTour=new System.Windows.Forms.Button();
  this.label21=new System.Windows.Forms.Label();
  this.dgvDD=new System.Windows.Forms.DataGridView();
  this.label23=new System.Windows.Forms.Label();
  this.numDD=new System.Windows.Forms.NumericUpDown();
  this.label25=new System.Windows.Forms.Label();
  this.txtDD=new System.Windows.Forms.TextBox();
  this.chkDoi=new System.Windows.Forms.CheckBox();
  this.chkAn=new System.Windows.Forms.CheckBox();
  this.chkKS=new System.Windows.Forms.CheckBox();
  this.label30=new System.Windows.Forms.Label();
  this.numSao=new System.Windows.Forms.NumericUpDown();
  this.label32=new System.Windows.Forms.Label();
  this.txtDDNote=new System.Windows.Forms.TextBox();
  this.btnThemDD=new System.Windows.Forms.Button();
  this.dgvPT=new System.Windows.Forms.DataGridView();
  this.label36=new System.Windows.Forms.Label();
  this.numChang=new System.Windows.Forms.NumericUpDown();
  this.label38=new System.Windows.Forms.Label();
  this.cboPT=new System.Windows.Forms.ComboBox();
  this.label40=new System.Windows.Forms.Label();
  this.txtPTNote=new System.Windows.Forms.TextBox();
  this.btnGanPT=new System.Windows.Forms.Button();
  this.label43=new System.Windows.Forms.Label();
  this.dgvTQ=new System.Windows.Forms.DataGridView();
  this.label45=new System.Windows.Forms.Label();
  this.numTQ=new System.Windows.Forms.NumericUpDown();
  this.label47=new System.Windows.Forms.Label();
  this.cboTQ=new System.Windows.Forms.ComboBox();
  this.btnGanTQ=new System.Windows.Forms.Button();
  this.btnDong=new System.Windows.Forms.Button();
  this.SuspendLayout();
  this.label0.Name="label0";
  this.label0.Location=new System.Drawing.Point(20,23);
  this.label0.Size=new System.Drawing.Size(285,25);
  this.label0.TabIndex=0;
  this.label0.Text="Tour đang chọn (cho các tab hành trình):";
  this.Controls.Add(this.label0);
  this.cboTour.Name="cboTour";
  this.cboTour.Location=new System.Drawing.Point(305,20);
  this.cboTour.Size=new System.Drawing.Size(350,25);
  this.cboTour.TabIndex=1;
  this.cboTour.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.Controls.Add(this.cboTour);
  this.tabs.Name="tabs";
  this.tabs.Location=new System.Drawing.Point(20,60);
  this.tabs.Size=new System.Drawing.Size(1000,545);
  this.tabs.TabIndex=2;
  this.Controls.Add(this.tabs);
  this.tabTour.Name="tabTour";
  this.tabTour.Location=new System.Drawing.Point(0,0);
  this.tabTour.Size=new System.Drawing.Size(990,520);
  this.tabTour.TabIndex=3;
  this.tabTour.Text="Tour";
  this.tabTour.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabTour);
  this.tabDD.Name="tabDD";
  this.tabDD.Location=new System.Drawing.Point(0,0);
  this.tabDD.Size=new System.Drawing.Size(990,520);
  this.tabDD.TabIndex=4;
  this.tabDD.Text="Điểm dừng";
  this.tabDD.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabDD);
  this.tabPT.Name="tabPT";
  this.tabPT.Location=new System.Drawing.Point(0,0);
  this.tabPT.Size=new System.Drawing.Size(990,520);
  this.tabPT.TabIndex=5;
  this.tabPT.Text="Phương tiện theo chặng";
  this.tabPT.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabPT);
  this.tabTQ.Name="tabTQ";
  this.tabTQ.Location=new System.Drawing.Point(0,0);
  this.tabTQ.Size=new System.Drawing.Size(990,520);
  this.tabTQ.TabIndex=6;
  this.tabTQ.Text="Điểm tham quan";
  this.tabTQ.BackColor = System.Drawing.Color.White;
  this.tabs.Controls.Add(this.tabTQ);
  this.dgvTour.Name="dgvTour";
  this.dgvTour.Location=new System.Drawing.Point(12,15);
  this.dgvTour.Size=new System.Drawing.Size(965,290);
  this.dgvTour.TabIndex=7;
  this.dgvTour.ReadOnly = true;
  this.dgvTour.AllowUserToAddRows = false;
  this.dgvTour.AllowUserToDeleteRows = false;
  this.dgvTour.MultiSelect = false;
  this.dgvTour.RowHeadersVisible = true;
  this.dgvTour.RowHeadersWidth = 28;
  this.dgvTour.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvTour.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvTour.BackgroundColor = System.Drawing.Color.White;
  this.dgvTour.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvTour.EnableHeadersVisualStyles = false;
  this.dgvTour.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvTour.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvTour.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvTour.ColumnHeadersHeight = 26;
  this.tabTour.Controls.Add(this.dgvTour);
  this.label8.Name="label8";
  this.label8.Location=new System.Drawing.Point(15,330);
  this.label8.Size=new System.Drawing.Size(90,25);
  this.label8.TabIndex=8;
  this.label8.Text="Mã tour:";
  this.tabTour.Controls.Add(this.label8);
  this.txtMa.Name="txtMa";
  this.txtMa.Location=new System.Drawing.Point(105,327);
  this.txtMa.Size=new System.Drawing.Size(150,25);
  this.txtMa.TabIndex=9;
  this.txtMa.MaxLength = 1500;
  this.tabTour.Controls.Add(this.txtMa);
  this.label10.Name="label10";
  this.label10.Location=new System.Drawing.Point(320,330);
  this.label10.Size=new System.Drawing.Size(90,25);
  this.label10.TabIndex=10;
  this.label10.Text="Tên tour:";
  this.tabTour.Controls.Add(this.label10);
  this.txtTen.Name="txtTen";
  this.txtTen.Location=new System.Drawing.Point(410,327);
  this.txtTen.Size=new System.Drawing.Size(480,25);
  this.txtTen.TabIndex=11;
  this.txtTen.MaxLength = 1500;
  this.tabTour.Controls.Add(this.txtTen);
  this.label12.Name="label12";
  this.label12.Location=new System.Drawing.Point(15,368);
  this.label12.Size=new System.Drawing.Size(90,25);
  this.label12.TabIndex=12;
  this.label12.Text="Số ngày:";
  this.tabTour.Controls.Add(this.label12);
  this.numNgay.Name="numNgay";
  this.numNgay.Location=new System.Drawing.Point(105,365);
  this.numNgay.Size=new System.Drawing.Size(95,25);
  this.numNgay.TabIndex=13;
  this.numNgay.Minimum = 1M;
  this.numNgay.Maximum = 365M;
  this.numNgay.Value = 3M;
  this.numNgay.ThousandsSeparator = true;
  this.tabTour.Controls.Add(this.numNgay);
  this.label14.Name="label14";
  this.label14.Location=new System.Drawing.Point(260,368);
  this.label14.Size=new System.Drawing.Size(90,25);
  this.label14.TabIndex=14;
  this.label14.Text="Số đêm:";
  this.tabTour.Controls.Add(this.label14);
  this.numDem.Name="numDem";
  this.numDem.Location=new System.Drawing.Point(350,365);
  this.numDem.Size=new System.Drawing.Size(95,25);
  this.numDem.TabIndex=15;
  this.numDem.Minimum = 0M;
  this.numDem.Maximum = 365M;
  this.numDem.Value = 2M;
  this.numDem.ThousandsSeparator = true;
  this.tabTour.Controls.Add(this.numDem);
  this.label16.Name="label16";
  this.label16.Location=new System.Drawing.Point(505,368);
  this.label16.Size=new System.Drawing.Size(140,25);
  this.label16.TabIndex=16;
  this.label16.Text="Đơn giá / khách:";
  this.tabTour.Controls.Add(this.label16);
  this.numGia.Name="numGia";
  this.numGia.Location=new System.Drawing.Point(645,365);
  this.numGia.Size=new System.Drawing.Size(180,25);
  this.numGia.TabIndex=17;
  this.numGia.Minimum = 0M;
  this.numGia.Maximum = 999999999999M;
  this.numGia.Value = 5500000M;
  this.numGia.ThousandsSeparator = true;
  this.tabTour.Controls.Add(this.numGia);
  this.label18.Name="label18";
  this.label18.Location=new System.Drawing.Point(15,408);
  this.label18.Size=new System.Drawing.Size(90,25);
  this.label18.TabIndex=18;
  this.label18.Text="Mô tả:";
  this.tabTour.Controls.Add(this.label18);
  this.txtMoTa.Name="txtMoTa";
  this.txtMoTa.Location=new System.Drawing.Point(105,405);
  this.txtMoTa.Size=new System.Drawing.Size(660,25);
  this.txtMoTa.TabIndex=19;
  this.txtMoTa.MaxLength = 1500;
  this.tabTour.Controls.Add(this.txtMoTa);
  this.btnThemTour.Name="btnThemTour";
  this.btnThemTour.Location=new System.Drawing.Point(830,405);
  this.btnThemTour.Size=new System.Drawing.Size(140,34);
  this.btnThemTour.TabIndex=20;
  this.btnThemTour.Text="Thêm tour";
  this.btnThemTour.UseVisualStyleBackColor = false;
  this.btnThemTour.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnThemTour.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnThemTour.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabTour.Controls.Add(this.btnThemTour);
  this.label21.Name="label21";
  this.label21.Location=new System.Drawing.Point(15,460);
  this.label21.Size=new System.Drawing.Size(930,25);
  this.label21.TabIndex=21;
  this.label21.Text="Chọn tour trong bảng, nhấn chuột phải để mở / ngừng bán hoặc xóa tour chưa sử dụng.";
  this.tabTour.Controls.Add(this.label21);
  this.dgvDD.Name="dgvDD";
  this.dgvDD.Location=new System.Drawing.Point(12,15);
  this.dgvDD.Size=new System.Drawing.Size(965,310);
  this.dgvDD.TabIndex=22;
  this.dgvDD.ReadOnly = true;
  this.dgvDD.AllowUserToAddRows = false;
  this.dgvDD.AllowUserToDeleteRows = false;
  this.dgvDD.MultiSelect = false;
  this.dgvDD.RowHeadersVisible = true;
  this.dgvDD.RowHeadersWidth = 28;
  this.dgvDD.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvDD.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvDD.BackgroundColor = System.Drawing.Color.White;
  this.dgvDD.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvDD.EnableHeadersVisualStyles = false;
  this.dgvDD.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvDD.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvDD.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvDD.ColumnHeadersHeight = 26;
  this.tabDD.Controls.Add(this.dgvDD);
  this.label23.Name="label23";
  this.label23.Location=new System.Drawing.Point(15,348);
  this.label23.Size=new System.Drawing.Size(80,25);
  this.label23.TabIndex=23;
  this.label23.Text="Thứ tự:";
  this.tabDD.Controls.Add(this.label23);
  this.numDD.Name="numDD";
  this.numDD.Location=new System.Drawing.Point(95,345);
  this.numDD.Size=new System.Drawing.Size(95,25);
  this.numDD.TabIndex=24;
  this.numDD.Minimum = 1M;
  this.numDD.Maximum = 500M;
  this.numDD.Value = 1M;
  this.numDD.ThousandsSeparator = true;
  this.tabDD.Controls.Add(this.numDD);
  this.label25.Name="label25";
  this.label25.Location=new System.Drawing.Point(260,348);
  this.label25.Size=new System.Drawing.Size(140,25);
  this.label25.TabIndex=25;
  this.label25.Text="Tên điểm dừng:";
  this.tabDD.Controls.Add(this.label25);
  this.txtDD.Name="txtDD";
  this.txtDD.Location=new System.Drawing.Point(400,345);
  this.txtDD.Size=new System.Drawing.Size(330,25);
  this.txtDD.TabIndex=26;
  this.txtDD.MaxLength = 1500;
  this.tabDD.Controls.Add(this.txtDD);
  this.chkDoi.Name="chkDoi";
  this.chkDoi.Location=new System.Drawing.Point(15,385);
  this.chkDoi.Size=new System.Drawing.Size(175,25);
  this.chkDoi.TabIndex=27;
  this.chkDoi.Text="Đổi phương tiện";
  this.chkDoi.Checked = false;
  this.tabDD.Controls.Add(this.chkDoi);
  this.chkAn.Name="chkAn";
  this.chkAn.Location=new System.Drawing.Point(210,385);
  this.chkAn.Size=new System.Drawing.Size(175,25);
  this.chkAn.TabIndex=28;
  this.chkAn.Text="Có nơi ăn";
  this.chkAn.Checked = false;
  this.tabDD.Controls.Add(this.chkAn);
  this.chkKS.Name="chkKS";
  this.chkKS.Location=new System.Drawing.Point(395,385);
  this.chkKS.Size=new System.Drawing.Size(175,25);
  this.chkKS.TabIndex=29;
  this.chkKS.Text="Có khách sạn";
  this.chkKS.Checked = false;
  this.tabDD.Controls.Add(this.chkKS);
  this.label30.Name="label30";
  this.label30.Location=new System.Drawing.Point(615,388);
  this.label30.Size=new System.Drawing.Size(85,25);
  this.label30.TabIndex=30;
  this.label30.Text="Hạng sao:";
  this.tabDD.Controls.Add(this.label30);
  this.numSao.Name="numSao";
  this.numSao.Location=new System.Drawing.Point(700,385);
  this.numSao.Size=new System.Drawing.Size(95,25);
  this.numSao.TabIndex=31;
  this.numSao.Minimum = 2M;
  this.numSao.Maximum = 5M;
  this.numSao.Value = 3M;
  this.numSao.ThousandsSeparator = true;
  this.tabDD.Controls.Add(this.numSao);
  this.label32.Name="label32";
  this.label32.Location=new System.Drawing.Point(15,428);
  this.label32.Size=new System.Drawing.Size(80,25);
  this.label32.TabIndex=32;
  this.label32.Text="Ghi chú:";
  this.tabDD.Controls.Add(this.label32);
  this.txtDDNote.Name="txtDDNote";
  this.txtDDNote.Location=new System.Drawing.Point(95,425);
  this.txtDDNote.Size=new System.Drawing.Size(660,25);
  this.txtDDNote.TabIndex=33;
  this.txtDDNote.MaxLength = 1500;
  this.tabDD.Controls.Add(this.txtDDNote);
  this.btnThemDD.Name="btnThemDD";
  this.btnThemDD.Location=new System.Drawing.Point(830,425);
  this.btnThemDD.Size=new System.Drawing.Size(140,34);
  this.btnThemDD.TabIndex=34;
  this.btnThemDD.Text="Thêm điểm dừng";
  this.btnThemDD.UseVisualStyleBackColor = false;
  this.btnThemDD.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnThemDD.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnThemDD.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabDD.Controls.Add(this.btnThemDD);
  this.dgvPT.Name="dgvPT";
  this.dgvPT.Location=new System.Drawing.Point(12,15);
  this.dgvPT.Size=new System.Drawing.Size(965,310);
  this.dgvPT.TabIndex=35;
  this.dgvPT.ReadOnly = true;
  this.dgvPT.AllowUserToAddRows = false;
  this.dgvPT.AllowUserToDeleteRows = false;
  this.dgvPT.MultiSelect = false;
  this.dgvPT.RowHeadersVisible = true;
  this.dgvPT.RowHeadersWidth = 28;
  this.dgvPT.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvPT.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvPT.BackgroundColor = System.Drawing.Color.White;
  this.dgvPT.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvPT.EnableHeadersVisualStyles = false;
  this.dgvPT.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvPT.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvPT.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvPT.ColumnHeadersHeight = 26;
  this.tabPT.Controls.Add(this.dgvPT);
  this.label36.Name="label36";
  this.label36.Location=new System.Drawing.Point(15,348);
  this.label36.Size=new System.Drawing.Size(90,25);
  this.label36.TabIndex=36;
  this.label36.Text="Chặng thứ:";
  this.tabPT.Controls.Add(this.label36);
  this.numChang.Name="numChang";
  this.numChang.Location=new System.Drawing.Point(105,345);
  this.numChang.Size=new System.Drawing.Size(95,25);
  this.numChang.TabIndex=37;
  this.numChang.Minimum = 1M;
  this.numChang.Maximum = 500M;
  this.numChang.Value = 1M;
  this.numChang.ThousandsSeparator = true;
  this.tabPT.Controls.Add(this.numChang);
  this.label38.Name="label38";
  this.label38.Location=new System.Drawing.Point(260,348);
  this.label38.Size=new System.Drawing.Size(125,25);
  this.label38.TabIndex=38;
  this.label38.Text="Phương tiện:";
  this.tabPT.Controls.Add(this.label38);
  this.cboPT.Name="cboPT";
  this.cboPT.Location=new System.Drawing.Point(385,345);
  this.cboPT.Size=new System.Drawing.Size(320,25);
  this.cboPT.TabIndex=39;
  this.cboPT.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.tabPT.Controls.Add(this.cboPT);
  this.label40.Name="label40";
  this.label40.Location=new System.Drawing.Point(15,388);
  this.label40.Size=new System.Drawing.Size(90,25);
  this.label40.TabIndex=40;
  this.label40.Text="Ghi chú:";
  this.tabPT.Controls.Add(this.label40);
  this.txtPTNote.Name="txtPTNote";
  this.txtPTNote.Location=new System.Drawing.Point(105,385);
  this.txtPTNote.Size=new System.Drawing.Size(660,25);
  this.txtPTNote.TabIndex=41;
  this.txtPTNote.MaxLength = 1500;
  this.tabPT.Controls.Add(this.txtPTNote);
  this.btnGanPT.Name="btnGanPT";
  this.btnGanPT.Location=new System.Drawing.Point(830,385);
  this.btnGanPT.Size=new System.Drawing.Size(140,34);
  this.btnGanPT.TabIndex=42;
  this.btnGanPT.Text="Gán phương tiện";
  this.btnGanPT.UseVisualStyleBackColor = false;
  this.btnGanPT.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnGanPT.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnGanPT.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabPT.Controls.Add(this.btnGanPT);
  this.label43.Name="label43";
  this.label43.Location=new System.Drawing.Point(15,435);
  this.label43.Size=new System.Drawing.Size(930,25);
  this.label43.TabIndex=43;
  this.label43.Text="Chặng k là đoạn đi tới điểm dừng thứ k+1; một chặng có thể dùng nhiều phương tiện.";
  this.tabPT.Controls.Add(this.label43);
  this.dgvTQ.Name="dgvTQ";
  this.dgvTQ.Location=new System.Drawing.Point(12,15);
  this.dgvTQ.Size=new System.Drawing.Size(965,310);
  this.dgvTQ.TabIndex=44;
  this.dgvTQ.ReadOnly = true;
  this.dgvTQ.AllowUserToAddRows = false;
  this.dgvTQ.AllowUserToDeleteRows = false;
  this.dgvTQ.MultiSelect = false;
  this.dgvTQ.RowHeadersVisible = true;
  this.dgvTQ.RowHeadersWidth = 28;
  this.dgvTQ.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
  this.dgvTQ.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
  this.dgvTQ.BackgroundColor = System.Drawing.Color.White;
  this.dgvTQ.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
  this.dgvTQ.EnableHeadersVisualStyles = false;
  this.dgvTQ.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(239,239,239);
  this.dgvTQ.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(204,232,255);
  this.dgvTQ.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.Black;
  this.dgvTQ.ColumnHeadersHeight = 26;
  this.tabTQ.Controls.Add(this.dgvTQ);
  this.label45.Name="label45";
  this.label45.Location=new System.Drawing.Point(15,348);
  this.label45.Size=new System.Drawing.Size(90,25);
  this.label45.TabIndex=45;
  this.label45.Text="Thứ tự:";
  this.tabTQ.Controls.Add(this.label45);
  this.numTQ.Name="numTQ";
  this.numTQ.Location=new System.Drawing.Point(105,345);
  this.numTQ.Size=new System.Drawing.Size(95,25);
  this.numTQ.TabIndex=46;
  this.numTQ.Minimum = 1M;
  this.numTQ.Maximum = 500M;
  this.numTQ.Value = 1M;
  this.numTQ.ThousandsSeparator = true;
  this.tabTQ.Controls.Add(this.numTQ);
  this.label47.Name="label47";
  this.label47.Location=new System.Drawing.Point(260,348);
  this.label47.Size=new System.Drawing.Size(145,25);
  this.label47.TabIndex=47;
  this.label47.Text="Điểm tham quan:";
  this.tabTQ.Controls.Add(this.label47);
  this.cboTQ.Name="cboTQ";
  this.cboTQ.Location=new System.Drawing.Point(405,345);
  this.cboTQ.Size=new System.Drawing.Size(410,25);
  this.cboTQ.TabIndex=48;
  this.cboTQ.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
  this.tabTQ.Controls.Add(this.cboTQ);
  this.btnGanTQ.Name="btnGanTQ";
  this.btnGanTQ.Location=new System.Drawing.Point(800,395);
  this.btnGanTQ.Size=new System.Drawing.Size(175,34);
  this.btnGanTQ.TabIndex=49;
  this.btnGanTQ.Text="Gán điểm tham quan";
  this.btnGanTQ.UseVisualStyleBackColor = false;
  this.btnGanTQ.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnGanTQ.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnGanTQ.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.tabTQ.Controls.Add(this.btnGanTQ);
  this.btnDong.Name="btnDong";
  this.btnDong.Location=new System.Drawing.Point(910,620);
  this.btnDong.Size=new System.Drawing.Size(110,32);
  this.btnDong.TabIndex=50;
  this.btnDong.Text="Đóng";
  this.btnDong.UseVisualStyleBackColor = false;
  this.btnDong.BackColor = System.Drawing.Color.FromArgb(224,224,224);
  this.btnDong.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
  this.btnDong.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(195,195,195);
  this.Controls.Add(this.btnDong);
  this.AutoScaleDimensions=new System.Drawing.SizeF(7F,15F);
  this.AutoScaleMode=System.Windows.Forms.AutoScaleMode.Font;
  this.ClientSize=new System.Drawing.Size(1040,660);
  this.Font=new System.Drawing.Font("Segoe UI",9F);
  this.BackColor=System.Drawing.Color.FromArgb(240,240,240);
  this.StartPosition=System.Windows.Forms.FormStartPosition.CenterParent;
  this.Name="FrmTour";
  this.Text="Tour - hành trình";
  this.Load+=new System.EventHandler(this.FrmTour_Load);
  this.ResumeLayout(false);
  this.PerformLayout();
 }
 private System.Windows.Forms.Label label0;
 private System.Windows.Forms.ComboBox cboTour;
 private System.Windows.Forms.TabControl tabs;
 private System.Windows.Forms.TabPage tabTour;
 private System.Windows.Forms.TabPage tabDD;
 private System.Windows.Forms.TabPage tabPT;
 private System.Windows.Forms.TabPage tabTQ;
 private System.Windows.Forms.DataGridView dgvTour;
 private System.Windows.Forms.Label label8;
 private System.Windows.Forms.TextBox txtMa;
 private System.Windows.Forms.Label label10;
 private System.Windows.Forms.TextBox txtTen;
 private System.Windows.Forms.Label label12;
 private System.Windows.Forms.NumericUpDown numNgay;
 private System.Windows.Forms.Label label14;
 private System.Windows.Forms.NumericUpDown numDem;
 private System.Windows.Forms.Label label16;
 private System.Windows.Forms.NumericUpDown numGia;
 private System.Windows.Forms.Label label18;
 private System.Windows.Forms.TextBox txtMoTa;
 private System.Windows.Forms.Button btnThemTour;
 private System.Windows.Forms.Label label21;
 private System.Windows.Forms.DataGridView dgvDD;
 private System.Windows.Forms.Label label23;
 private System.Windows.Forms.NumericUpDown numDD;
 private System.Windows.Forms.Label label25;
 private System.Windows.Forms.TextBox txtDD;
 private System.Windows.Forms.CheckBox chkDoi;
 private System.Windows.Forms.CheckBox chkAn;
 private System.Windows.Forms.CheckBox chkKS;
 private System.Windows.Forms.Label label30;
 private System.Windows.Forms.NumericUpDown numSao;
 private System.Windows.Forms.Label label32;
 private System.Windows.Forms.TextBox txtDDNote;
 private System.Windows.Forms.Button btnThemDD;
 private System.Windows.Forms.DataGridView dgvPT;
 private System.Windows.Forms.Label label36;
 private System.Windows.Forms.NumericUpDown numChang;
 private System.Windows.Forms.Label label38;
 private System.Windows.Forms.ComboBox cboPT;
 private System.Windows.Forms.Label label40;
 private System.Windows.Forms.TextBox txtPTNote;
 private System.Windows.Forms.Button btnGanPT;
 private System.Windows.Forms.Label label43;
 private System.Windows.Forms.DataGridView dgvTQ;
 private System.Windows.Forms.Label label45;
 private System.Windows.Forms.NumericUpDown numTQ;
 private System.Windows.Forms.Label label47;
 private System.Windows.Forms.ComboBox cboTQ;
 private System.Windows.Forms.Button btnGanTQ;
 private System.Windows.Forms.Button btnDong;
 }
}