namespace QuanLyKhachSan.Forms
{
    partial class FrmDanhMuc
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabMain = new System.Windows.Forms.TabControl();
            this.tabKhu = new System.Windows.Forms.TabPage();
            this.tabNV = new System.Windows.Forms.TabPage();
            this.tabLoai = new System.Windows.Forms.TabPage();
            this.tabDV = new System.Windows.Forms.TabPage();
            this.tabQD = new System.Windows.Forms.TabPage();
            this.lblField1 = new System.Windows.Forms.Label();
            this.txtKhuMa = new System.Windows.Forms.TextBox();
            this.lblField2 = new System.Windows.Forms.Label();
            this.txtKhuTen = new System.Windows.Forms.TextBox();
            this.btnThemKhu = new System.Windows.Forms.Button();
            this.btnTaiKhu = new System.Windows.Forms.Button();
            this.dgvKhu = new System.Windows.Forms.DataGridView();
            this.lblField3 = new System.Windows.Forms.Label();
            this.txtNVMa = new System.Windows.Forms.TextBox();
            this.lblField4 = new System.Windows.Forms.Label();
            this.txtNVTen = new System.Windows.Forms.TextBox();
            this.lblField5 = new System.Windows.Forms.Label();
            this.txtNVVaiTro = new System.Windows.Forms.TextBox();
            this.lblField6 = new System.Windows.Forms.Label();
            this.txtNVSDT = new System.Windows.Forms.TextBox();
            this.btnThemNV = new System.Windows.Forms.Button();
            this.btnTaiNV = new System.Windows.Forms.Button();
            this.dgvNV = new System.Windows.Forms.DataGridView();
            this.lblField7 = new System.Windows.Forms.Label();
            this.txtLoaiMa = new System.Windows.Forms.TextBox();
            this.lblField8 = new System.Windows.Forms.Label();
            this.txtLoaiTen = new System.Windows.Forms.TextBox();
            this.btnThemLoai = new System.Windows.Forms.Button();
            this.btnTaiLoai = new System.Windows.Forms.Button();
            this.dgvLoai = new System.Windows.Forms.DataGridView();
            this.lblField9 = new System.Windows.Forms.Label();
            this.txtDVMa = new System.Windows.Forms.TextBox();
            this.lblField10 = new System.Windows.Forms.Label();
            this.txtDVTen = new System.Windows.Forms.TextBox();
            this.lblField11 = new System.Windows.Forms.Label();
            this.txtDVDVT = new System.Windows.Forms.TextBox();
            this.lblField12 = new System.Windows.Forms.Label();
            this.numDVGia = new System.Windows.Forms.NumericUpDown();
            this.btnThemDV = new System.Windows.Forms.Button();
            this.btnTaiDV = new System.Windows.Forms.Button();
            this.dgvDV = new System.Windows.Forms.DataGridView();
            this.lblField13 = new System.Windows.Forms.Label();
            this.txtQDMa = new System.Windows.Forms.TextBox();
            this.lblField14 = new System.Windows.Forms.Label();
            this.cboQDLoai = new System.Windows.Forms.ComboBox();
            this.lblField15 = new System.Windows.Forms.Label();
            this.txtQDMucDo = new System.Windows.Forms.TextBox();
            this.lblField16 = new System.Windows.Forms.Label();
            this.numQDTien = new System.Windows.Forms.NumericUpDown();
            this.btnThemQD = new System.Windows.Forms.Button();
            this.btnTaiQD = new System.Windows.Forms.Button();
            this.dgvQD = new System.Windows.Forms.DataGridView();
            this.btnDong = new System.Windows.Forms.Button();
            this.dgvKhu_MaKhuVuc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvKhu_TenKhuVuc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvNV_MaNV = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvNV_HoTen = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvNV_VaiTro = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvNV_SoDienThoai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLoai_MaLoaiTN = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLoai_TenLoaiTN = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDV_MaDV = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDV_TenDV = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDV_DonViTinh = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDV_DonGia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvQD_MaQuyDinh = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvQD_MaLoaiTN = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvQD_MucDoThietHai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvQD_MucDenBu = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tabMain.SuspendLayout();
            this.tabKhu.SuspendLayout();
            this.tabNV.SuspendLayout();
            this.tabLoai.SuspendLayout();
            this.tabDV.SuspendLayout();
            this.tabQD.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhu)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNV)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLoai)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDVGia)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDV)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numQDTien)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvQD)).BeginInit();
            this.SuspendLayout();
            // tabMain
            this.tabMain.Location = new System.Drawing.Point(12, 12);
            this.tabMain.Size = new System.Drawing.Size(1072, 560);
            this.tabMain.Name = "tabMain";
            this.tabMain.TabIndex = 0;
            // tabKhu
            this.tabKhu.Location = new System.Drawing.Point(4, 27);
            this.tabKhu.Size = new System.Drawing.Size(1064, 529);
            this.tabKhu.Name = "tabKhu";
            this.tabKhu.TabIndex = 1;
            this.tabKhu.Text = "Khu vực";
            this.tabKhu.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabKhu.Padding = new System.Windows.Forms.Padding(8);
            // tabNV
            this.tabNV.Location = new System.Drawing.Point(4, 27);
            this.tabNV.Size = new System.Drawing.Size(1064, 529);
            this.tabNV.Name = "tabNV";
            this.tabNV.TabIndex = 2;
            this.tabNV.Text = "Nhân viên";
            this.tabNV.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabNV.Padding = new System.Windows.Forms.Padding(8);
            // tabLoai
            this.tabLoai.Location = new System.Drawing.Point(4, 27);
            this.tabLoai.Size = new System.Drawing.Size(1064, 529);
            this.tabLoai.Name = "tabLoai";
            this.tabLoai.TabIndex = 3;
            this.tabLoai.Text = "Loại tiện nghi";
            this.tabLoai.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabLoai.Padding = new System.Windows.Forms.Padding(8);
            // tabDV
            this.tabDV.Location = new System.Drawing.Point(4, 27);
            this.tabDV.Size = new System.Drawing.Size(1064, 529);
            this.tabDV.Name = "tabDV";
            this.tabDV.TabIndex = 4;
            this.tabDV.Text = "Dịch vụ";
            this.tabDV.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabDV.Padding = new System.Windows.Forms.Padding(8);
            // tabQD
            this.tabQD.Location = new System.Drawing.Point(4, 27);
            this.tabQD.Size = new System.Drawing.Size(1064, 529);
            this.tabQD.Name = "tabQD";
            this.tabQD.TabIndex = 5;
            this.tabQD.Text = "Quy định đền bù";
            this.tabQD.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabQD.Padding = new System.Windows.Forms.Padding(8);
            // lblField1
            this.lblField1.Location = new System.Drawing.Point(15, 23);
            this.lblField1.Size = new System.Drawing.Size(105, 24);
            this.lblField1.Name = "lblField1";
            this.lblField1.TabIndex = 6;
            this.lblField1.Text = "Mã khu vực";
            this.lblField1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtKhuMa
            this.txtKhuMa.Location = new System.Drawing.Point(120, 20);
            this.txtKhuMa.Size = new System.Drawing.Size(300, 28);
            this.txtKhuMa.Name = "txtKhuMa";
            this.txtKhuMa.TabIndex = 7;
            this.txtKhuMa.MaxLength = 120;
            // lblField2
            this.lblField2.Location = new System.Drawing.Point(455, 23);
            this.lblField2.Size = new System.Drawing.Size(105, 24);
            this.lblField2.Name = "lblField2";
            this.lblField2.TabIndex = 8;
            this.lblField2.Text = "Tên khu vực";
            this.lblField2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtKhuTen
            this.txtKhuTen.Location = new System.Drawing.Point(560, 20);
            this.txtKhuTen.Size = new System.Drawing.Size(300, 28);
            this.txtKhuTen.Name = "txtKhuTen";
            this.txtKhuTen.TabIndex = 9;
            this.txtKhuTen.MaxLength = 120;
            // btnThemKhu
            this.btnThemKhu.Location = new System.Drawing.Point(900, 20);
            this.btnThemKhu.Size = new System.Drawing.Size(125, 32);
            this.btnThemKhu.Name = "btnThemKhu";
            this.btnThemKhu.TabIndex = 10;
            this.btnThemKhu.Text = "Thêm";
            this.btnThemKhu.UseVisualStyleBackColor = true;
            // btnTaiKhu
            this.btnTaiKhu.Location = new System.Drawing.Point(900, 62);
            this.btnTaiKhu.Size = new System.Drawing.Size(125, 32);
            this.btnTaiKhu.Name = "btnTaiKhu";
            this.btnTaiKhu.TabIndex = 11;
            this.btnTaiKhu.Text = "Tải lại";
            this.btnTaiKhu.UseVisualStyleBackColor = true;
            // dgvKhu
            this.dgvKhu.Location = new System.Drawing.Point(15, 122);
            this.dgvKhu.Size = new System.Drawing.Size(1010, 380);
            this.dgvKhu.Name = "dgvKhu";
            this.dgvKhu.TabIndex = 12;
            this.dgvKhu.AllowUserToAddRows = false;
            this.dgvKhu.AllowUserToDeleteRows = false;
            this.dgvKhu.AutoGenerateColumns = false;
            this.dgvKhu.ReadOnly = true;
            this.dgvKhu.MultiSelect = false;
            this.dgvKhu.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvKhu.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvKhu.BackgroundColor = System.Drawing.Color.White;
            this.dgvKhu.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvKhu.RowHeadersWidth = 28;
            this.dgvKhu.EnableHeadersVisualStyles = false;
            this.dgvKhu.ColumnHeadersHeight = 30;
            this.dgvKhu.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvKhuHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvKhuHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvKhuHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvKhu.ColumnHeadersDefaultCellStyle = dgvKhuHeader;
            this.dgvKhu.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvKhu_MaKhuVuc, this.dgvKhu_TenKhuVuc });
            // lblField3
            this.lblField3.Location = new System.Drawing.Point(15, 23);
            this.lblField3.Size = new System.Drawing.Size(105, 24);
            this.lblField3.Name = "lblField3";
            this.lblField3.TabIndex = 13;
            this.lblField3.Text = "Mã nhân viên";
            this.lblField3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtNVMa
            this.txtNVMa.Location = new System.Drawing.Point(120, 20);
            this.txtNVMa.Size = new System.Drawing.Size(300, 28);
            this.txtNVMa.Name = "txtNVMa";
            this.txtNVMa.TabIndex = 14;
            this.txtNVMa.MaxLength = 120;
            // lblField4
            this.lblField4.Location = new System.Drawing.Point(455, 23);
            this.lblField4.Size = new System.Drawing.Size(105, 24);
            this.lblField4.Name = "lblField4";
            this.lblField4.TabIndex = 15;
            this.lblField4.Text = "Họ tên";
            this.lblField4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtNVTen
            this.txtNVTen.Location = new System.Drawing.Point(560, 20);
            this.txtNVTen.Size = new System.Drawing.Size(300, 28);
            this.txtNVTen.Name = "txtNVTen";
            this.txtNVTen.TabIndex = 16;
            this.txtNVTen.MaxLength = 120;
            // lblField5
            this.lblField5.Location = new System.Drawing.Point(15, 65);
            this.lblField5.Size = new System.Drawing.Size(105, 24);
            this.lblField5.Name = "lblField5";
            this.lblField5.TabIndex = 17;
            this.lblField5.Text = "Vai trò";
            this.lblField5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtNVVaiTro
            this.txtNVVaiTro.Location = new System.Drawing.Point(120, 62);
            this.txtNVVaiTro.Size = new System.Drawing.Size(300, 28);
            this.txtNVVaiTro.Name = "txtNVVaiTro";
            this.txtNVVaiTro.TabIndex = 18;
            this.txtNVVaiTro.MaxLength = 120;
            // lblField6
            this.lblField6.Location = new System.Drawing.Point(455, 65);
            this.lblField6.Size = new System.Drawing.Size(105, 24);
            this.lblField6.Name = "lblField6";
            this.lblField6.TabIndex = 19;
            this.lblField6.Text = "Điện thoại";
            this.lblField6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtNVSDT
            this.txtNVSDT.Location = new System.Drawing.Point(560, 62);
            this.txtNVSDT.Size = new System.Drawing.Size(300, 28);
            this.txtNVSDT.Name = "txtNVSDT";
            this.txtNVSDT.TabIndex = 20;
            this.txtNVSDT.MaxLength = 120;
            // btnThemNV
            this.btnThemNV.Location = new System.Drawing.Point(900, 20);
            this.btnThemNV.Size = new System.Drawing.Size(125, 32);
            this.btnThemNV.Name = "btnThemNV";
            this.btnThemNV.TabIndex = 21;
            this.btnThemNV.Text = "Thêm";
            this.btnThemNV.UseVisualStyleBackColor = true;
            // btnTaiNV
            this.btnTaiNV.Location = new System.Drawing.Point(900, 62);
            this.btnTaiNV.Size = new System.Drawing.Size(125, 32);
            this.btnTaiNV.Name = "btnTaiNV";
            this.btnTaiNV.TabIndex = 22;
            this.btnTaiNV.Text = "Tải lại";
            this.btnTaiNV.UseVisualStyleBackColor = true;
            // dgvNV
            this.dgvNV.Location = new System.Drawing.Point(15, 122);
            this.dgvNV.Size = new System.Drawing.Size(1010, 380);
            this.dgvNV.Name = "dgvNV";
            this.dgvNV.TabIndex = 23;
            this.dgvNV.AllowUserToAddRows = false;
            this.dgvNV.AllowUserToDeleteRows = false;
            this.dgvNV.AutoGenerateColumns = false;
            this.dgvNV.ReadOnly = true;
            this.dgvNV.MultiSelect = false;
            this.dgvNV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvNV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvNV.BackgroundColor = System.Drawing.Color.White;
            this.dgvNV.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvNV.RowHeadersWidth = 28;
            this.dgvNV.EnableHeadersVisualStyles = false;
            this.dgvNV.ColumnHeadersHeight = 30;
            this.dgvNV.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvNVHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvNVHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvNVHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvNV.ColumnHeadersDefaultCellStyle = dgvNVHeader;
            this.dgvNV.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvNV_MaNV, this.dgvNV_HoTen, this.dgvNV_VaiTro, this.dgvNV_SoDienThoai });
            // lblField7
            this.lblField7.Location = new System.Drawing.Point(15, 23);
            this.lblField7.Size = new System.Drawing.Size(105, 24);
            this.lblField7.Name = "lblField7";
            this.lblField7.TabIndex = 24;
            this.lblField7.Text = "Mã loại";
            this.lblField7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtLoaiMa
            this.txtLoaiMa.Location = new System.Drawing.Point(120, 20);
            this.txtLoaiMa.Size = new System.Drawing.Size(300, 28);
            this.txtLoaiMa.Name = "txtLoaiMa";
            this.txtLoaiMa.TabIndex = 25;
            this.txtLoaiMa.MaxLength = 120;
            // lblField8
            this.lblField8.Location = new System.Drawing.Point(455, 23);
            this.lblField8.Size = new System.Drawing.Size(105, 24);
            this.lblField8.Name = "lblField8";
            this.lblField8.TabIndex = 26;
            this.lblField8.Text = "Tên loại";
            this.lblField8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtLoaiTen
            this.txtLoaiTen.Location = new System.Drawing.Point(560, 20);
            this.txtLoaiTen.Size = new System.Drawing.Size(300, 28);
            this.txtLoaiTen.Name = "txtLoaiTen";
            this.txtLoaiTen.TabIndex = 27;
            this.txtLoaiTen.MaxLength = 120;
            // btnThemLoai
            this.btnThemLoai.Location = new System.Drawing.Point(900, 20);
            this.btnThemLoai.Size = new System.Drawing.Size(125, 32);
            this.btnThemLoai.Name = "btnThemLoai";
            this.btnThemLoai.TabIndex = 28;
            this.btnThemLoai.Text = "Thêm";
            this.btnThemLoai.UseVisualStyleBackColor = true;
            // btnTaiLoai
            this.btnTaiLoai.Location = new System.Drawing.Point(900, 62);
            this.btnTaiLoai.Size = new System.Drawing.Size(125, 32);
            this.btnTaiLoai.Name = "btnTaiLoai";
            this.btnTaiLoai.TabIndex = 29;
            this.btnTaiLoai.Text = "Tải lại";
            this.btnTaiLoai.UseVisualStyleBackColor = true;
            // dgvLoai
            this.dgvLoai.Location = new System.Drawing.Point(15, 122);
            this.dgvLoai.Size = new System.Drawing.Size(1010, 380);
            this.dgvLoai.Name = "dgvLoai";
            this.dgvLoai.TabIndex = 30;
            this.dgvLoai.AllowUserToAddRows = false;
            this.dgvLoai.AllowUserToDeleteRows = false;
            this.dgvLoai.AutoGenerateColumns = false;
            this.dgvLoai.ReadOnly = true;
            this.dgvLoai.MultiSelect = false;
            this.dgvLoai.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvLoai.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvLoai.BackgroundColor = System.Drawing.Color.White;
            this.dgvLoai.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvLoai.RowHeadersWidth = 28;
            this.dgvLoai.EnableHeadersVisualStyles = false;
            this.dgvLoai.ColumnHeadersHeight = 30;
            this.dgvLoai.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvLoaiHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvLoaiHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvLoaiHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvLoai.ColumnHeadersDefaultCellStyle = dgvLoaiHeader;
            this.dgvLoai.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvLoai_MaLoaiTN, this.dgvLoai_TenLoaiTN });
            // lblField9
            this.lblField9.Location = new System.Drawing.Point(15, 23);
            this.lblField9.Size = new System.Drawing.Size(105, 24);
            this.lblField9.Name = "lblField9";
            this.lblField9.TabIndex = 31;
            this.lblField9.Text = "Mã dịch vụ";
            this.lblField9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtDVMa
            this.txtDVMa.Location = new System.Drawing.Point(120, 20);
            this.txtDVMa.Size = new System.Drawing.Size(300, 28);
            this.txtDVMa.Name = "txtDVMa";
            this.txtDVMa.TabIndex = 32;
            this.txtDVMa.MaxLength = 120;
            // lblField10
            this.lblField10.Location = new System.Drawing.Point(455, 23);
            this.lblField10.Size = new System.Drawing.Size(105, 24);
            this.lblField10.Name = "lblField10";
            this.lblField10.TabIndex = 33;
            this.lblField10.Text = "Tên dịch vụ";
            this.lblField10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtDVTen
            this.txtDVTen.Location = new System.Drawing.Point(560, 20);
            this.txtDVTen.Size = new System.Drawing.Size(300, 28);
            this.txtDVTen.Name = "txtDVTen";
            this.txtDVTen.TabIndex = 34;
            this.txtDVTen.MaxLength = 120;
            // lblField11
            this.lblField11.Location = new System.Drawing.Point(15, 65);
            this.lblField11.Size = new System.Drawing.Size(105, 24);
            this.lblField11.Name = "lblField11";
            this.lblField11.TabIndex = 35;
            this.lblField11.Text = "Đơn vị tính";
            this.lblField11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtDVDVT
            this.txtDVDVT.Location = new System.Drawing.Point(120, 62);
            this.txtDVDVT.Size = new System.Drawing.Size(300, 28);
            this.txtDVDVT.Name = "txtDVDVT";
            this.txtDVDVT.TabIndex = 36;
            this.txtDVDVT.MaxLength = 120;
            // lblField12
            this.lblField12.Location = new System.Drawing.Point(455, 65);
            this.lblField12.Size = new System.Drawing.Size(105, 24);
            this.lblField12.Name = "lblField12";
            this.lblField12.TabIndex = 37;
            this.lblField12.Text = "Đơn giá";
            this.lblField12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numDVGia
            this.numDVGia.Location = new System.Drawing.Point(560, 62);
            this.numDVGia.Size = new System.Drawing.Size(300, 28);
            this.numDVGia.Name = "numDVGia";
            this.numDVGia.TabIndex = 38;
            this.numDVGia.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numDVGia.ThousandsSeparator = true;
            // btnThemDV
            this.btnThemDV.Location = new System.Drawing.Point(900, 20);
            this.btnThemDV.Size = new System.Drawing.Size(125, 32);
            this.btnThemDV.Name = "btnThemDV";
            this.btnThemDV.TabIndex = 39;
            this.btnThemDV.Text = "Thêm";
            this.btnThemDV.UseVisualStyleBackColor = true;
            // btnTaiDV
            this.btnTaiDV.Location = new System.Drawing.Point(900, 62);
            this.btnTaiDV.Size = new System.Drawing.Size(125, 32);
            this.btnTaiDV.Name = "btnTaiDV";
            this.btnTaiDV.TabIndex = 40;
            this.btnTaiDV.Text = "Tải lại";
            this.btnTaiDV.UseVisualStyleBackColor = true;
            // dgvDV
            this.dgvDV.Location = new System.Drawing.Point(15, 122);
            this.dgvDV.Size = new System.Drawing.Size(1010, 380);
            this.dgvDV.Name = "dgvDV";
            this.dgvDV.TabIndex = 41;
            this.dgvDV.AllowUserToAddRows = false;
            this.dgvDV.AllowUserToDeleteRows = false;
            this.dgvDV.AutoGenerateColumns = false;
            this.dgvDV.ReadOnly = true;
            this.dgvDV.MultiSelect = false;
            this.dgvDV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDV.BackgroundColor = System.Drawing.Color.White;
            this.dgvDV.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvDV.RowHeadersWidth = 28;
            this.dgvDV.EnableHeadersVisualStyles = false;
            this.dgvDV.ColumnHeadersHeight = 30;
            this.dgvDV.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvDVHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvDVHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvDVHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvDV.ColumnHeadersDefaultCellStyle = dgvDVHeader;
            this.dgvDV.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvDV_MaDV, this.dgvDV_TenDV, this.dgvDV_DonViTinh, this.dgvDV_DonGia });
            // lblField13
            this.lblField13.Location = new System.Drawing.Point(15, 23);
            this.lblField13.Size = new System.Drawing.Size(105, 24);
            this.lblField13.Name = "lblField13";
            this.lblField13.TabIndex = 42;
            this.lblField13.Text = "Mã quy định";
            this.lblField13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtQDMa
            this.txtQDMa.Location = new System.Drawing.Point(120, 20);
            this.txtQDMa.Size = new System.Drawing.Size(300, 28);
            this.txtQDMa.Name = "txtQDMa";
            this.txtQDMa.TabIndex = 43;
            this.txtQDMa.MaxLength = 120;
            // lblField14
            this.lblField14.Location = new System.Drawing.Point(455, 23);
            this.lblField14.Size = new System.Drawing.Size(105, 24);
            this.lblField14.Name = "lblField14";
            this.lblField14.TabIndex = 44;
            this.lblField14.Text = "Loại tiện nghi";
            this.lblField14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboQDLoai
            this.cboQDLoai.Location = new System.Drawing.Point(560, 20);
            this.cboQDLoai.Size = new System.Drawing.Size(300, 28);
            this.cboQDLoai.Name = "cboQDLoai";
            this.cboQDLoai.TabIndex = 45;
            this.cboQDLoai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboQDLoai.FormattingEnabled = true;
            // lblField15
            this.lblField15.Location = new System.Drawing.Point(15, 65);
            this.lblField15.Size = new System.Drawing.Size(105, 24);
            this.lblField15.Name = "lblField15";
            this.lblField15.TabIndex = 46;
            this.lblField15.Text = "Mức độ";
            this.lblField15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtQDMucDo
            this.txtQDMucDo.Location = new System.Drawing.Point(120, 62);
            this.txtQDMucDo.Size = new System.Drawing.Size(300, 28);
            this.txtQDMucDo.Name = "txtQDMucDo";
            this.txtQDMucDo.TabIndex = 47;
            this.txtQDMucDo.MaxLength = 120;
            // lblField16
            this.lblField16.Location = new System.Drawing.Point(455, 65);
            this.lblField16.Size = new System.Drawing.Size(105, 24);
            this.lblField16.Name = "lblField16";
            this.lblField16.TabIndex = 48;
            this.lblField16.Text = "Mức đền bù";
            this.lblField16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numQDTien
            this.numQDTien.Location = new System.Drawing.Point(560, 62);
            this.numQDTien.Size = new System.Drawing.Size(300, 28);
            this.numQDTien.Name = "numQDTien";
            this.numQDTien.TabIndex = 49;
            this.numQDTien.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numQDTien.ThousandsSeparator = true;
            // btnThemQD
            this.btnThemQD.Location = new System.Drawing.Point(900, 20);
            this.btnThemQD.Size = new System.Drawing.Size(125, 32);
            this.btnThemQD.Name = "btnThemQD";
            this.btnThemQD.TabIndex = 50;
            this.btnThemQD.Text = "Thêm";
            this.btnThemQD.UseVisualStyleBackColor = true;
            // btnTaiQD
            this.btnTaiQD.Location = new System.Drawing.Point(900, 62);
            this.btnTaiQD.Size = new System.Drawing.Size(125, 32);
            this.btnTaiQD.Name = "btnTaiQD";
            this.btnTaiQD.TabIndex = 51;
            this.btnTaiQD.Text = "Tải lại";
            this.btnTaiQD.UseVisualStyleBackColor = true;
            // dgvQD
            this.dgvQD.Location = new System.Drawing.Point(15, 122);
            this.dgvQD.Size = new System.Drawing.Size(1010, 380);
            this.dgvQD.Name = "dgvQD";
            this.dgvQD.TabIndex = 52;
            this.dgvQD.AllowUserToAddRows = false;
            this.dgvQD.AllowUserToDeleteRows = false;
            this.dgvQD.AutoGenerateColumns = false;
            this.dgvQD.ReadOnly = true;
            this.dgvQD.MultiSelect = false;
            this.dgvQD.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvQD.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvQD.BackgroundColor = System.Drawing.Color.White;
            this.dgvQD.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvQD.RowHeadersWidth = 28;
            this.dgvQD.EnableHeadersVisualStyles = false;
            this.dgvQD.ColumnHeadersHeight = 30;
            this.dgvQD.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvQDHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvQDHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvQDHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvQD.ColumnHeadersDefaultCellStyle = dgvQDHeader;
            this.dgvQD.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvQD_MaQuyDinh, this.dgvQD_MaLoaiTN, this.dgvQD_MucDoThietHai, this.dgvQD_MucDenBu });
            // btnDong
            this.btnDong.Location = new System.Drawing.Point(948, 584);
            this.btnDong.Size = new System.Drawing.Size(130, 32);
            this.btnDong.Name = "btnDong";
            this.btnDong.TabIndex = 53;
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.dgvKhu_MaKhuVuc.Name = "dgvKhu_MaKhuVuc";
            this.dgvKhu_MaKhuVuc.DataPropertyName = "MaKhuVuc";
            this.dgvKhu_MaKhuVuc.HeaderText = "Mã";
            this.dgvKhu_MaKhuVuc.ReadOnly = true;
            this.dgvKhu_TenKhuVuc.Name = "dgvKhu_TenKhuVuc";
            this.dgvKhu_TenKhuVuc.DataPropertyName = "TenKhuVuc";
            this.dgvKhu_TenKhuVuc.HeaderText = "Tên khu vực";
            this.dgvKhu_TenKhuVuc.ReadOnly = true;
            this.dgvNV_MaNV.Name = "dgvNV_MaNV";
            this.dgvNV_MaNV.DataPropertyName = "MaNV";
            this.dgvNV_MaNV.HeaderText = "Mã";
            this.dgvNV_MaNV.ReadOnly = true;
            this.dgvNV_HoTen.Name = "dgvNV_HoTen";
            this.dgvNV_HoTen.DataPropertyName = "HoTen";
            this.dgvNV_HoTen.HeaderText = "Họ tên";
            this.dgvNV_HoTen.ReadOnly = true;
            this.dgvNV_VaiTro.Name = "dgvNV_VaiTro";
            this.dgvNV_VaiTro.DataPropertyName = "VaiTro";
            this.dgvNV_VaiTro.HeaderText = "Vai trò";
            this.dgvNV_VaiTro.ReadOnly = true;
            this.dgvNV_SoDienThoai.Name = "dgvNV_SoDienThoai";
            this.dgvNV_SoDienThoai.DataPropertyName = "SoDienThoai";
            this.dgvNV_SoDienThoai.HeaderText = "Điện thoại";
            this.dgvNV_SoDienThoai.ReadOnly = true;
            this.dgvLoai_MaLoaiTN.Name = "dgvLoai_MaLoaiTN";
            this.dgvLoai_MaLoaiTN.DataPropertyName = "MaLoaiTN";
            this.dgvLoai_MaLoaiTN.HeaderText = "Mã";
            this.dgvLoai_MaLoaiTN.ReadOnly = true;
            this.dgvLoai_TenLoaiTN.Name = "dgvLoai_TenLoaiTN";
            this.dgvLoai_TenLoaiTN.DataPropertyName = "TenLoaiTN";
            this.dgvLoai_TenLoaiTN.HeaderText = "Tên loại tiện nghi";
            this.dgvLoai_TenLoaiTN.ReadOnly = true;
            this.dgvDV_MaDV.Name = "dgvDV_MaDV";
            this.dgvDV_MaDV.DataPropertyName = "MaDV";
            this.dgvDV_MaDV.HeaderText = "Mã";
            this.dgvDV_MaDV.ReadOnly = true;
            this.dgvDV_TenDV.Name = "dgvDV_TenDV";
            this.dgvDV_TenDV.DataPropertyName = "TenDV";
            this.dgvDV_TenDV.HeaderText = "Tên dịch vụ";
            this.dgvDV_TenDV.ReadOnly = true;
            this.dgvDV_DonViTinh.Name = "dgvDV_DonViTinh";
            this.dgvDV_DonViTinh.DataPropertyName = "DonViTinh";
            this.dgvDV_DonViTinh.HeaderText = "Đơn vị";
            this.dgvDV_DonViTinh.ReadOnly = true;
            this.dgvDV_DonGia.Name = "dgvDV_DonGia";
            this.dgvDV_DonGia.DataPropertyName = "DonGia";
            this.dgvDV_DonGia.HeaderText = "Đơn giá";
            this.dgvDV_DonGia.ReadOnly = true;
            this.dgvQD_MaQuyDinh.Name = "dgvQD_MaQuyDinh";
            this.dgvQD_MaQuyDinh.DataPropertyName = "MaQuyDinh";
            this.dgvQD_MaQuyDinh.HeaderText = "Mã";
            this.dgvQD_MaQuyDinh.ReadOnly = true;
            this.dgvQD_MaLoaiTN.Name = "dgvQD_MaLoaiTN";
            this.dgvQD_MaLoaiTN.DataPropertyName = "MaLoaiTN";
            this.dgvQD_MaLoaiTN.HeaderText = "Loại tiện nghi";
            this.dgvQD_MaLoaiTN.ReadOnly = true;
            this.dgvQD_MucDoThietHai.Name = "dgvQD_MucDoThietHai";
            this.dgvQD_MucDoThietHai.DataPropertyName = "MucDoThietHai";
            this.dgvQD_MucDoThietHai.HeaderText = "Mức độ";
            this.dgvQD_MucDoThietHai.ReadOnly = true;
            this.dgvQD_MucDenBu.Name = "dgvQD_MucDenBu";
            this.dgvQD_MucDenBu.DataPropertyName = "MucDenBu";
            this.dgvQD_MucDenBu.HeaderText = "Mức đền bù";
            this.dgvQD_MucDenBu.ReadOnly = true;
            this.Controls.Add(this.tabMain);
            this.tabMain.Controls.Add(this.tabKhu);
            this.tabMain.Controls.Add(this.tabNV);
            this.tabMain.Controls.Add(this.tabLoai);
            this.tabMain.Controls.Add(this.tabDV);
            this.tabMain.Controls.Add(this.tabQD);
            this.tabKhu.Controls.Add(this.lblField1);
            this.tabKhu.Controls.Add(this.txtKhuMa);
            this.tabKhu.Controls.Add(this.lblField2);
            this.tabKhu.Controls.Add(this.txtKhuTen);
            this.tabKhu.Controls.Add(this.btnThemKhu);
            this.tabKhu.Controls.Add(this.btnTaiKhu);
            this.tabKhu.Controls.Add(this.dgvKhu);
            this.tabNV.Controls.Add(this.lblField3);
            this.tabNV.Controls.Add(this.txtNVMa);
            this.tabNV.Controls.Add(this.lblField4);
            this.tabNV.Controls.Add(this.txtNVTen);
            this.tabNV.Controls.Add(this.lblField5);
            this.tabNV.Controls.Add(this.txtNVVaiTro);
            this.tabNV.Controls.Add(this.lblField6);
            this.tabNV.Controls.Add(this.txtNVSDT);
            this.tabNV.Controls.Add(this.btnThemNV);
            this.tabNV.Controls.Add(this.btnTaiNV);
            this.tabNV.Controls.Add(this.dgvNV);
            this.tabLoai.Controls.Add(this.lblField7);
            this.tabLoai.Controls.Add(this.txtLoaiMa);
            this.tabLoai.Controls.Add(this.lblField8);
            this.tabLoai.Controls.Add(this.txtLoaiTen);
            this.tabLoai.Controls.Add(this.btnThemLoai);
            this.tabLoai.Controls.Add(this.btnTaiLoai);
            this.tabLoai.Controls.Add(this.dgvLoai);
            this.tabDV.Controls.Add(this.lblField9);
            this.tabDV.Controls.Add(this.txtDVMa);
            this.tabDV.Controls.Add(this.lblField10);
            this.tabDV.Controls.Add(this.txtDVTen);
            this.tabDV.Controls.Add(this.lblField11);
            this.tabDV.Controls.Add(this.txtDVDVT);
            this.tabDV.Controls.Add(this.lblField12);
            this.tabDV.Controls.Add(this.numDVGia);
            this.tabDV.Controls.Add(this.btnThemDV);
            this.tabDV.Controls.Add(this.btnTaiDV);
            this.tabDV.Controls.Add(this.dgvDV);
            this.tabQD.Controls.Add(this.lblField13);
            this.tabQD.Controls.Add(this.txtQDMa);
            this.tabQD.Controls.Add(this.lblField14);
            this.tabQD.Controls.Add(this.cboQDLoai);
            this.tabQD.Controls.Add(this.lblField15);
            this.tabQD.Controls.Add(this.txtQDMucDo);
            this.tabQD.Controls.Add(this.lblField16);
            this.tabQD.Controls.Add(this.numQDTien);
            this.tabQD.Controls.Add(this.btnThemQD);
            this.tabQD.Controls.Add(this.btnTaiQD);
            this.tabQD.Controls.Add(this.dgvQD);
            this.Controls.Add(this.btnDong);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 630);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Name = "FrmDanhMuc";
            this.Text = "Danh mục khách sạn";
            this.Load += new System.EventHandler(this.FrmDanhMuc_Load);
            this.tabMain.ResumeLayout(false);
            this.tabMain.PerformLayout();
            this.tabKhu.ResumeLayout(false);
            this.tabKhu.PerformLayout();
            this.tabNV.ResumeLayout(false);
            this.tabNV.PerformLayout();
            this.tabLoai.ResumeLayout(false);
            this.tabLoai.PerformLayout();
            this.tabDV.ResumeLayout(false);
            this.tabDV.PerformLayout();
            this.tabQD.ResumeLayout(false);
            this.tabQD.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhu)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNV)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLoai)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDVGia)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDV)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numQDTien)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvQD)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.TabPage tabKhu;
        private System.Windows.Forms.TabPage tabNV;
        private System.Windows.Forms.TabPage tabLoai;
        private System.Windows.Forms.TabPage tabDV;
        private System.Windows.Forms.TabPage tabQD;
        private System.Windows.Forms.Label lblField1;
        private System.Windows.Forms.TextBox txtKhuMa;
        private System.Windows.Forms.Label lblField2;
        private System.Windows.Forms.TextBox txtKhuTen;
        private System.Windows.Forms.Button btnThemKhu;
        private System.Windows.Forms.Button btnTaiKhu;
        private System.Windows.Forms.DataGridView dgvKhu;
        private System.Windows.Forms.Label lblField3;
        private System.Windows.Forms.TextBox txtNVMa;
        private System.Windows.Forms.Label lblField4;
        private System.Windows.Forms.TextBox txtNVTen;
        private System.Windows.Forms.Label lblField5;
        private System.Windows.Forms.TextBox txtNVVaiTro;
        private System.Windows.Forms.Label lblField6;
        private System.Windows.Forms.TextBox txtNVSDT;
        private System.Windows.Forms.Button btnThemNV;
        private System.Windows.Forms.Button btnTaiNV;
        private System.Windows.Forms.DataGridView dgvNV;
        private System.Windows.Forms.Label lblField7;
        private System.Windows.Forms.TextBox txtLoaiMa;
        private System.Windows.Forms.Label lblField8;
        private System.Windows.Forms.TextBox txtLoaiTen;
        private System.Windows.Forms.Button btnThemLoai;
        private System.Windows.Forms.Button btnTaiLoai;
        private System.Windows.Forms.DataGridView dgvLoai;
        private System.Windows.Forms.Label lblField9;
        private System.Windows.Forms.TextBox txtDVMa;
        private System.Windows.Forms.Label lblField10;
        private System.Windows.Forms.TextBox txtDVTen;
        private System.Windows.Forms.Label lblField11;
        private System.Windows.Forms.TextBox txtDVDVT;
        private System.Windows.Forms.Label lblField12;
        private System.Windows.Forms.NumericUpDown numDVGia;
        private System.Windows.Forms.Button btnThemDV;
        private System.Windows.Forms.Button btnTaiDV;
        private System.Windows.Forms.DataGridView dgvDV;
        private System.Windows.Forms.Label lblField13;
        private System.Windows.Forms.TextBox txtQDMa;
        private System.Windows.Forms.Label lblField14;
        private System.Windows.Forms.ComboBox cboQDLoai;
        private System.Windows.Forms.Label lblField15;
        private System.Windows.Forms.TextBox txtQDMucDo;
        private System.Windows.Forms.Label lblField16;
        private System.Windows.Forms.NumericUpDown numQDTien;
        private System.Windows.Forms.Button btnThemQD;
        private System.Windows.Forms.Button btnTaiQD;
        private System.Windows.Forms.DataGridView dgvQD;
        private System.Windows.Forms.Button btnDong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvKhu_MaKhuVuc;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvKhu_TenKhuVuc;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvNV_MaNV;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvNV_HoTen;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvNV_VaiTro;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvNV_SoDienThoai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLoai_MaLoaiTN;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLoai_TenLoaiTN;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDV_MaDV;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDV_TenDV;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDV_DonViTinh;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDV_DonGia;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvQD_MaQuyDinh;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvQD_MaLoaiTN;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvQD_MucDoThietHai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvQD_MucDenBu;
    }
}
