namespace QuanLyKhachSan.Forms
{
    partial class FrmDatPhong
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabMain = new System.Windows.Forms.TabControl();
            this.tabKhach = new System.Windows.Forms.TabPage();
            this.tabDat = new System.Windows.Forms.TabPage();
            this.tabNhan = new System.Windows.Forms.TabPage();
            this.lblField1 = new System.Windows.Forms.Label();
            this.txtMaKH = new System.Windows.Forms.TextBox();
            this.lblField2 = new System.Windows.Forms.Label();
            this.txtTenKH = new System.Windows.Forms.TextBox();
            this.lblField3 = new System.Windows.Forms.Label();
            this.txtCMND = new System.Windows.Forms.TextBox();
            this.lblField4 = new System.Windows.Forms.Label();
            this.txtQT = new System.Windows.Forms.TextBox();
            this.lblField5 = new System.Windows.Forms.Label();
            this.txtSDT = new System.Windows.Forms.TextBox();
            this.btnThemKhach = new System.Windows.Forms.Button();
            this.btnTaiKhach = new System.Windows.Forms.Button();
            this.dgvKhach = new System.Windows.Forms.DataGridView();
            this.lblField6 = new System.Windows.Forms.Label();
            this.txtSoPhieu = new System.Windows.Forms.TextBox();
            this.lblField7 = new System.Windows.Forms.Label();
            this.cboKhach = new System.Windows.Forms.ComboBox();
            this.lblField8 = new System.Windows.Forms.Label();
            this.cboKenh = new System.Windows.Forms.ComboBox();
            this.lblField9 = new System.Windows.Forms.Label();
            this.numCoc = new System.Windows.Forms.NumericUpDown();
            this.lblField10 = new System.Windows.Forms.Label();
            this.dtNhan = new System.Windows.Forms.DateTimePicker();
            this.lblField11 = new System.Windows.Forms.Label();
            this.dtTra = new System.Windows.Forms.DateTimePicker();
            this.lblField12 = new System.Windows.Forms.Label();
            this.cboNV = new System.Windows.Forms.ComboBox();
            this.lblField13 = new System.Windows.Forms.Label();
            this.numSoNguoi = new System.Windows.Forms.NumericUpDown();
            this.dgvPhong = new System.Windows.Forms.DataGridView();
            this.dgvChon = new System.Windows.Forms.DataGridView();
            this.btnThemPhong = new System.Windows.Forms.Button();
            this.btnBoPhong = new System.Windows.Forms.Button();
            this.btnTaiDat = new System.Windows.Forms.Button();
            this.btnLapPhieu = new System.Windows.Forms.Button();
            this.lblField14 = new System.Windows.Forms.Label();
            this.dgvPhieu = new System.Windows.Forms.DataGridView();
            this.lblField15 = new System.Windows.Forms.Label();
            this.cboPhieuNhan = new System.Windows.Forms.ComboBox();
            this.lblField16 = new System.Windows.Forms.Label();
            this.cboPhongNhan = new System.Windows.Forms.ComboBox();
            this.btnTaiNhan = new System.Windows.Forms.Button();
            this.lblField17 = new System.Windows.Forms.Label();
            this.txtNguoiTen = new System.Windows.Forms.TextBox();
            this.lblField18 = new System.Windows.Forms.Label();
            this.txtNguoiCMND = new System.Windows.Forms.TextBox();
            this.lblField19 = new System.Windows.Forms.Label();
            this.txtNguoiQT = new System.Windows.Forms.TextBox();
            this.btnThemNguoi = new System.Windows.Forms.Button();
            this.btnNhanPhong = new System.Windows.Forms.Button();
            this.btnNoShow = new System.Windows.Forms.Button();
            this.dgvCT = new System.Windows.Forms.DataGridView();
            this.dgvNguoi = new System.Windows.Forms.DataGridView();
            this.btnDong = new System.Windows.Forms.Button();
            this.dgvKhach_MaKhach = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvKhach_HoTen = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvKhach_SoCMND = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvKhach_QuocTich = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvKhach_SoDienThoai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhong_SoPhong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhong_MaKhuVuc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhong_SoNguoiToiDa = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhong_DonGiaNgay = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvChon_SoPhong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvChon_SoNguoi = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvChon_DonGiaNgay = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhieu_SoPhieuDat = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhieu_HoTen = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhieu_NgayNhan = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhieu_NgayTraDuKien = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhieu_TienCoc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhieu_KenhDat = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhieu_TrangThai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvCT_SoPhieuDat = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvCT_SoPhong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvCT_SoNguoi = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvNguoi_SoPhong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvNguoi_HoTen = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvNguoi_SoCMND = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvNguoi_QuocTich = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tabMain.SuspendLayout();
            this.tabKhach.SuspendLayout();
            this.tabDat.SuspendLayout();
            this.tabNhan.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhach)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCoc)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSoNguoi)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvChon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhieu)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCT)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNguoi)).BeginInit();
            this.SuspendLayout();
            // tabMain
            this.tabMain.Location = new System.Drawing.Point(12, 12);
            this.tabMain.Size = new System.Drawing.Size(1136, 710);
            this.tabMain.Name = "tabMain";
            this.tabMain.SelectedIndex = 1;
            this.tabMain.TabIndex = 0;
            // tabKhach
            this.tabKhach.Location = new System.Drawing.Point(4, 27);
            this.tabKhach.Size = new System.Drawing.Size(1128, 679);
            this.tabKhach.Name = "tabKhach";
            this.tabKhach.TabIndex = 1;
            this.tabKhach.Text = "Khách hàng";
            this.tabKhach.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabKhach.Padding = new System.Windows.Forms.Padding(8);
            // tabDat
            this.tabDat.Location = new System.Drawing.Point(4, 27);
            this.tabDat.Size = new System.Drawing.Size(1128, 679);
            this.tabDat.Name = "tabDat";
            this.tabDat.TabIndex = 2;
            this.tabDat.Text = "Đặt phòng";
            this.tabDat.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabDat.Padding = new System.Windows.Forms.Padding(8);
            // tabNhan
            this.tabNhan.Location = new System.Drawing.Point(4, 27);
            this.tabNhan.Size = new System.Drawing.Size(1128, 679);
            this.tabNhan.Name = "tabNhan";
            this.tabNhan.TabIndex = 3;
            this.tabNhan.Text = "Nhận phòng / Người lưu trú";
            this.tabNhan.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabNhan.Padding = new System.Windows.Forms.Padding(8);
            // lblField1
            this.lblField1.Location = new System.Drawing.Point(16, 23);
            this.lblField1.Size = new System.Drawing.Size(95, 24);
            this.lblField1.Name = "lblField1";
            this.lblField1.TabIndex = 4;
            this.lblField1.Text = "Mã khách:";
            this.lblField1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtMaKH
            this.txtMaKH.Location = new System.Drawing.Point(111, 20);
            this.txtMaKH.Size = new System.Drawing.Size(160, 28);
            this.txtMaKH.Name = "txtMaKH";
            this.txtMaKH.TabIndex = 5;
            this.txtMaKH.MaxLength = 120;
            // lblField2
            this.lblField2.Location = new System.Drawing.Point(300, 23);
            this.lblField2.Size = new System.Drawing.Size(65, 24);
            this.lblField2.Name = "lblField2";
            this.lblField2.TabIndex = 6;
            this.lblField2.Text = "Họ tên:";
            this.lblField2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtTenKH
            this.txtTenKH.Location = new System.Drawing.Point(365, 20);
            this.txtTenKH.Size = new System.Drawing.Size(250, 28);
            this.txtTenKH.Name = "txtTenKH";
            this.txtTenKH.TabIndex = 7;
            this.txtTenKH.MaxLength = 120;
            // lblField3
            this.lblField3.Location = new System.Drawing.Point(650, 23);
            this.lblField3.Size = new System.Drawing.Size(65, 24);
            this.lblField3.Name = "lblField3";
            this.lblField3.TabIndex = 8;
            this.lblField3.Text = "CCCD:";
            this.lblField3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtCMND
            this.txtCMND.Location = new System.Drawing.Point(715, 20);
            this.txtCMND.Size = new System.Drawing.Size(240, 28);
            this.txtCMND.Name = "txtCMND";
            this.txtCMND.TabIndex = 9;
            this.txtCMND.MaxLength = 120;
            // lblField4
            this.lblField4.Location = new System.Drawing.Point(16, 68);
            this.lblField4.Size = new System.Drawing.Size(95, 24);
            this.lblField4.Name = "lblField4";
            this.lblField4.TabIndex = 10;
            this.lblField4.Text = "Quốc tịch:";
            this.lblField4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtQT
            this.txtQT.Location = new System.Drawing.Point(111, 65);
            this.txtQT.Size = new System.Drawing.Size(160, 28);
            this.txtQT.Name = "txtQT";
            this.txtQT.TabIndex = 11;
            this.txtQT.MaxLength = 120;
            // lblField5
            this.lblField5.Location = new System.Drawing.Point(300, 68);
            this.lblField5.Size = new System.Drawing.Size(95, 24);
            this.lblField5.Name = "lblField5";
            this.lblField5.TabIndex = 12;
            this.lblField5.Text = "Điện thoại:";
            this.lblField5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtSDT
            this.txtSDT.Location = new System.Drawing.Point(395, 65);
            this.txtSDT.Size = new System.Drawing.Size(250, 28);
            this.txtSDT.Name = "txtSDT";
            this.txtSDT.TabIndex = 13;
            this.txtSDT.MaxLength = 120;
            // btnThemKhach
            this.btnThemKhach.Location = new System.Drawing.Point(800, 65);
            this.btnThemKhach.Size = new System.Drawing.Size(130, 32);
            this.btnThemKhach.Name = "btnThemKhach";
            this.btnThemKhach.TabIndex = 14;
            this.btnThemKhach.Text = "Thêm khách";
            this.btnThemKhach.UseVisualStyleBackColor = true;
            // btnTaiKhach
            this.btnTaiKhach.Location = new System.Drawing.Point(945, 65);
            this.btnTaiKhach.Size = new System.Drawing.Size(130, 32);
            this.btnTaiKhach.Name = "btnTaiKhach";
            this.btnTaiKhach.TabIndex = 15;
            this.btnTaiKhach.Text = "Tải lại";
            this.btnTaiKhach.UseVisualStyleBackColor = true;
            // dgvKhach
            this.dgvKhach.Location = new System.Drawing.Point(16, 125);
            this.dgvKhach.Size = new System.Drawing.Size(1080, 510);
            this.dgvKhach.Name = "dgvKhach";
            this.dgvKhach.TabIndex = 16;
            this.dgvKhach.AllowUserToAddRows = false;
            this.dgvKhach.AllowUserToDeleteRows = false;
            this.dgvKhach.AutoGenerateColumns = false;
            this.dgvKhach.ReadOnly = true;
            this.dgvKhach.MultiSelect = false;
            this.dgvKhach.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvKhach.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvKhach.BackgroundColor = System.Drawing.Color.White;
            this.dgvKhach.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvKhach.RowHeadersWidth = 28;
            this.dgvKhach.EnableHeadersVisualStyles = false;
            this.dgvKhach.ColumnHeadersHeight = 30;
            this.dgvKhach.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvKhachHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvKhachHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvKhachHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvKhach.ColumnHeadersDefaultCellStyle = dgvKhachHeader;
            this.dgvKhach.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvKhach_MaKhach, this.dgvKhach_HoTen, this.dgvKhach_SoCMND, this.dgvKhach_QuocTich, this.dgvKhach_SoDienThoai });
            // lblField6
            this.lblField6.Location = new System.Drawing.Point(12, 20);
            this.lblField6.Size = new System.Drawing.Size(100, 24);
            this.lblField6.Name = "lblField6";
            this.lblField6.TabIndex = 17;
            this.lblField6.Text = "Số phiếu đặt:";
            this.lblField6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtSoPhieu
            this.txtSoPhieu.Location = new System.Drawing.Point(112, 17);
            this.txtSoPhieu.Size = new System.Drawing.Size(150, 28);
            this.txtSoPhieu.Name = "txtSoPhieu";
            this.txtSoPhieu.TabIndex = 18;
            this.txtSoPhieu.MaxLength = 120;
            // lblField7
            this.lblField7.Location = new System.Drawing.Point(280, 20);
            this.lblField7.Size = new System.Drawing.Size(60, 24);
            this.lblField7.Name = "lblField7";
            this.lblField7.TabIndex = 19;
            this.lblField7.Text = "Khách:";
            this.lblField7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboKhach
            this.cboKhach.Location = new System.Drawing.Point(340, 17);
            this.cboKhach.Size = new System.Drawing.Size(220, 28);
            this.cboKhach.Name = "cboKhach";
            this.cboKhach.TabIndex = 20;
            this.cboKhach.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboKhach.FormattingEnabled = true;
            // lblField8
            this.lblField8.Location = new System.Drawing.Point(590, 20);
            this.lblField8.Size = new System.Drawing.Size(75, 24);
            this.lblField8.Name = "lblField8";
            this.lblField8.TabIndex = 21;
            this.lblField8.Text = "Kênh đặt:";
            this.lblField8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboKenh
            this.cboKenh.Location = new System.Drawing.Point(665, 17);
            this.cboKenh.Size = new System.Drawing.Size(150, 28);
            this.cboKenh.Name = "cboKenh";
            this.cboKenh.TabIndex = 22;
            this.cboKenh.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboKenh.FormattingEnabled = true;
            // lblField9
            this.lblField9.Location = new System.Drawing.Point(850, 20);
            this.lblField9.Size = new System.Drawing.Size(75, 24);
            this.lblField9.Name = "lblField9";
            this.lblField9.TabIndex = 23;
            this.lblField9.Text = "Tiền cọc:";
            this.lblField9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numCoc
            this.numCoc.Location = new System.Drawing.Point(925, 17);
            this.numCoc.Size = new System.Drawing.Size(155, 28);
            this.numCoc.Name = "numCoc";
            this.numCoc.TabIndex = 24;
            this.numCoc.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numCoc.ThousandsSeparator = true;
            // lblField10
            this.lblField10.Location = new System.Drawing.Point(12, 63);
            this.lblField10.Size = new System.Drawing.Size(100, 24);
            this.lblField10.Name = "lblField10";
            this.lblField10.TabIndex = 25;
            this.lblField10.Text = "Ngày nhận:";
            this.lblField10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // dtNhan
            this.dtNhan.Location = new System.Drawing.Point(112, 60);
            this.dtNhan.Size = new System.Drawing.Size(150, 28);
            this.dtNhan.Name = "dtNhan";
            this.dtNhan.TabIndex = 26;
            this.dtNhan.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtNhan.CustomFormat = "dd/MM/yyyy";
            // lblField11
            this.lblField11.Location = new System.Drawing.Point(280, 63);
            this.lblField11.Size = new System.Drawing.Size(75, 24);
            this.lblField11.Name = "lblField11";
            this.lblField11.TabIndex = 27;
            this.lblField11.Text = "Ngày trả:";
            this.lblField11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // dtTra
            this.dtTra.Location = new System.Drawing.Point(355, 60);
            this.dtTra.Size = new System.Drawing.Size(155, 28);
            this.dtTra.Name = "dtTra";
            this.dtTra.TabIndex = 28;
            this.dtTra.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtTra.CustomFormat = "dd/MM/yyyy";
            // lblField12
            this.lblField12.Location = new System.Drawing.Point(560, 63);
            this.lblField12.Size = new System.Drawing.Size(65, 24);
            this.lblField12.Name = "lblField12";
            this.lblField12.TabIndex = 29;
            this.lblField12.Text = "Lễ tân:";
            this.lblField12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboNV
            this.cboNV.Location = new System.Drawing.Point(625, 60);
            this.cboNV.Size = new System.Drawing.Size(185, 28);
            this.cboNV.Name = "cboNV";
            this.cboNV.TabIndex = 30;
            this.cboNV.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboNV.FormattingEnabled = true;
            // lblField13
            this.lblField13.Location = new System.Drawing.Point(850, 63);
            this.lblField13.Size = new System.Drawing.Size(75, 24);
            this.lblField13.Name = "lblField13";
            this.lblField13.TabIndex = 31;
            this.lblField13.Text = "Số người:";
            this.lblField13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numSoNguoi
            this.numSoNguoi.Location = new System.Drawing.Point(925, 60);
            this.numSoNguoi.Size = new System.Drawing.Size(155, 28);
            this.numSoNguoi.Name = "numSoNguoi";
            this.numSoNguoi.TabIndex = 32;
            this.numSoNguoi.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numSoNguoi.ThousandsSeparator = true;
            // dgvPhong
            this.dgvPhong.Location = new System.Drawing.Point(16, 115);
            this.dgvPhong.Size = new System.Drawing.Size(520, 205);
            this.dgvPhong.Name = "dgvPhong";
            this.dgvPhong.TabIndex = 33;
            this.dgvPhong.AllowUserToAddRows = false;
            this.dgvPhong.AllowUserToDeleteRows = false;
            this.dgvPhong.AutoGenerateColumns = false;
            this.dgvPhong.ReadOnly = true;
            this.dgvPhong.MultiSelect = false;
            this.dgvPhong.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPhong.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPhong.BackgroundColor = System.Drawing.Color.White;
            this.dgvPhong.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvPhong.RowHeadersWidth = 28;
            this.dgvPhong.EnableHeadersVisualStyles = false;
            this.dgvPhong.ColumnHeadersHeight = 30;
            this.dgvPhong.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvPhongHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvPhongHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvPhongHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvPhong.ColumnHeadersDefaultCellStyle = dgvPhongHeader;
            this.dgvPhong.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvPhong_SoPhong, this.dgvPhong_MaKhuVuc, this.dgvPhong_SoNguoiToiDa, this.dgvPhong_DonGiaNgay });
            // dgvChon
            this.dgvChon.Location = new System.Drawing.Point(564, 115);
            this.dgvChon.Size = new System.Drawing.Size(532, 205);
            this.dgvChon.Name = "dgvChon";
            this.dgvChon.TabIndex = 34;
            this.dgvChon.AllowUserToAddRows = false;
            this.dgvChon.AllowUserToDeleteRows = false;
            this.dgvChon.AutoGenerateColumns = false;
            this.dgvChon.ReadOnly = true;
            this.dgvChon.MultiSelect = false;
            this.dgvChon.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvChon.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvChon.BackgroundColor = System.Drawing.Color.White;
            this.dgvChon.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvChon.RowHeadersWidth = 28;
            this.dgvChon.EnableHeadersVisualStyles = false;
            this.dgvChon.ColumnHeadersHeight = 30;
            this.dgvChon.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvChonHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvChonHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvChonHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvChon.ColumnHeadersDefaultCellStyle = dgvChonHeader;
            this.dgvChon.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvChon_SoPhong, this.dgvChon_SoNguoi, this.dgvChon_DonGiaNgay });
            // btnThemPhong
            this.btnThemPhong.Location = new System.Drawing.Point(370, 331);
            this.btnThemPhong.Size = new System.Drawing.Size(165, 32);
            this.btnThemPhong.Name = "btnThemPhong";
            this.btnThemPhong.TabIndex = 35;
            this.btnThemPhong.Text = "Thêm phòng →";
            this.btnThemPhong.UseVisualStyleBackColor = true;
            // btnBoPhong
            this.btnBoPhong.Location = new System.Drawing.Point(565, 331);
            this.btnBoPhong.Size = new System.Drawing.Size(140, 32);
            this.btnBoPhong.Name = "btnBoPhong";
            this.btnBoPhong.TabIndex = 36;
            this.btnBoPhong.Text = "Bỏ phòng";
            this.btnBoPhong.UseVisualStyleBackColor = true;
            // btnTaiDat
            this.btnTaiDat.Location = new System.Drawing.Point(730, 331);
            this.btnTaiDat.Size = new System.Drawing.Size(165, 32);
            this.btnTaiDat.Name = "btnTaiDat";
            this.btnTaiDat.TabIndex = 37;
            this.btnTaiDat.Text = "Tải khách / phòng";
            this.btnTaiDat.UseVisualStyleBackColor = true;
            // btnLapPhieu
            this.btnLapPhieu.Location = new System.Drawing.Point(926, 331);
            this.btnLapPhieu.Size = new System.Drawing.Size(170, 32);
            this.btnLapPhieu.Name = "btnLapPhieu";
            this.btnLapPhieu.TabIndex = 38;
            this.btnLapPhieu.Text = "Lập phiếu đặt";
            this.btnLapPhieu.UseVisualStyleBackColor = true;
            // lblField14
            this.lblField14.Location = new System.Drawing.Point(16, 378);
            this.lblField14.Size = new System.Drawing.Size(220, 24);
            this.lblField14.Name = "lblField14";
            this.lblField14.TabIndex = 39;
            this.lblField14.Text = "Phiếu đặt phòng:";
            this.lblField14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // dgvPhieu
            this.dgvPhieu.Location = new System.Drawing.Point(16, 410);
            this.dgvPhieu.Size = new System.Drawing.Size(1080, 230);
            this.dgvPhieu.Name = "dgvPhieu";
            this.dgvPhieu.TabIndex = 40;
            this.dgvPhieu.AllowUserToAddRows = false;
            this.dgvPhieu.AllowUserToDeleteRows = false;
            this.dgvPhieu.AutoGenerateColumns = false;
            this.dgvPhieu.ReadOnly = true;
            this.dgvPhieu.MultiSelect = false;
            this.dgvPhieu.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPhieu.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPhieu.BackgroundColor = System.Drawing.Color.White;
            this.dgvPhieu.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvPhieu.RowHeadersWidth = 28;
            this.dgvPhieu.EnableHeadersVisualStyles = false;
            this.dgvPhieu.ColumnHeadersHeight = 30;
            this.dgvPhieu.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvPhieuHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvPhieuHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvPhieuHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvPhieu.ColumnHeadersDefaultCellStyle = dgvPhieuHeader;
            this.dgvPhieu.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvPhieu_SoPhieuDat, this.dgvPhieu_HoTen, this.dgvPhieu_NgayNhan, this.dgvPhieu_NgayTraDuKien, this.dgvPhieu_TienCoc, this.dgvPhieu_KenhDat, this.dgvPhieu_TrangThai });
            // lblField15
            this.lblField15.Location = new System.Drawing.Point(16, 23);
            this.lblField15.Size = new System.Drawing.Size(85, 24);
            this.lblField15.Name = "lblField15";
            this.lblField15.TabIndex = 41;
            this.lblField15.Text = "Phiếu đặt:";
            this.lblField15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboPhieuNhan
            this.cboPhieuNhan.Location = new System.Drawing.Point(101, 20);
            this.cboPhieuNhan.Size = new System.Drawing.Size(260, 28);
            this.cboPhieuNhan.Name = "cboPhieuNhan";
            this.cboPhieuNhan.TabIndex = 42;
            this.cboPhieuNhan.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboPhieuNhan.FormattingEnabled = true;
            // lblField16
            this.lblField16.Location = new System.Drawing.Point(415, 23);
            this.lblField16.Size = new System.Drawing.Size(65, 24);
            this.lblField16.Name = "lblField16";
            this.lblField16.TabIndex = 43;
            this.lblField16.Text = "Phòng:";
            this.lblField16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboPhongNhan
            this.cboPhongNhan.Location = new System.Drawing.Point(480, 20);
            this.cboPhongNhan.Size = new System.Drawing.Size(180, 28);
            this.cboPhongNhan.Name = "cboPhongNhan";
            this.cboPhongNhan.TabIndex = 44;
            this.cboPhongNhan.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboPhongNhan.FormattingEnabled = true;
            // btnTaiNhan
            this.btnTaiNhan.Location = new System.Drawing.Point(850, 20);
            this.btnTaiNhan.Size = new System.Drawing.Size(180, 32);
            this.btnTaiNhan.Name = "btnTaiNhan";
            this.btnTaiNhan.TabIndex = 45;
            this.btnTaiNhan.Text = "Tải lại phiếu";
            this.btnTaiNhan.UseVisualStyleBackColor = true;
            // lblField17
            this.lblField17.Location = new System.Drawing.Point(16, 73);
            this.lblField17.Size = new System.Drawing.Size(85, 24);
            this.lblField17.Name = "lblField17";
            this.lblField17.TabIndex = 46;
            this.lblField17.Text = "Họ tên:";
            this.lblField17.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtNguoiTen
            this.txtNguoiTen.Location = new System.Drawing.Point(101, 70);
            this.txtNguoiTen.Size = new System.Drawing.Size(250, 28);
            this.txtNguoiTen.Name = "txtNguoiTen";
            this.txtNguoiTen.TabIndex = 47;
            this.txtNguoiTen.MaxLength = 120;
            // lblField18
            this.lblField18.Location = new System.Drawing.Point(400, 73);
            this.lblField18.Size = new System.Drawing.Size(65, 24);
            this.lblField18.Name = "lblField18";
            this.lblField18.TabIndex = 48;
            this.lblField18.Text = "CCCD:";
            this.lblField18.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtNguoiCMND
            this.txtNguoiCMND.Location = new System.Drawing.Point(465, 70);
            this.txtNguoiCMND.Size = new System.Drawing.Size(230, 28);
            this.txtNguoiCMND.Name = "txtNguoiCMND";
            this.txtNguoiCMND.TabIndex = 49;
            this.txtNguoiCMND.MaxLength = 120;
            // lblField19
            this.lblField19.Location = new System.Drawing.Point(740, 73);
            this.lblField19.Size = new System.Drawing.Size(95, 24);
            this.lblField19.Name = "lblField19";
            this.lblField19.TabIndex = 50;
            this.lblField19.Text = "Quốc tịch:";
            this.lblField19.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtNguoiQT
            this.txtNguoiQT.Location = new System.Drawing.Point(835, 70);
            this.txtNguoiQT.Size = new System.Drawing.Size(235, 28);
            this.txtNguoiQT.Name = "txtNguoiQT";
            this.txtNguoiQT.TabIndex = 51;
            this.txtNguoiQT.MaxLength = 120;
            // btnThemNguoi
            this.btnThemNguoi.Location = new System.Drawing.Point(16, 115);
            this.btnThemNguoi.Size = new System.Drawing.Size(185, 32);
            this.btnThemNguoi.Name = "btnThemNguoi";
            this.btnThemNguoi.TabIndex = 52;
            this.btnThemNguoi.Text = "Thêm người lưu trú";
            this.btnThemNguoi.UseVisualStyleBackColor = true;
            // btnNhanPhong
            this.btnNhanPhong.Location = new System.Drawing.Point(725, 115);
            this.btnNhanPhong.Size = new System.Drawing.Size(150, 32);
            this.btnNhanPhong.Name = "btnNhanPhong";
            this.btnNhanPhong.TabIndex = 53;
            this.btnNhanPhong.Text = "Nhận phòng";
            this.btnNhanPhong.UseVisualStyleBackColor = true;
            // btnNoShow
            this.btnNoShow.Location = new System.Drawing.Point(900, 115);
            this.btnNoShow.Size = new System.Drawing.Size(150, 32);
            this.btnNoShow.Name = "btnNoShow";
            this.btnNoShow.TabIndex = 54;
            this.btnNoShow.Text = "No-show";
            this.btnNoShow.UseVisualStyleBackColor = true;
            // dgvCT
            this.dgvCT.Location = new System.Drawing.Point(16, 175);
            this.dgvCT.Size = new System.Drawing.Size(1080, 160);
            this.dgvCT.Name = "dgvCT";
            this.dgvCT.TabIndex = 55;
            this.dgvCT.AllowUserToAddRows = false;
            this.dgvCT.AllowUserToDeleteRows = false;
            this.dgvCT.AutoGenerateColumns = false;
            this.dgvCT.ReadOnly = true;
            this.dgvCT.MultiSelect = false;
            this.dgvCT.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvCT.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvCT.BackgroundColor = System.Drawing.Color.White;
            this.dgvCT.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvCT.RowHeadersWidth = 28;
            this.dgvCT.EnableHeadersVisualStyles = false;
            this.dgvCT.ColumnHeadersHeight = 30;
            this.dgvCT.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvCTHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvCTHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvCTHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvCT.ColumnHeadersDefaultCellStyle = dgvCTHeader;
            this.dgvCT.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvCT_SoPhieuDat, this.dgvCT_SoPhong, this.dgvCT_SoNguoi });
            // dgvNguoi
            this.dgvNguoi.Location = new System.Drawing.Point(16, 365);
            this.dgvNguoi.Size = new System.Drawing.Size(1080, 275);
            this.dgvNguoi.Name = "dgvNguoi";
            this.dgvNguoi.TabIndex = 56;
            this.dgvNguoi.AllowUserToAddRows = false;
            this.dgvNguoi.AllowUserToDeleteRows = false;
            this.dgvNguoi.AutoGenerateColumns = false;
            this.dgvNguoi.ReadOnly = true;
            this.dgvNguoi.MultiSelect = false;
            this.dgvNguoi.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvNguoi.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvNguoi.BackgroundColor = System.Drawing.Color.White;
            this.dgvNguoi.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvNguoi.RowHeadersWidth = 28;
            this.dgvNguoi.EnableHeadersVisualStyles = false;
            this.dgvNguoi.ColumnHeadersHeight = 30;
            this.dgvNguoi.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvNguoiHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvNguoiHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvNguoiHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvNguoi.ColumnHeadersDefaultCellStyle = dgvNguoiHeader;
            this.dgvNguoi.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvNguoi_SoPhong, this.dgvNguoi_HoTen, this.dgvNguoi_SoCMND, this.dgvNguoi_QuocTich });
            // btnDong
            this.btnDong.Location = new System.Drawing.Point(1016, 734);
            this.btnDong.Size = new System.Drawing.Size(130, 32);
            this.btnDong.Name = "btnDong";
            this.btnDong.TabIndex = 57;
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.dgvKhach_MaKhach.Name = "dgvKhach_MaKhach";
            this.dgvKhach_MaKhach.DataPropertyName = "MaKhach";
            this.dgvKhach_MaKhach.HeaderText = "Mã";
            this.dgvKhach_MaKhach.ReadOnly = true;
            this.dgvKhach_HoTen.Name = "dgvKhach_HoTen";
            this.dgvKhach_HoTen.DataPropertyName = "HoTen";
            this.dgvKhach_HoTen.HeaderText = "Họ tên";
            this.dgvKhach_HoTen.ReadOnly = true;
            this.dgvKhach_SoCMND.Name = "dgvKhach_SoCMND";
            this.dgvKhach_SoCMND.DataPropertyName = "SoCMND";
            this.dgvKhach_SoCMND.HeaderText = "CCCD";
            this.dgvKhach_SoCMND.ReadOnly = true;
            this.dgvKhach_QuocTich.Name = "dgvKhach_QuocTich";
            this.dgvKhach_QuocTich.DataPropertyName = "QuocTich";
            this.dgvKhach_QuocTich.HeaderText = "Quốc tịch";
            this.dgvKhach_QuocTich.ReadOnly = true;
            this.dgvKhach_SoDienThoai.Name = "dgvKhach_SoDienThoai";
            this.dgvKhach_SoDienThoai.DataPropertyName = "SoDienThoai";
            this.dgvKhach_SoDienThoai.HeaderText = "Điện thoại";
            this.dgvKhach_SoDienThoai.ReadOnly = true;
            this.dgvPhong_SoPhong.Name = "dgvPhong_SoPhong";
            this.dgvPhong_SoPhong.DataPropertyName = "SoPhong";
            this.dgvPhong_SoPhong.HeaderText = "Phòng";
            this.dgvPhong_SoPhong.ReadOnly = true;
            this.dgvPhong_MaKhuVuc.Name = "dgvPhong_MaKhuVuc";
            this.dgvPhong_MaKhuVuc.DataPropertyName = "MaKhuVuc";
            this.dgvPhong_MaKhuVuc.HeaderText = "Khu";
            this.dgvPhong_MaKhuVuc.ReadOnly = true;
            this.dgvPhong_SoNguoiToiDa.Name = "dgvPhong_SoNguoiToiDa";
            this.dgvPhong_SoNguoiToiDa.DataPropertyName = "SoNguoiToiDa";
            this.dgvPhong_SoNguoiToiDa.HeaderText = "Sức chứa";
            this.dgvPhong_SoNguoiToiDa.ReadOnly = true;
            this.dgvPhong_DonGiaNgay.Name = "dgvPhong_DonGiaNgay";
            this.dgvPhong_DonGiaNgay.DataPropertyName = "DonGiaNgay";
            this.dgvPhong_DonGiaNgay.HeaderText = "Đơn giá";
            this.dgvPhong_DonGiaNgay.ReadOnly = true;
            this.dgvChon_SoPhong.Name = "dgvChon_SoPhong";
            this.dgvChon_SoPhong.DataPropertyName = "SoPhong";
            this.dgvChon_SoPhong.HeaderText = "Phòng chọn";
            this.dgvChon_SoPhong.ReadOnly = true;
            this.dgvChon_SoNguoi.Name = "dgvChon_SoNguoi";
            this.dgvChon_SoNguoi.DataPropertyName = "SoNguoi";
            this.dgvChon_SoNguoi.HeaderText = "Số người";
            this.dgvChon_SoNguoi.ReadOnly = true;
            this.dgvChon_DonGiaNgay.Name = "dgvChon_DonGiaNgay";
            this.dgvChon_DonGiaNgay.DataPropertyName = "DonGiaNgay";
            this.dgvChon_DonGiaNgay.HeaderText = "Đơn giá/ngày";
            this.dgvChon_DonGiaNgay.ReadOnly = true;
            this.dgvPhieu_SoPhieuDat.Name = "dgvPhieu_SoPhieuDat";
            this.dgvPhieu_SoPhieuDat.DataPropertyName = "SoPhieuDat";
            this.dgvPhieu_SoPhieuDat.HeaderText = "Số phiếu";
            this.dgvPhieu_SoPhieuDat.ReadOnly = true;
            this.dgvPhieu_HoTen.Name = "dgvPhieu_HoTen";
            this.dgvPhieu_HoTen.DataPropertyName = "HoTen";
            this.dgvPhieu_HoTen.HeaderText = "Khách";
            this.dgvPhieu_HoTen.ReadOnly = true;
            this.dgvPhieu_NgayNhan.Name = "dgvPhieu_NgayNhan";
            this.dgvPhieu_NgayNhan.DataPropertyName = "NgayNhan";
            this.dgvPhieu_NgayNhan.HeaderText = "Ngày nhận";
            this.dgvPhieu_NgayNhan.ReadOnly = true;
            this.dgvPhieu_NgayTraDuKien.Name = "dgvPhieu_NgayTraDuKien";
            this.dgvPhieu_NgayTraDuKien.DataPropertyName = "NgayTraDuKien";
            this.dgvPhieu_NgayTraDuKien.HeaderText = "Ngày trả dự kiến";
            this.dgvPhieu_NgayTraDuKien.ReadOnly = true;
            this.dgvPhieu_TienCoc.Name = "dgvPhieu_TienCoc";
            this.dgvPhieu_TienCoc.DataPropertyName = "TienCoc";
            this.dgvPhieu_TienCoc.HeaderText = "Cọc";
            this.dgvPhieu_TienCoc.ReadOnly = true;
            this.dgvPhieu_KenhDat.Name = "dgvPhieu_KenhDat";
            this.dgvPhieu_KenhDat.DataPropertyName = "KenhDat";
            this.dgvPhieu_KenhDat.HeaderText = "Kênh";
            this.dgvPhieu_KenhDat.ReadOnly = true;
            this.dgvPhieu_TrangThai.Name = "dgvPhieu_TrangThai";
            this.dgvPhieu_TrangThai.DataPropertyName = "TrangThai";
            this.dgvPhieu_TrangThai.HeaderText = "Trạng thái";
            this.dgvPhieu_TrangThai.ReadOnly = true;
            this.dgvCT_SoPhieuDat.Name = "dgvCT_SoPhieuDat";
            this.dgvCT_SoPhieuDat.DataPropertyName = "SoPhieuDat";
            this.dgvCT_SoPhieuDat.HeaderText = "Phiếu";
            this.dgvCT_SoPhieuDat.ReadOnly = true;
            this.dgvCT_SoPhong.Name = "dgvCT_SoPhong";
            this.dgvCT_SoPhong.DataPropertyName = "SoPhong";
            this.dgvCT_SoPhong.HeaderText = "Phòng";
            this.dgvCT_SoPhong.ReadOnly = true;
            this.dgvCT_SoNguoi.Name = "dgvCT_SoNguoi";
            this.dgvCT_SoNguoi.DataPropertyName = "SoNguoi";
            this.dgvCT_SoNguoi.HeaderText = "Số người đăng ký";
            this.dgvCT_SoNguoi.ReadOnly = true;
            this.dgvNguoi_SoPhong.Name = "dgvNguoi_SoPhong";
            this.dgvNguoi_SoPhong.DataPropertyName = "SoPhong";
            this.dgvNguoi_SoPhong.HeaderText = "Phòng";
            this.dgvNguoi_SoPhong.ReadOnly = true;
            this.dgvNguoi_HoTen.Name = "dgvNguoi_HoTen";
            this.dgvNguoi_HoTen.DataPropertyName = "HoTen";
            this.dgvNguoi_HoTen.HeaderText = "Họ tên";
            this.dgvNguoi_HoTen.ReadOnly = true;
            this.dgvNguoi_SoCMND.Name = "dgvNguoi_SoCMND";
            this.dgvNguoi_SoCMND.DataPropertyName = "SoCMND";
            this.dgvNguoi_SoCMND.HeaderText = "CCCD";
            this.dgvNguoi_SoCMND.ReadOnly = true;
            this.dgvNguoi_QuocTich.Name = "dgvNguoi_QuocTich";
            this.dgvNguoi_QuocTich.DataPropertyName = "QuocTich";
            this.dgvNguoi_QuocTich.HeaderText = "Quốc tịch";
            this.dgvNguoi_QuocTich.ReadOnly = true;
            this.Controls.Add(this.tabMain);
            this.tabMain.Controls.Add(this.tabKhach);
            this.tabMain.Controls.Add(this.tabDat);
            this.tabMain.Controls.Add(this.tabNhan);
            this.tabKhach.Controls.Add(this.lblField1);
            this.tabKhach.Controls.Add(this.txtMaKH);
            this.tabKhach.Controls.Add(this.lblField2);
            this.tabKhach.Controls.Add(this.txtTenKH);
            this.tabKhach.Controls.Add(this.lblField3);
            this.tabKhach.Controls.Add(this.txtCMND);
            this.tabKhach.Controls.Add(this.lblField4);
            this.tabKhach.Controls.Add(this.txtQT);
            this.tabKhach.Controls.Add(this.lblField5);
            this.tabKhach.Controls.Add(this.txtSDT);
            this.tabKhach.Controls.Add(this.btnThemKhach);
            this.tabKhach.Controls.Add(this.btnTaiKhach);
            this.tabKhach.Controls.Add(this.dgvKhach);
            this.tabDat.Controls.Add(this.lblField6);
            this.tabDat.Controls.Add(this.txtSoPhieu);
            this.tabDat.Controls.Add(this.lblField7);
            this.tabDat.Controls.Add(this.cboKhach);
            this.tabDat.Controls.Add(this.lblField8);
            this.tabDat.Controls.Add(this.cboKenh);
            this.tabDat.Controls.Add(this.lblField9);
            this.tabDat.Controls.Add(this.numCoc);
            this.tabDat.Controls.Add(this.lblField10);
            this.tabDat.Controls.Add(this.dtNhan);
            this.tabDat.Controls.Add(this.lblField11);
            this.tabDat.Controls.Add(this.dtTra);
            this.tabDat.Controls.Add(this.lblField12);
            this.tabDat.Controls.Add(this.cboNV);
            this.tabDat.Controls.Add(this.lblField13);
            this.tabDat.Controls.Add(this.numSoNguoi);
            this.tabDat.Controls.Add(this.dgvPhong);
            this.tabDat.Controls.Add(this.dgvChon);
            this.tabDat.Controls.Add(this.btnThemPhong);
            this.tabDat.Controls.Add(this.btnBoPhong);
            this.tabDat.Controls.Add(this.btnTaiDat);
            this.tabDat.Controls.Add(this.btnLapPhieu);
            this.tabDat.Controls.Add(this.lblField14);
            this.tabDat.Controls.Add(this.dgvPhieu);
            this.tabNhan.Controls.Add(this.lblField15);
            this.tabNhan.Controls.Add(this.cboPhieuNhan);
            this.tabNhan.Controls.Add(this.lblField16);
            this.tabNhan.Controls.Add(this.cboPhongNhan);
            this.tabNhan.Controls.Add(this.btnTaiNhan);
            this.tabNhan.Controls.Add(this.lblField17);
            this.tabNhan.Controls.Add(this.txtNguoiTen);
            this.tabNhan.Controls.Add(this.lblField18);
            this.tabNhan.Controls.Add(this.txtNguoiCMND);
            this.tabNhan.Controls.Add(this.lblField19);
            this.tabNhan.Controls.Add(this.txtNguoiQT);
            this.tabNhan.Controls.Add(this.btnThemNguoi);
            this.tabNhan.Controls.Add(this.btnNhanPhong);
            this.tabNhan.Controls.Add(this.btnNoShow);
            this.tabNhan.Controls.Add(this.dgvCT);
            this.tabNhan.Controls.Add(this.dgvNguoi);
            this.Controls.Add(this.btnDong);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1160, 780);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Name = "FrmDatPhong";
            this.Text = "Khách hàng - Đặt phòng - Nhận phòng";
            this.Load += new System.EventHandler(this.FrmDatPhong_Load);
            this.tabMain.ResumeLayout(false);
            this.tabMain.PerformLayout();
            this.tabKhach.ResumeLayout(false);
            this.tabKhach.PerformLayout();
            this.tabDat.ResumeLayout(false);
            this.tabDat.PerformLayout();
            this.tabNhan.ResumeLayout(false);
            this.tabNhan.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvKhach)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCoc)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSoNguoi)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvChon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhieu)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCT)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvNguoi)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.TabPage tabKhach;
        private System.Windows.Forms.TabPage tabDat;
        private System.Windows.Forms.TabPage tabNhan;
        private System.Windows.Forms.Label lblField1;
        private System.Windows.Forms.TextBox txtMaKH;
        private System.Windows.Forms.Label lblField2;
        private System.Windows.Forms.TextBox txtTenKH;
        private System.Windows.Forms.Label lblField3;
        private System.Windows.Forms.TextBox txtCMND;
        private System.Windows.Forms.Label lblField4;
        private System.Windows.Forms.TextBox txtQT;
        private System.Windows.Forms.Label lblField5;
        private System.Windows.Forms.TextBox txtSDT;
        private System.Windows.Forms.Button btnThemKhach;
        private System.Windows.Forms.Button btnTaiKhach;
        private System.Windows.Forms.DataGridView dgvKhach;
        private System.Windows.Forms.Label lblField6;
        private System.Windows.Forms.TextBox txtSoPhieu;
        private System.Windows.Forms.Label lblField7;
        private System.Windows.Forms.ComboBox cboKhach;
        private System.Windows.Forms.Label lblField8;
        private System.Windows.Forms.ComboBox cboKenh;
        private System.Windows.Forms.Label lblField9;
        private System.Windows.Forms.NumericUpDown numCoc;
        private System.Windows.Forms.Label lblField10;
        private System.Windows.Forms.DateTimePicker dtNhan;
        private System.Windows.Forms.Label lblField11;
        private System.Windows.Forms.DateTimePicker dtTra;
        private System.Windows.Forms.Label lblField12;
        private System.Windows.Forms.ComboBox cboNV;
        private System.Windows.Forms.Label lblField13;
        private System.Windows.Forms.NumericUpDown numSoNguoi;
        private System.Windows.Forms.DataGridView dgvPhong;
        private System.Windows.Forms.DataGridView dgvChon;
        private System.Windows.Forms.Button btnThemPhong;
        private System.Windows.Forms.Button btnBoPhong;
        private System.Windows.Forms.Button btnTaiDat;
        private System.Windows.Forms.Button btnLapPhieu;
        private System.Windows.Forms.Label lblField14;
        private System.Windows.Forms.DataGridView dgvPhieu;
        private System.Windows.Forms.Label lblField15;
        private System.Windows.Forms.ComboBox cboPhieuNhan;
        private System.Windows.Forms.Label lblField16;
        private System.Windows.Forms.ComboBox cboPhongNhan;
        private System.Windows.Forms.Button btnTaiNhan;
        private System.Windows.Forms.Label lblField17;
        private System.Windows.Forms.TextBox txtNguoiTen;
        private System.Windows.Forms.Label lblField18;
        private System.Windows.Forms.TextBox txtNguoiCMND;
        private System.Windows.Forms.Label lblField19;
        private System.Windows.Forms.TextBox txtNguoiQT;
        private System.Windows.Forms.Button btnThemNguoi;
        private System.Windows.Forms.Button btnNhanPhong;
        private System.Windows.Forms.Button btnNoShow;
        private System.Windows.Forms.DataGridView dgvCT;
        private System.Windows.Forms.DataGridView dgvNguoi;
        private System.Windows.Forms.Button btnDong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvKhach_MaKhach;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvKhach_HoTen;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvKhach_SoCMND;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvKhach_QuocTich;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvKhach_SoDienThoai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_SoPhong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_MaKhuVuc;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_SoNguoiToiDa;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_DonGiaNgay;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvChon_SoPhong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvChon_SoNguoi;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvChon_DonGiaNgay;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhieu_SoPhieuDat;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhieu_HoTen;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhieu_NgayNhan;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhieu_NgayTraDuKien;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhieu_TienCoc;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhieu_KenhDat;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhieu_TrangThai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvCT_SoPhieuDat;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvCT_SoPhong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvCT_SoNguoi;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvNguoi_SoPhong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvNguoi_HoTen;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvNguoi_SoCMND;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvNguoi_QuocTich;
    }
}
