namespace QuanLyKhachSan.Forms
{
    partial class FrmPhongTienNghi
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabMain = new System.Windows.Forms.TabControl();
            this.tabPhong = new System.Windows.Forms.TabPage();
            this.tabTN = new System.Windows.Forms.TabPage();
            this.tabLD = new System.Windows.Forms.TabPage();
            this.lblField1 = new System.Windows.Forms.Label();
            this.txtPhong = new System.Windows.Forms.TextBox();
            this.lblField2 = new System.Windows.Forms.Label();
            this.cboKhu = new System.Windows.Forms.ComboBox();
            this.lblField3 = new System.Windows.Forms.Label();
            this.numMax = new System.Windows.Forms.NumericUpDown();
            this.lblField4 = new System.Windows.Forms.Label();
            this.numGia = new System.Windows.Forms.NumericUpDown();
            this.btnThemPhong = new System.Windows.Forms.Button();
            this.btnTaiPhong = new System.Windows.Forms.Button();
            this.dgvPhong = new System.Windows.Forms.DataGridView();
            this.lblField5 = new System.Windows.Forms.Label();
            this.txtMaTN = new System.Windows.Forms.TextBox();
            this.lblField6 = new System.Windows.Forms.Label();
            this.cboLoai = new System.Windows.Forms.ComboBox();
            this.lblField7 = new System.Windows.Forms.Label();
            this.numSTT = new System.Windows.Forms.NumericUpDown();
            this.lblField8 = new System.Windows.Forms.Label();
            this.txtTinhTrang = new System.Windows.Forms.TextBox();
            this.btnThemTN = new System.Windows.Forms.Button();
            this.btnTaiTN = new System.Windows.Forms.Button();
            this.dgvTN = new System.Windows.Forms.DataGridView();
            this.dgvLD = new System.Windows.Forms.DataGridView();
            this.lblField9 = new System.Windows.Forms.Label();
            this.lblField10 = new System.Windows.Forms.Label();
            this.txtSoLD = new System.Windows.Forms.TextBox();
            this.lblField11 = new System.Windows.Forms.Label();
            this.cboTN = new System.Windows.Forms.ComboBox();
            this.lblField12 = new System.Windows.Forms.Label();
            this.cboPhong = new System.Windows.Forms.ComboBox();
            this.lblField13 = new System.Windows.Forms.Label();
            this.txtTTLD = new System.Windows.Forms.TextBox();
            this.lblField14 = new System.Windows.Forms.Label();
            this.dtNgay = new System.Windows.Forms.DateTimePicker();
            this.lblField15 = new System.Windows.Forms.Label();
            this.cboNV = new System.Windows.Forms.ComboBox();
            this.lblField16 = new System.Windows.Forms.Label();
            this.txtGhiChu = new System.Windows.Forms.TextBox();
            this.btnLapDat = new System.Windows.Forms.Button();
            this.btnTai = new System.Windows.Forms.Button();
            this.btnDong = new System.Windows.Forms.Button();
            this.dgvPhong_SoPhong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhong_MaKhuVuc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhong_SoNguoiToiDa = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhong_DonGiaNgay = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhong_TrangThai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTN_MaTienNghi = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTN_MaLoaiTN = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTN_SoThuTu = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTN_TinhTrangHienTai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLD_SoPhieuLapDat = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLD_MaTienNghi = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLD_SoPhong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLD_NgayLap = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLD_TinhTrang = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLD_MaNV = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tabMain.SuspendLayout();
            this.tabPhong.SuspendLayout();
            this.tabTN.SuspendLayout();
            this.tabLD.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numMax)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGia)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSTT)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTN)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLD)).BeginInit();
            this.SuspendLayout();
            // tabMain
            this.tabMain.Location = new System.Drawing.Point(12, 12);
            this.tabMain.Size = new System.Drawing.Size(1072, 470);
            this.tabMain.Name = "tabMain";
            this.tabMain.TabIndex = 0;
            // tabPhong
            this.tabPhong.Location = new System.Drawing.Point(4, 27);
            this.tabPhong.Size = new System.Drawing.Size(1064, 439);
            this.tabPhong.Name = "tabPhong";
            this.tabPhong.TabIndex = 1;
            this.tabPhong.Text = "Phòng";
            this.tabPhong.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabPhong.Padding = new System.Windows.Forms.Padding(8);
            // tabTN
            this.tabTN.Location = new System.Drawing.Point(4, 27);
            this.tabTN.Size = new System.Drawing.Size(1064, 439);
            this.tabTN.Name = "tabTN";
            this.tabTN.TabIndex = 2;
            this.tabTN.Text = "Tiện nghi";
            this.tabTN.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabTN.Padding = new System.Windows.Forms.Padding(8);
            // tabLD
            this.tabLD.Location = new System.Drawing.Point(4, 27);
            this.tabLD.Size = new System.Drawing.Size(1064, 439);
            this.tabLD.Name = "tabLD";
            this.tabLD.TabIndex = 3;
            this.tabLD.Text = "Lịch sử lắp đặt / luân chuyển";
            this.tabLD.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.tabLD.Padding = new System.Windows.Forms.Padding(8);
            // lblField1
            this.lblField1.Location = new System.Drawing.Point(12, 23);
            this.lblField1.Size = new System.Drawing.Size(80, 24);
            this.lblField1.Name = "lblField1";
            this.lblField1.TabIndex = 4;
            this.lblField1.Text = "Số phòng:";
            this.lblField1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtPhong
            this.txtPhong.Location = new System.Drawing.Point(92, 20);
            this.txtPhong.Size = new System.Drawing.Size(120, 28);
            this.txtPhong.Name = "txtPhong";
            this.txtPhong.TabIndex = 5;
            this.txtPhong.MaxLength = 120;
            // lblField2
            this.lblField2.Location = new System.Drawing.Point(225, 23);
            this.lblField2.Size = new System.Drawing.Size(75, 24);
            this.lblField2.Name = "lblField2";
            this.lblField2.TabIndex = 6;
            this.lblField2.Text = "Khu vực:";
            this.lblField2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboKhu
            this.cboKhu.Location = new System.Drawing.Point(300, 20);
            this.cboKhu.Size = new System.Drawing.Size(155, 28);
            this.cboKhu.Name = "cboKhu";
            this.cboKhu.TabIndex = 7;
            this.cboKhu.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboKhu.FormattingEnabled = true;
            // lblField3
            this.lblField3.Location = new System.Drawing.Point(470, 23);
            this.lblField3.Size = new System.Drawing.Size(125, 24);
            this.lblField3.Name = "lblField3";
            this.lblField3.TabIndex = 8;
            this.lblField3.Text = "Số người tối đa:";
            this.lblField3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numMax
            this.numMax.Location = new System.Drawing.Point(595, 20);
            this.numMax.Size = new System.Drawing.Size(95, 28);
            this.numMax.Name = "numMax";
            this.numMax.TabIndex = 9;
            this.numMax.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numMax.ThousandsSeparator = true;
            // lblField4
            this.lblField4.Location = new System.Drawing.Point(710, 23);
            this.lblField4.Size = new System.Drawing.Size(115, 24);
            this.lblField4.Name = "lblField4";
            this.lblField4.TabIndex = 10;
            this.lblField4.Text = "Đơn giá/ngày:";
            this.lblField4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numGia
            this.numGia.Location = new System.Drawing.Point(825, 20);
            this.numGia.Size = new System.Drawing.Size(130, 28);
            this.numGia.Name = "numGia";
            this.numGia.TabIndex = 11;
            this.numGia.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numGia.ThousandsSeparator = true;
            // btnThemPhong
            this.btnThemPhong.Location = new System.Drawing.Point(745, 63);
            this.btnThemPhong.Size = new System.Drawing.Size(125, 32);
            this.btnThemPhong.Name = "btnThemPhong";
            this.btnThemPhong.TabIndex = 12;
            this.btnThemPhong.Text = "Thêm phòng";
            this.btnThemPhong.UseVisualStyleBackColor = true;
            // btnTaiPhong
            this.btnTaiPhong.Location = new System.Drawing.Point(895, 63);
            this.btnTaiPhong.Size = new System.Drawing.Size(125, 32);
            this.btnTaiPhong.Name = "btnTaiPhong";
            this.btnTaiPhong.TabIndex = 13;
            this.btnTaiPhong.Text = "Tải lại";
            this.btnTaiPhong.UseVisualStyleBackColor = true;
            // dgvPhong
            this.dgvPhong.Location = new System.Drawing.Point(15, 110);
            this.dgvPhong.Size = new System.Drawing.Size(1010, 295);
            this.dgvPhong.Name = "dgvPhong";
            this.dgvPhong.TabIndex = 14;
            this.dgvPhong.AllowUserToAddRows = false;
            this.dgvPhong.AllowUserToDeleteRows = false;
            this.dgvPhong.AutoGenerateColumns = false;
            this.dgvPhong.ReadOnly = true;
            this.dgvPhong.MultiSelect = false;
            this.dgvPhong.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPhong.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPhong.BackgroundColor = System.Drawing.Color.White;
            this.dgvPhong.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvPhong.RowHeadersWidth = 28;
            this.dgvPhong.EnableHeadersVisualStyles = false;
            this.dgvPhong.ColumnHeadersHeight = 30;
            this.dgvPhong.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvPhongHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvPhongHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvPhongHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvPhong.ColumnHeadersDefaultCellStyle = dgvPhongHeader;
            this.dgvPhong.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvPhong_SoPhong, this.dgvPhong_MaKhuVuc, this.dgvPhong_SoNguoiToiDa, this.dgvPhong_DonGiaNgay, this.dgvPhong_TrangThai });
            // lblField5
            this.lblField5.Location = new System.Drawing.Point(12, 23);
            this.lblField5.Size = new System.Drawing.Size(95, 24);
            this.lblField5.Name = "lblField5";
            this.lblField5.TabIndex = 15;
            this.lblField5.Text = "Mã thiết bị:";
            this.lblField5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtMaTN
            this.txtMaTN.Location = new System.Drawing.Point(107, 20);
            this.txtMaTN.Size = new System.Drawing.Size(130, 28);
            this.txtMaTN.Name = "txtMaTN";
            this.txtMaTN.TabIndex = 16;
            this.txtMaTN.MaxLength = 120;
            // lblField6
            this.lblField6.Location = new System.Drawing.Point(260, 23);
            this.lblField6.Size = new System.Drawing.Size(55, 24);
            this.lblField6.Name = "lblField6";
            this.lblField6.TabIndex = 17;
            this.lblField6.Text = "Loại:";
            this.lblField6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboLoai
            this.cboLoai.Location = new System.Drawing.Point(315, 20);
            this.cboLoai.Size = new System.Drawing.Size(180, 28);
            this.cboLoai.Name = "cboLoai";
            this.cboLoai.TabIndex = 18;
            this.cboLoai.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboLoai.FormattingEnabled = true;
            // lblField7
            this.lblField7.Location = new System.Drawing.Point(520, 23);
            this.lblField7.Size = new System.Drawing.Size(90, 24);
            this.lblField7.Name = "lblField7";
            this.lblField7.TabIndex = 19;
            this.lblField7.Text = "Số thứ tự:";
            this.lblField7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numSTT
            this.numSTT.Location = new System.Drawing.Point(610, 20);
            this.numSTT.Size = new System.Drawing.Size(90, 28);
            this.numSTT.Name = "numSTT";
            this.numSTT.TabIndex = 20;
            this.numSTT.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numSTT.ThousandsSeparator = true;
            // lblField8
            this.lblField8.Location = new System.Drawing.Point(730, 23);
            this.lblField8.Size = new System.Drawing.Size(95, 24);
            this.lblField8.Name = "lblField8";
            this.lblField8.TabIndex = 21;
            this.lblField8.Text = "Tình trạng:";
            this.lblField8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtTinhTrang
            this.txtTinhTrang.Location = new System.Drawing.Point(825, 20);
            this.txtTinhTrang.Size = new System.Drawing.Size(170, 28);
            this.txtTinhTrang.Name = "txtTinhTrang";
            this.txtTinhTrang.TabIndex = 22;
            this.txtTinhTrang.MaxLength = 120;
            // btnThemTN
            this.btnThemTN.Location = new System.Drawing.Point(745, 63);
            this.btnThemTN.Size = new System.Drawing.Size(125, 32);
            this.btnThemTN.Name = "btnThemTN";
            this.btnThemTN.TabIndex = 23;
            this.btnThemTN.Text = "Thêm tiện nghi";
            this.btnThemTN.UseVisualStyleBackColor = true;
            // btnTaiTN
            this.btnTaiTN.Location = new System.Drawing.Point(895, 63);
            this.btnTaiTN.Size = new System.Drawing.Size(125, 32);
            this.btnTaiTN.Name = "btnTaiTN";
            this.btnTaiTN.TabIndex = 24;
            this.btnTaiTN.Text = "Tải lại";
            this.btnTaiTN.UseVisualStyleBackColor = true;
            // dgvTN
            this.dgvTN.Location = new System.Drawing.Point(15, 110);
            this.dgvTN.Size = new System.Drawing.Size(1010, 295);
            this.dgvTN.Name = "dgvTN";
            this.dgvTN.TabIndex = 25;
            this.dgvTN.AllowUserToAddRows = false;
            this.dgvTN.AllowUserToDeleteRows = false;
            this.dgvTN.AutoGenerateColumns = false;
            this.dgvTN.ReadOnly = true;
            this.dgvTN.MultiSelect = false;
            this.dgvTN.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvTN.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvTN.BackgroundColor = System.Drawing.Color.White;
            this.dgvTN.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvTN.RowHeadersWidth = 28;
            this.dgvTN.EnableHeadersVisualStyles = false;
            this.dgvTN.ColumnHeadersHeight = 30;
            this.dgvTN.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvTNHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvTNHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvTNHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvTN.ColumnHeadersDefaultCellStyle = dgvTNHeader;
            this.dgvTN.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvTN_MaTienNghi, this.dgvTN_MaLoaiTN, this.dgvTN_SoThuTu, this.dgvTN_TinhTrangHienTai });
            // dgvLD
            this.dgvLD.Location = new System.Drawing.Point(15, 20);
            this.dgvLD.Size = new System.Drawing.Size(1010, 385);
            this.dgvLD.Name = "dgvLD";
            this.dgvLD.TabIndex = 26;
            this.dgvLD.AllowUserToAddRows = false;
            this.dgvLD.AllowUserToDeleteRows = false;
            this.dgvLD.AutoGenerateColumns = false;
            this.dgvLD.ReadOnly = true;
            this.dgvLD.MultiSelect = false;
            this.dgvLD.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvLD.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvLD.BackgroundColor = System.Drawing.Color.White;
            this.dgvLD.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvLD.RowHeadersWidth = 28;
            this.dgvLD.EnableHeadersVisualStyles = false;
            this.dgvLD.ColumnHeadersHeight = 30;
            this.dgvLD.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvLDHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvLDHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvLDHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvLD.ColumnHeadersDefaultCellStyle = dgvLDHeader;
            this.dgvLD.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvLD_SoPhieuLapDat, this.dgvLD_MaTienNghi, this.dgvLD_SoPhong, this.dgvLD_NgayLap, this.dgvLD_TinhTrang, this.dgvLD_MaNV });
            // lblField9
            this.lblField9.Location = new System.Drawing.Point(24, 500);
            this.lblField9.Size = new System.Drawing.Size(600, 24);
            this.lblField9.Name = "lblField9";
            this.lblField9.TabIndex = 27;
            this.lblField9.Text = "LẬP PHIẾU LẮP ĐẶT / LUÂN CHUYỂN";
            this.lblField9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // lblField10
            this.lblField10.Location = new System.Drawing.Point(24, 543);
            this.lblField10.Size = new System.Drawing.Size(100, 24);
            this.lblField10.Name = "lblField10";
            this.lblField10.TabIndex = 28;
            this.lblField10.Text = "Phiếu lắp đặt:";
            this.lblField10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtSoLD
            this.txtSoLD.Location = new System.Drawing.Point(124, 540);
            this.txtSoLD.Size = new System.Drawing.Size(135, 28);
            this.txtSoLD.Name = "txtSoLD";
            this.txtSoLD.TabIndex = 29;
            this.txtSoLD.MaxLength = 120;
            // lblField11
            this.lblField11.Location = new System.Drawing.Point(285, 543);
            this.lblField11.Size = new System.Drawing.Size(80, 24);
            this.lblField11.Name = "lblField11";
            this.lblField11.TabIndex = 30;
            this.lblField11.Text = "Tiện nghi:";
            this.lblField11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboTN
            this.cboTN.Location = new System.Drawing.Point(365, 540);
            this.cboTN.Size = new System.Drawing.Size(140, 28);
            this.cboTN.Name = "cboTN";
            this.cboTN.TabIndex = 31;
            this.cboTN.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTN.FormattingEnabled = true;
            // lblField12
            this.lblField12.Location = new System.Drawing.Point(540, 543);
            this.lblField12.Size = new System.Drawing.Size(60, 24);
            this.lblField12.Name = "lblField12";
            this.lblField12.TabIndex = 32;
            this.lblField12.Text = "Phòng:";
            this.lblField12.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboPhong
            this.cboPhong.Location = new System.Drawing.Point(600, 540);
            this.cboPhong.Size = new System.Drawing.Size(130, 28);
            this.cboPhong.Name = "cboPhong";
            this.cboPhong.TabIndex = 33;
            this.cboPhong.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboPhong.FormattingEnabled = true;
            // lblField13
            this.lblField13.Location = new System.Drawing.Point(775, 543);
            this.lblField13.Size = new System.Drawing.Size(95, 24);
            this.lblField13.Name = "lblField13";
            this.lblField13.TabIndex = 34;
            this.lblField13.Text = "Tình trạng:";
            this.lblField13.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtTTLD
            this.txtTTLD.Location = new System.Drawing.Point(870, 540);
            this.txtTTLD.Size = new System.Drawing.Size(180, 28);
            this.txtTTLD.Name = "txtTTLD";
            this.txtTTLD.TabIndex = 35;
            this.txtTTLD.MaxLength = 120;
            // lblField14
            this.lblField14.Location = new System.Drawing.Point(24, 588);
            this.lblField14.Size = new System.Drawing.Size(100, 24);
            this.lblField14.Name = "lblField14";
            this.lblField14.TabIndex = 36;
            this.lblField14.Text = "Ngày lắp:";
            this.lblField14.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // dtNgay
            this.dtNgay.Location = new System.Drawing.Point(124, 585);
            this.dtNgay.Size = new System.Drawing.Size(150, 28);
            this.dtNgay.Name = "dtNgay";
            this.dtNgay.TabIndex = 37;
            this.dtNgay.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtNgay.CustomFormat = "dd/MM/yyyy";
            // lblField15
            this.lblField15.Location = new System.Drawing.Point(305, 588);
            this.lblField15.Size = new System.Drawing.Size(90, 24);
            this.lblField15.Name = "lblField15";
            this.lblField15.TabIndex = 38;
            this.lblField15.Text = "Nhân viên:";
            this.lblField15.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboNV
            this.cboNV.Location = new System.Drawing.Point(395, 585);
            this.cboNV.Size = new System.Drawing.Size(220, 28);
            this.cboNV.Name = "cboNV";
            this.cboNV.TabIndex = 39;
            this.cboNV.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboNV.FormattingEnabled = true;
            // lblField16
            this.lblField16.Location = new System.Drawing.Point(650, 588);
            this.lblField16.Size = new System.Drawing.Size(90, 24);
            this.lblField16.Name = "lblField16";
            this.lblField16.TabIndex = 40;
            this.lblField16.Text = "Ghi chú:";
            this.lblField16.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtGhiChu
            this.txtGhiChu.Location = new System.Drawing.Point(740, 585);
            this.txtGhiChu.Size = new System.Drawing.Size(310, 28);
            this.txtGhiChu.Name = "txtGhiChu";
            this.txtGhiChu.TabIndex = 41;
            this.txtGhiChu.MaxLength = 120;
            // btnLapDat
            this.btnLapDat.Location = new System.Drawing.Point(770, 640);
            this.btnLapDat.Size = new System.Drawing.Size(140, 32);
            this.btnLapDat.Name = "btnLapDat";
            this.btnLapDat.TabIndex = 42;
            this.btnLapDat.Text = "Lập phiếu";
            this.btnLapDat.UseVisualStyleBackColor = true;
            // btnTai
            this.btnTai.Location = new System.Drawing.Point(930, 640);
            this.btnTai.Size = new System.Drawing.Size(130, 32);
            this.btnTai.Name = "btnTai";
            this.btnTai.TabIndex = 43;
            this.btnTai.Text = "Tải lại";
            this.btnTai.UseVisualStyleBackColor = true;
            // btnDong
            this.btnDong.Location = new System.Drawing.Point(930, 705);
            this.btnDong.Size = new System.Drawing.Size(130, 32);
            this.btnDong.Name = "btnDong";
            this.btnDong.TabIndex = 44;
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.dgvPhong_SoPhong.Name = "dgvPhong_SoPhong";
            this.dgvPhong_SoPhong.DataPropertyName = "SoPhong";
            this.dgvPhong_SoPhong.HeaderText = "Phòng";
            this.dgvPhong_SoPhong.ReadOnly = true;
            this.dgvPhong_MaKhuVuc.Name = "dgvPhong_MaKhuVuc";
            this.dgvPhong_MaKhuVuc.DataPropertyName = "MaKhuVuc";
            this.dgvPhong_MaKhuVuc.HeaderText = "Khu";
            this.dgvPhong_MaKhuVuc.ReadOnly = true;
            this.dgvPhong_SoNguoiToiDa.Name = "dgvPhong_SoNguoiToiDa";
            this.dgvPhong_SoNguoiToiDa.DataPropertyName = "SoNguoiToiDa";
            this.dgvPhong_SoNguoiToiDa.HeaderText = "Sức chứa";
            this.dgvPhong_SoNguoiToiDa.ReadOnly = true;
            this.dgvPhong_DonGiaNgay.Name = "dgvPhong_DonGiaNgay";
            this.dgvPhong_DonGiaNgay.DataPropertyName = "DonGiaNgay";
            this.dgvPhong_DonGiaNgay.HeaderText = "Đơn giá";
            this.dgvPhong_DonGiaNgay.ReadOnly = true;
            this.dgvPhong_TrangThai.Name = "dgvPhong_TrangThai";
            this.dgvPhong_TrangThai.DataPropertyName = "TrangThai";
            this.dgvPhong_TrangThai.HeaderText = "Trạng thái";
            this.dgvPhong_TrangThai.ReadOnly = true;
            this.dgvTN_MaTienNghi.Name = "dgvTN_MaTienNghi";
            this.dgvTN_MaTienNghi.DataPropertyName = "MaTienNghi";
            this.dgvTN_MaTienNghi.HeaderText = "Thiết bị";
            this.dgvTN_MaTienNghi.ReadOnly = true;
            this.dgvTN_MaLoaiTN.Name = "dgvTN_MaLoaiTN";
            this.dgvTN_MaLoaiTN.DataPropertyName = "MaLoaiTN";
            this.dgvTN_MaLoaiTN.HeaderText = "Loại";
            this.dgvTN_MaLoaiTN.ReadOnly = true;
            this.dgvTN_SoThuTu.Name = "dgvTN_SoThuTu";
            this.dgvTN_SoThuTu.DataPropertyName = "SoThuTu";
            this.dgvTN_SoThuTu.HeaderText = "Số thứ tự";
            this.dgvTN_SoThuTu.ReadOnly = true;
            this.dgvTN_TinhTrangHienTai.Name = "dgvTN_TinhTrangHienTai";
            this.dgvTN_TinhTrangHienTai.DataPropertyName = "TinhTrangHienTai";
            this.dgvTN_TinhTrangHienTai.HeaderText = "Tình trạng";
            this.dgvTN_TinhTrangHienTai.ReadOnly = true;
            this.dgvLD_SoPhieuLapDat.Name = "dgvLD_SoPhieuLapDat";
            this.dgvLD_SoPhieuLapDat.DataPropertyName = "SoPhieuLapDat";
            this.dgvLD_SoPhieuLapDat.HeaderText = "Phiếu lắp đặt";
            this.dgvLD_SoPhieuLapDat.ReadOnly = true;
            this.dgvLD_MaTienNghi.Name = "dgvLD_MaTienNghi";
            this.dgvLD_MaTienNghi.DataPropertyName = "MaTienNghi";
            this.dgvLD_MaTienNghi.HeaderText = "Thiết bị";
            this.dgvLD_MaTienNghi.ReadOnly = true;
            this.dgvLD_SoPhong.Name = "dgvLD_SoPhong";
            this.dgvLD_SoPhong.DataPropertyName = "SoPhong";
            this.dgvLD_SoPhong.HeaderText = "Phòng";
            this.dgvLD_SoPhong.ReadOnly = true;
            this.dgvLD_NgayLap.Name = "dgvLD_NgayLap";
            this.dgvLD_NgayLap.DataPropertyName = "NgayLap";
            this.dgvLD_NgayLap.HeaderText = "Ngày";
            this.dgvLD_NgayLap.ReadOnly = true;
            this.dgvLD_TinhTrang.Name = "dgvLD_TinhTrang";
            this.dgvLD_TinhTrang.DataPropertyName = "TinhTrang";
            this.dgvLD_TinhTrang.HeaderText = "Tình trạng";
            this.dgvLD_TinhTrang.ReadOnly = true;
            this.dgvLD_MaNV.Name = "dgvLD_MaNV";
            this.dgvLD_MaNV.DataPropertyName = "MaNV";
            this.dgvLD_MaNV.HeaderText = "Nhân viên";
            this.dgvLD_MaNV.ReadOnly = true;
            this.Controls.Add(this.tabMain);
            this.tabMain.Controls.Add(this.tabPhong);
            this.tabMain.Controls.Add(this.tabTN);
            this.tabMain.Controls.Add(this.tabLD);
            this.tabPhong.Controls.Add(this.lblField1);
            this.tabPhong.Controls.Add(this.txtPhong);
            this.tabPhong.Controls.Add(this.lblField2);
            this.tabPhong.Controls.Add(this.cboKhu);
            this.tabPhong.Controls.Add(this.lblField3);
            this.tabPhong.Controls.Add(this.numMax);
            this.tabPhong.Controls.Add(this.lblField4);
            this.tabPhong.Controls.Add(this.numGia);
            this.tabPhong.Controls.Add(this.btnThemPhong);
            this.tabPhong.Controls.Add(this.btnTaiPhong);
            this.tabPhong.Controls.Add(this.dgvPhong);
            this.tabTN.Controls.Add(this.lblField5);
            this.tabTN.Controls.Add(this.txtMaTN);
            this.tabTN.Controls.Add(this.lblField6);
            this.tabTN.Controls.Add(this.cboLoai);
            this.tabTN.Controls.Add(this.lblField7);
            this.tabTN.Controls.Add(this.numSTT);
            this.tabTN.Controls.Add(this.lblField8);
            this.tabTN.Controls.Add(this.txtTinhTrang);
            this.tabTN.Controls.Add(this.btnThemTN);
            this.tabTN.Controls.Add(this.btnTaiTN);
            this.tabTN.Controls.Add(this.dgvTN);
            this.tabLD.Controls.Add(this.dgvLD);
            this.Controls.Add(this.lblField9);
            this.Controls.Add(this.lblField10);
            this.Controls.Add(this.txtSoLD);
            this.Controls.Add(this.lblField11);
            this.Controls.Add(this.cboTN);
            this.Controls.Add(this.lblField12);
            this.Controls.Add(this.cboPhong);
            this.Controls.Add(this.lblField13);
            this.Controls.Add(this.txtTTLD);
            this.Controls.Add(this.lblField14);
            this.Controls.Add(this.dtNgay);
            this.Controls.Add(this.lblField15);
            this.Controls.Add(this.cboNV);
            this.Controls.Add(this.lblField16);
            this.Controls.Add(this.txtGhiChu);
            this.Controls.Add(this.btnLapDat);
            this.Controls.Add(this.btnTai);
            this.Controls.Add(this.btnDong);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 760);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Name = "FrmPhongTienNghi";
            this.Text = "Phòng - Tiện nghi - Phiếu lắp đặt";
            this.Load += new System.EventHandler(this.FrmPhongTienNghi_Load);
            this.tabMain.ResumeLayout(false);
            this.tabMain.PerformLayout();
            this.tabPhong.ResumeLayout(false);
            this.tabPhong.PerformLayout();
            this.tabTN.ResumeLayout(false);
            this.tabTN.PerformLayout();
            this.tabLD.ResumeLayout(false);
            this.tabLD.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.numMax)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numGia)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSTT)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTN)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLD)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.TabPage tabPhong;
        private System.Windows.Forms.TabPage tabTN;
        private System.Windows.Forms.TabPage tabLD;
        private System.Windows.Forms.Label lblField1;
        private System.Windows.Forms.TextBox txtPhong;
        private System.Windows.Forms.Label lblField2;
        private System.Windows.Forms.ComboBox cboKhu;
        private System.Windows.Forms.Label lblField3;
        private System.Windows.Forms.NumericUpDown numMax;
        private System.Windows.Forms.Label lblField4;
        private System.Windows.Forms.NumericUpDown numGia;
        private System.Windows.Forms.Button btnThemPhong;
        private System.Windows.Forms.Button btnTaiPhong;
        private System.Windows.Forms.DataGridView dgvPhong;
        private System.Windows.Forms.Label lblField5;
        private System.Windows.Forms.TextBox txtMaTN;
        private System.Windows.Forms.Label lblField6;
        private System.Windows.Forms.ComboBox cboLoai;
        private System.Windows.Forms.Label lblField7;
        private System.Windows.Forms.NumericUpDown numSTT;
        private System.Windows.Forms.Label lblField8;
        private System.Windows.Forms.TextBox txtTinhTrang;
        private System.Windows.Forms.Button btnThemTN;
        private System.Windows.Forms.Button btnTaiTN;
        private System.Windows.Forms.DataGridView dgvTN;
        private System.Windows.Forms.DataGridView dgvLD;
        private System.Windows.Forms.Label lblField9;
        private System.Windows.Forms.Label lblField10;
        private System.Windows.Forms.TextBox txtSoLD;
        private System.Windows.Forms.Label lblField11;
        private System.Windows.Forms.ComboBox cboTN;
        private System.Windows.Forms.Label lblField12;
        private System.Windows.Forms.ComboBox cboPhong;
        private System.Windows.Forms.Label lblField13;
        private System.Windows.Forms.TextBox txtTTLD;
        private System.Windows.Forms.Label lblField14;
        private System.Windows.Forms.DateTimePicker dtNgay;
        private System.Windows.Forms.Label lblField15;
        private System.Windows.Forms.ComboBox cboNV;
        private System.Windows.Forms.Label lblField16;
        private System.Windows.Forms.TextBox txtGhiChu;
        private System.Windows.Forms.Button btnLapDat;
        private System.Windows.Forms.Button btnTai;
        private System.Windows.Forms.Button btnDong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_SoPhong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_MaKhuVuc;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_SoNguoiToiDa;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_DonGiaNgay;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_TrangThai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTN_MaTienNghi;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTN_MaLoaiTN;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTN_SoThuTu;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTN_TinhTrangHienTai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLD_SoPhieuLapDat;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLD_MaTienNghi;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLD_SoPhong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLD_NgayLap;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLD_TinhTrang;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLD_MaNV;
    }
}
