namespace QuanLyKhachSan.Forms
{
    partial class FrmTraPhong
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            this.tabMain = new System.Windows.Forms.TabControl();
            this.tabXuLy = new System.Windows.Forms.TabPage();
            this.tabLichSu = new System.Windows.Forms.TabPage();
            this.lblField1 = new System.Windows.Forms.Label();
            this.cboDat = new System.Windows.Forms.ComboBox();
            this.lblField2 = new System.Windows.Forms.Label();
            this.cboNV = new System.Windows.Forms.ComboBox();
            this.btnTai = new System.Windows.Forms.Button();
            this.dgvPhong = new System.Windows.Forms.DataGridView();
            this.dgvTN = new System.Windows.Forms.DataGridView();
            this.dgvDBChon = new System.Windows.Forms.DataGridView();
            this.lblField3 = new System.Windows.Forms.Label();
            this.txtSoDB = new System.Windows.Forms.TextBox();
            this.lblField4 = new System.Windows.Forms.Label();
            this.cboMucDo = new System.Windows.Forms.ComboBox();
            this.lblField5 = new System.Windows.Forms.Label();
            this.numDenBu = new System.Windows.Forms.NumericUpDown();
            this.btnThemDB = new System.Windows.Forms.Button();
            this.btnBoDB = new System.Windows.Forms.Button();
            this.btnLapDB = new System.Windows.Forms.Button();
            this.lblField6 = new System.Windows.Forms.Label();
            this.txtSoHD = new System.Windows.Forms.TextBox();
            this.lblField7 = new System.Windows.Forms.Label();
            this.numSoNgay = new System.Windows.Forms.NumericUpDown();
            this.btnLapHD = new System.Windows.Forms.Button();
            this.dgvHD = new System.Windows.Forms.DataGridView();
            this.lblField8 = new System.Windows.Forms.Label();
            this.cboHT = new System.Windows.Forms.ComboBox();
            this.lblField9 = new System.Windows.Forms.Label();
            this.numTienTT = new System.Windows.Forms.NumericUpDown();
            this.btnThanhToan = new System.Windows.Forms.Button();
            this.btnTraPhong = new System.Windows.Forms.Button();
            this.lblField10 = new System.Windows.Forms.Label();
            this.lblField11 = new System.Windows.Forms.Label();
            this.dgvDB = new System.Windows.Forms.DataGridView();
            this.dgvTT = new System.Windows.Forms.DataGridView();
            this.btnDong = new System.Windows.Forms.Button();
            this.dgvPhong_SoPhong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPhong_DonGiaNgay = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTN_MaTienNghi = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTN_TenLoaiTN = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTN_TinhTrangHienTai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDBChon_MaTienNghi = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDBChon_MucDoThietHai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDBChon_SoTien = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvHD_SoHoaDon = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvHD_SoPhieuDat = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvHD_TienPhong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvHD_TienDichVu = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvHD_TongTien = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvHD_ConLai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvHD_TrangThai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDB_SoPhieuDenBu = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDB_SoPhong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDB_MaTienNghi = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDB_MucDoThietHai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDB_SoTien = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTT_MaThanhToan = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTT_SoHoaDon = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTT_NgayThanhToan = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTT_HinhThuc = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvTT_SoTien = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tabMain.SuspendLayout();
            this.tabXuLy.SuspendLayout();
            this.tabLichSu.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTN)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDBChon)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDenBu)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSoNgay)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvHD)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numTienTT)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDB)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTT)).BeginInit();
            this.SuspendLayout();
            // tabMain
            this.tabMain.Location = new System.Drawing.Point(12, 12);
            this.tabMain.Size = new System.Drawing.Size(1156, 734);
            this.tabMain.Name = "tabMain";
            this.tabMain.TabIndex = 0;
            // tabXuLy
            this.tabXuLy.Location = new System.Drawing.Point(4, 27);
            this.tabXuLy.Size = new System.Drawing.Size(1148, 703);
            this.tabXuLy.Name = "tabXuLy";
            this.tabXuLy.TabIndex = 1;
            this.tabXuLy.Text = "Trả phòng / Thanh toán";
            this.tabXuLy.BackColor = System.Drawing.SystemColors.Control;
            this.tabXuLy.Padding = new System.Windows.Forms.Padding(8);
            // tabLichSu
            this.tabLichSu.Location = new System.Drawing.Point(4, 27);
            this.tabLichSu.Size = new System.Drawing.Size(1148, 703);
            this.tabLichSu.Name = "tabLichSu";
            this.tabLichSu.TabIndex = 2;
            this.tabLichSu.Text = "Lịch sử đền bù / thanh toán";
            this.tabLichSu.BackColor = System.Drawing.SystemColors.Control;
            this.tabLichSu.Padding = new System.Windows.Forms.Padding(8);
            // lblField1
            this.lblField1.Location = new System.Drawing.Point(15, 18);
            this.lblField1.Size = new System.Drawing.Size(105, 24);
            this.lblField1.Name = "lblField1";
            this.lblField1.TabIndex = 3;
            this.lblField1.Text = "Phiếu đang ở:";
            this.lblField1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboDat
            this.cboDat.Location = new System.Drawing.Point(120, 15);
            this.cboDat.Size = new System.Drawing.Size(240, 28);
            this.cboDat.Name = "cboDat";
            this.cboDat.TabIndex = 4;
            this.cboDat.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboDat.FormattingEnabled = true;
            // lblField2
            this.lblField2.Location = new System.Drawing.Point(455, 18);
            this.lblField2.Size = new System.Drawing.Size(85, 24);
            this.lblField2.Name = "lblField2";
            this.lblField2.TabIndex = 5;
            this.lblField2.Text = "Nhân viên:";
            this.lblField2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboNV
            this.cboNV.Location = new System.Drawing.Point(540, 15);
            this.cboNV.Size = new System.Drawing.Size(240, 28);
            this.cboNV.Name = "cboNV";
            this.cboNV.TabIndex = 6;
            this.cboNV.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboNV.FormattingEnabled = true;
            // btnTai
            this.btnTai.Location = new System.Drawing.Point(960, 14);
            this.btnTai.Size = new System.Drawing.Size(155, 32);
            this.btnTai.Name = "btnTai";
            this.btnTai.TabIndex = 7;
            this.btnTai.Text = "Tải lại";
            this.btnTai.UseVisualStyleBackColor = true;
            // dgvPhong
            this.dgvPhong.Location = new System.Drawing.Point(15, 64);
            this.dgvPhong.Size = new System.Drawing.Size(275, 174);
            this.dgvPhong.Name = "dgvPhong";
            this.dgvPhong.TabIndex = 8;
            this.dgvPhong.AllowUserToAddRows = false;
            this.dgvPhong.AllowUserToDeleteRows = false;
            this.dgvPhong.AutoGenerateColumns = false;
            this.dgvPhong.ReadOnly = true;
            this.dgvPhong.MultiSelect = false;
            this.dgvPhong.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPhong.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPhong.BackgroundColor = System.Drawing.Color.White;
            this.dgvPhong.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvPhong.RowHeadersWidth = 28;
            this.dgvPhong.EnableHeadersVisualStyles = false;
            this.dgvPhong.ColumnHeadersHeight = 30;
            this.dgvPhong.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvPhongHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvPhongHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvPhongHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvPhong.ColumnHeadersDefaultCellStyle = dgvPhongHeader;
            this.dgvPhong.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvPhong_SoPhong, this.dgvPhong_DonGiaNgay });
            // dgvTN
            this.dgvTN.Location = new System.Drawing.Point(309, 64);
            this.dgvTN.Size = new System.Drawing.Size(390, 174);
            this.dgvTN.Name = "dgvTN";
            this.dgvTN.TabIndex = 9;
            this.dgvTN.AllowUserToAddRows = false;
            this.dgvTN.AllowUserToDeleteRows = false;
            this.dgvTN.AutoGenerateColumns = false;
            this.dgvTN.ReadOnly = true;
            this.dgvTN.MultiSelect = false;
            this.dgvTN.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvTN.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvTN.BackgroundColor = System.Drawing.Color.White;
            this.dgvTN.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvTN.RowHeadersWidth = 28;
            this.dgvTN.EnableHeadersVisualStyles = false;
            this.dgvTN.ColumnHeadersHeight = 30;
            this.dgvTN.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvTNHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvTNHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvTNHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvTN.ColumnHeadersDefaultCellStyle = dgvTNHeader;
            this.dgvTN.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvTN_MaTienNghi, this.dgvTN_TenLoaiTN, this.dgvTN_TinhTrangHienTai });
            // dgvDBChon
            this.dgvDBChon.Location = new System.Drawing.Point(719, 64);
            this.dgvDBChon.Size = new System.Drawing.Size(396, 174);
            this.dgvDBChon.Name = "dgvDBChon";
            this.dgvDBChon.TabIndex = 10;
            this.dgvDBChon.AllowUserToAddRows = false;
            this.dgvDBChon.AllowUserToDeleteRows = false;
            this.dgvDBChon.AutoGenerateColumns = false;
            this.dgvDBChon.ReadOnly = true;
            this.dgvDBChon.MultiSelect = false;
            this.dgvDBChon.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDBChon.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDBChon.BackgroundColor = System.Drawing.Color.White;
            this.dgvDBChon.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvDBChon.RowHeadersWidth = 28;
            this.dgvDBChon.EnableHeadersVisualStyles = false;
            this.dgvDBChon.ColumnHeadersHeight = 30;
            this.dgvDBChon.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvDBChonHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvDBChonHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvDBChonHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvDBChon.ColumnHeadersDefaultCellStyle = dgvDBChonHeader;
            this.dgvDBChon.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvDBChon_MaTienNghi, this.dgvDBChon_MucDoThietHai, this.dgvDBChon_SoTien });
            // lblField3
            this.lblField3.Location = new System.Drawing.Point(15, 262);
            this.lblField3.Size = new System.Drawing.Size(110, 24);
            this.lblField3.Name = "lblField3";
            this.lblField3.TabIndex = 11;
            this.lblField3.Text = "Phiếu đền bù:";
            this.lblField3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtSoDB
            this.txtSoDB.Location = new System.Drawing.Point(125, 259);
            this.txtSoDB.Size = new System.Drawing.Size(155, 28);
            this.txtSoDB.Name = "txtSoDB";
            this.txtSoDB.TabIndex = 12;
            this.txtSoDB.MaxLength = 120;
            // lblField4
            this.lblField4.Location = new System.Drawing.Point(302, 262);
            this.lblField4.Size = new System.Drawing.Size(75, 24);
            this.lblField4.Name = "lblField4";
            this.lblField4.TabIndex = 13;
            this.lblField4.Text = "Mức độ:";
            this.lblField4.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboMucDo
            this.cboMucDo.Location = new System.Drawing.Point(377, 259);
            this.cboMucDo.Size = new System.Drawing.Size(185, 28);
            this.cboMucDo.Name = "cboMucDo";
            this.cboMucDo.TabIndex = 14;
            this.cboMucDo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboMucDo.FormattingEnabled = true;
            // lblField5
            this.lblField5.Location = new System.Drawing.Point(590, 262);
            this.lblField5.Size = new System.Drawing.Size(65, 24);
            this.lblField5.Name = "lblField5";
            this.lblField5.TabIndex = 15;
            this.lblField5.Text = "Số tiền:";
            this.lblField5.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numDenBu
            this.numDenBu.Location = new System.Drawing.Point(655, 259);
            this.numDenBu.Size = new System.Drawing.Size(140, 28);
            this.numDenBu.Name = "numDenBu";
            this.numDenBu.TabIndex = 16;
            this.numDenBu.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numDenBu.ThousandsSeparator = true;
            this.numDenBu.Enabled = false;
            // btnThemDB
            this.btnThemDB.Location = new System.Drawing.Point(820, 257);
            this.btnThemDB.Size = new System.Drawing.Size(140, 32);
            this.btnThemDB.Name = "btnThemDB";
            this.btnThemDB.TabIndex = 17;
            this.btnThemDB.Text = "Thêm đền bù";
            this.btnThemDB.UseVisualStyleBackColor = true;
            // btnBoDB
            this.btnBoDB.Location = new System.Drawing.Point(977, 257);
            this.btnBoDB.Size = new System.Drawing.Size(138, 32);
            this.btnBoDB.Name = "btnBoDB";
            this.btnBoDB.TabIndex = 18;
            this.btnBoDB.Text = "Bỏ dòng";
            this.btnBoDB.UseVisualStyleBackColor = true;
            // btnLapDB
            this.btnLapDB.Location = new System.Drawing.Point(915, 300);
            this.btnLapDB.Size = new System.Drawing.Size(200, 32);
            this.btnLapDB.Name = "btnLapDB";
            this.btnLapDB.TabIndex = 19;
            this.btnLapDB.Text = "Lập phiếu đền bù";
            this.btnLapDB.UseVisualStyleBackColor = true;
            // lblField6
            this.lblField6.Location = new System.Drawing.Point(15, 350);
            this.lblField6.Size = new System.Drawing.Size(110, 24);
            this.lblField6.Name = "lblField6";
            this.lblField6.TabIndex = 20;
            this.lblField6.Text = "Số hóa đơn:";
            this.lblField6.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // txtSoHD
            this.txtSoHD.Location = new System.Drawing.Point(125, 347);
            this.txtSoHD.Size = new System.Drawing.Size(170, 28);
            this.txtSoHD.Name = "txtSoHD";
            this.txtSoHD.TabIndex = 21;
            this.txtSoHD.MaxLength = 120;
            // lblField7
            this.lblField7.Location = new System.Drawing.Point(335, 350);
            this.lblField7.Size = new System.Drawing.Size(145, 24);
            this.lblField7.Name = "lblField7";
            this.lblField7.TabIndex = 22;
            this.lblField7.Text = "Số ngày tính tiền:";
            this.lblField7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numSoNgay
            this.numSoNgay.Location = new System.Drawing.Point(480, 347);
            this.numSoNgay.Size = new System.Drawing.Size(100, 28);
            this.numSoNgay.Name = "numSoNgay";
            this.numSoNgay.TabIndex = 23;
            this.numSoNgay.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numSoNgay.ThousandsSeparator = true;
            // btnLapHD
            this.btnLapHD.Location = new System.Drawing.Point(660, 345);
            this.btnLapHD.Size = new System.Drawing.Size(160, 32);
            this.btnLapHD.Name = "btnLapHD";
            this.btnLapHD.TabIndex = 24;
            this.btnLapHD.Text = "Lập hóa đơn";
            this.btnLapHD.UseVisualStyleBackColor = true;
            // dgvHD
            this.dgvHD.Location = new System.Drawing.Point(15, 395);
            this.dgvHD.Size = new System.Drawing.Size(1100, 153);
            this.dgvHD.Name = "dgvHD";
            this.dgvHD.TabIndex = 25;
            this.dgvHD.AllowUserToAddRows = false;
            this.dgvHD.AllowUserToDeleteRows = false;
            this.dgvHD.AutoGenerateColumns = false;
            this.dgvHD.ReadOnly = true;
            this.dgvHD.MultiSelect = false;
            this.dgvHD.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvHD.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvHD.BackgroundColor = System.Drawing.Color.White;
            this.dgvHD.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvHD.RowHeadersWidth = 28;
            this.dgvHD.EnableHeadersVisualStyles = false;
            this.dgvHD.ColumnHeadersHeight = 30;
            this.dgvHD.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvHDHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvHDHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvHDHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvHD.ColumnHeadersDefaultCellStyle = dgvHDHeader;
            this.dgvHD.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvHD_SoHoaDon, this.dgvHD_SoPhieuDat, this.dgvHD_TienPhong, this.dgvHD_TienDichVu, this.dgvHD_TongTien, this.dgvHD_ConLai, this.dgvHD_TrangThai });
            // lblField8
            this.lblField8.Location = new System.Drawing.Point(15, 574);
            this.lblField8.Size = new System.Drawing.Size(90, 24);
            this.lblField8.Name = "lblField8";
            this.lblField8.TabIndex = 26;
            this.lblField8.Text = "Hình thức:";
            this.lblField8.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // cboHT
            this.cboHT.Location = new System.Drawing.Point(105, 571);
            this.cboHT.Size = new System.Drawing.Size(160, 28);
            this.cboHT.Name = "cboHT";
            this.cboHT.TabIndex = 27;
            this.cboHT.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboHT.FormattingEnabled = true;
            // lblField9
            this.lblField9.Location = new System.Drawing.Point(305, 574);
            this.lblField9.Size = new System.Drawing.Size(70, 24);
            this.lblField9.Name = "lblField9";
            this.lblField9.TabIndex = 28;
            this.lblField9.Text = "Số tiền:";
            this.lblField9.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // numTienTT
            this.numTienTT.Location = new System.Drawing.Point(375, 571);
            this.numTienTT.Size = new System.Drawing.Size(165, 28);
            this.numTienTT.Name = "numTienTT";
            this.numTienTT.TabIndex = 29;
            this.numTienTT.Maximum = new decimal(new int[] { 1000000000, 0, 0, 0 });
            this.numTienTT.ThousandsSeparator = true;
            // btnThanhToan
            this.btnThanhToan.Location = new System.Drawing.Point(570, 569);
            this.btnThanhToan.Size = new System.Drawing.Size(160, 32);
            this.btnThanhToan.Name = "btnThanhToan";
            this.btnThanhToan.TabIndex = 30;
            this.btnThanhToan.Text = "Thanh toán";
            this.btnThanhToan.UseVisualStyleBackColor = true;
            // btnTraPhong
            this.btnTraPhong.Location = new System.Drawing.Point(755, 569);
            this.btnTraPhong.Size = new System.Drawing.Size(220, 32);
            this.btnTraPhong.Name = "btnTraPhong";
            this.btnTraPhong.TabIndex = 31;
            this.btnTraPhong.Text = "Hoàn tất trả phòng";
            this.btnTraPhong.UseVisualStyleBackColor = true;
            // lblField10
            this.lblField10.Location = new System.Drawing.Point(15, 628);
            this.lblField10.Size = new System.Drawing.Size(1080, 24);
            this.lblField10.Name = "lblField10";
            this.lblField10.TabIndex = 32;
            this.lblField10.Text = "Hóa đơn = tiền phòng + dịch vụ. Đền bù theo phiếu riêng; tiền cọc chưa tự khấu trừ.";
            this.lblField10.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // lblField11
            this.lblField11.Location = new System.Drawing.Point(15, 15);
            this.lblField11.Size = new System.Drawing.Size(1090, 24);
            this.lblField11.Name = "lblField11";
            this.lblField11.TabIndex = 33;
            this.lblField11.Text = "Lịch sử của phiếu đang chọn ở tab Trả phòng / Thanh toán";
            this.lblField11.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // dgvDB
            this.dgvDB.Location = new System.Drawing.Point(15, 55);
            this.dgvDB.Size = new System.Drawing.Size(1100, 260);
            this.dgvDB.Name = "dgvDB";
            this.dgvDB.TabIndex = 34;
            this.dgvDB.AllowUserToAddRows = false;
            this.dgvDB.AllowUserToDeleteRows = false;
            this.dgvDB.AutoGenerateColumns = false;
            this.dgvDB.ReadOnly = true;
            this.dgvDB.MultiSelect = false;
            this.dgvDB.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDB.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDB.BackgroundColor = System.Drawing.Color.White;
            this.dgvDB.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvDB.RowHeadersWidth = 28;
            this.dgvDB.EnableHeadersVisualStyles = false;
            this.dgvDB.ColumnHeadersHeight = 30;
            this.dgvDB.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvDBHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvDBHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvDBHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvDB.ColumnHeadersDefaultCellStyle = dgvDBHeader;
            this.dgvDB.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvDB_SoPhieuDenBu, this.dgvDB_SoPhong, this.dgvDB_MaTienNghi, this.dgvDB_MucDoThietHai, this.dgvDB_SoTien });
            // dgvTT
            this.dgvTT.Location = new System.Drawing.Point(15, 355);
            this.dgvTT.Size = new System.Drawing.Size(1100, 285);
            this.dgvTT.Name = "dgvTT";
            this.dgvTT.TabIndex = 35;
            this.dgvTT.AllowUserToAddRows = false;
            this.dgvTT.AllowUserToDeleteRows = false;
            this.dgvTT.AutoGenerateColumns = false;
            this.dgvTT.ReadOnly = true;
            this.dgvTT.MultiSelect = false;
            this.dgvTT.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvTT.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvTT.BackgroundColor = System.Drawing.Color.White;
            this.dgvTT.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.dgvTT.RowHeadersWidth = 28;
            this.dgvTT.EnableHeadersVisualStyles = false;
            this.dgvTT.ColumnHeadersHeight = 30;
            this.dgvTT.RowTemplate.Height = 27;
            System.Windows.Forms.DataGridViewCellStyle dgvTTHeader = new System.Windows.Forms.DataGridViewCellStyle();
            dgvTTHeader.BackColor = System.Drawing.Color.FromArgb(220, 231, 241);
            dgvTTHeader.ForeColor = System.Drawing.Color.FromArgb(35, 45, 55);
            this.dgvTT.ColumnHeadersDefaultCellStyle = dgvTTHeader;
            this.dgvTT.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.dgvTT_MaThanhToan, this.dgvTT_SoHoaDon, this.dgvTT_NgayThanhToan, this.dgvTT_HinhThuc, this.dgvTT_SoTien });
            // btnDong
            this.btnDong.Location = new System.Drawing.Point(1038, 751);
            this.btnDong.Size = new System.Drawing.Size(130, 32);
            this.btnDong.Name = "btnDong";
            this.btnDong.TabIndex = 36;
            this.btnDong.Text = "Đóng";
            this.btnDong.UseVisualStyleBackColor = true;
            this.dgvPhong_SoPhong.Name = "dgvPhong_SoPhong";
            this.dgvPhong_SoPhong.DataPropertyName = "SoPhong";
            this.dgvPhong_SoPhong.HeaderText = "Phòng";
            this.dgvPhong_SoPhong.ReadOnly = true;
            this.dgvPhong_DonGiaNgay.Name = "dgvPhong_DonGiaNgay";
            this.dgvPhong_DonGiaNgay.DataPropertyName = "DonGiaNgay";
            this.dgvPhong_DonGiaNgay.HeaderText = "Đơn giá/ngày";
            this.dgvPhong_DonGiaNgay.ReadOnly = true;
            this.dgvTN_MaTienNghi.Name = "dgvTN_MaTienNghi";
            this.dgvTN_MaTienNghi.DataPropertyName = "MaTienNghi";
            this.dgvTN_MaTienNghi.HeaderText = "Tiện nghi";
            this.dgvTN_MaTienNghi.ReadOnly = true;
            this.dgvTN_TenLoaiTN.Name = "dgvTN_TenLoaiTN";
            this.dgvTN_TenLoaiTN.DataPropertyName = "TenLoaiTN";
            this.dgvTN_TenLoaiTN.HeaderText = "Loại";
            this.dgvTN_TenLoaiTN.ReadOnly = true;
            this.dgvTN_TinhTrangHienTai.Name = "dgvTN_TinhTrangHienTai";
            this.dgvTN_TinhTrangHienTai.DataPropertyName = "TinhTrangHienTai";
            this.dgvTN_TinhTrangHienTai.HeaderText = "Tình trạng";
            this.dgvTN_TinhTrangHienTai.ReadOnly = true;
            this.dgvDBChon_MaTienNghi.Name = "dgvDBChon_MaTienNghi";
            this.dgvDBChon_MaTienNghi.DataPropertyName = "MaTienNghi";
            this.dgvDBChon_MaTienNghi.HeaderText = "Tiện nghi đền bù";
            this.dgvDBChon_MaTienNghi.ReadOnly = true;
            this.dgvDBChon_MucDoThietHai.Name = "dgvDBChon_MucDoThietHai";
            this.dgvDBChon_MucDoThietHai.DataPropertyName = "MucDoThietHai";
            this.dgvDBChon_MucDoThietHai.HeaderText = "Mức độ";
            this.dgvDBChon_MucDoThietHai.ReadOnly = true;
            this.dgvDBChon_SoTien.Name = "dgvDBChon_SoTien";
            this.dgvDBChon_SoTien.DataPropertyName = "SoTien";
            this.dgvDBChon_SoTien.HeaderText = "Số tiền";
            this.dgvDBChon_SoTien.ReadOnly = true;
            this.dgvHD_SoHoaDon.Name = "dgvHD_SoHoaDon";
            this.dgvHD_SoHoaDon.DataPropertyName = "SoHoaDon";
            this.dgvHD_SoHoaDon.HeaderText = "Hóa đơn";
            this.dgvHD_SoHoaDon.ReadOnly = true;
            this.dgvHD_SoPhieuDat.Name = "dgvHD_SoPhieuDat";
            this.dgvHD_SoPhieuDat.DataPropertyName = "SoPhieuDat";
            this.dgvHD_SoPhieuDat.HeaderText = "Phiếu đặt";
            this.dgvHD_SoPhieuDat.ReadOnly = true;
            this.dgvHD_TienPhong.Name = "dgvHD_TienPhong";
            this.dgvHD_TienPhong.DataPropertyName = "TienPhong";
            this.dgvHD_TienPhong.HeaderText = "Tiền phòng";
            this.dgvHD_TienPhong.ReadOnly = true;
            this.dgvHD_TienDichVu.Name = "dgvHD_TienDichVu";
            this.dgvHD_TienDichVu.DataPropertyName = "TienDichVu";
            this.dgvHD_TienDichVu.HeaderText = "Tiền dịch vụ";
            this.dgvHD_TienDichVu.ReadOnly = true;
            this.dgvHD_TongTien.Name = "dgvHD_TongTien";
            this.dgvHD_TongTien.DataPropertyName = "TongTien";
            this.dgvHD_TongTien.HeaderText = "Tổng tiền";
            this.dgvHD_TongTien.ReadOnly = true;
            this.dgvHD_ConLai.Name = "dgvHD_ConLai";
            this.dgvHD_ConLai.DataPropertyName = "ConLai";
            this.dgvHD_ConLai.HeaderText = "Còn lại";
            this.dgvHD_ConLai.ReadOnly = true;
            this.dgvHD_TrangThai.Name = "dgvHD_TrangThai";
            this.dgvHD_TrangThai.DataPropertyName = "TrangThai";
            this.dgvHD_TrangThai.HeaderText = "Trạng thái";
            this.dgvHD_TrangThai.ReadOnly = true;
            this.dgvDB_SoPhieuDenBu.Name = "dgvDB_SoPhieuDenBu";
            this.dgvDB_SoPhieuDenBu.DataPropertyName = "SoPhieuDenBu";
            this.dgvDB_SoPhieuDenBu.HeaderText = "Phiếu đền bù";
            this.dgvDB_SoPhieuDenBu.ReadOnly = true;
            this.dgvDB_SoPhong.Name = "dgvDB_SoPhong";
            this.dgvDB_SoPhong.DataPropertyName = "SoPhong";
            this.dgvDB_SoPhong.HeaderText = "Phòng";
            this.dgvDB_SoPhong.ReadOnly = true;
            this.dgvDB_MaTienNghi.Name = "dgvDB_MaTienNghi";
            this.dgvDB_MaTienNghi.DataPropertyName = "MaTienNghi";
            this.dgvDB_MaTienNghi.HeaderText = "Thiết bị";
            this.dgvDB_MaTienNghi.ReadOnly = true;
            this.dgvDB_MucDoThietHai.Name = "dgvDB_MucDoThietHai";
            this.dgvDB_MucDoThietHai.DataPropertyName = "MucDoThietHai";
            this.dgvDB_MucDoThietHai.HeaderText = "Mức độ";
            this.dgvDB_MucDoThietHai.ReadOnly = true;
            this.dgvDB_SoTien.Name = "dgvDB_SoTien";
            this.dgvDB_SoTien.DataPropertyName = "SoTien";
            this.dgvDB_SoTien.HeaderText = "Số tiền";
            this.dgvDB_SoTien.ReadOnly = true;
            this.dgvTT_MaThanhToan.Name = "dgvTT_MaThanhToan";
            this.dgvTT_MaThanhToan.DataPropertyName = "MaThanhToan";
            this.dgvTT_MaThanhToan.HeaderText = "Mã thanh toán";
            this.dgvTT_MaThanhToan.ReadOnly = true;
            this.dgvTT_SoHoaDon.Name = "dgvTT_SoHoaDon";
            this.dgvTT_SoHoaDon.DataPropertyName = "SoHoaDon";
            this.dgvTT_SoHoaDon.HeaderText = "Hóa đơn";
            this.dgvTT_SoHoaDon.ReadOnly = true;
            this.dgvTT_NgayThanhToan.Name = "dgvTT_NgayThanhToan";
            this.dgvTT_NgayThanhToan.DataPropertyName = "NgayThanhToan";
            this.dgvTT_NgayThanhToan.HeaderText = "Ngày thanh toán";
            this.dgvTT_NgayThanhToan.ReadOnly = true;
            this.dgvTT_HinhThuc.Name = "dgvTT_HinhThuc";
            this.dgvTT_HinhThuc.DataPropertyName = "HinhThuc";
            this.dgvTT_HinhThuc.HeaderText = "Hình thức";
            this.dgvTT_HinhThuc.ReadOnly = true;
            this.dgvTT_SoTien.Name = "dgvTT_SoTien";
            this.dgvTT_SoTien.DataPropertyName = "SoTien";
            this.dgvTT_SoTien.HeaderText = "Số tiền";
            this.dgvTT_SoTien.ReadOnly = true;
            this.Controls.Add(this.tabMain);
            this.tabMain.Controls.Add(this.tabXuLy);
            this.tabMain.Controls.Add(this.tabLichSu);
            this.tabXuLy.Controls.Add(this.lblField1);
            this.tabXuLy.Controls.Add(this.cboDat);
            this.tabXuLy.Controls.Add(this.lblField2);
            this.tabXuLy.Controls.Add(this.cboNV);
            this.tabXuLy.Controls.Add(this.btnTai);
            this.tabXuLy.Controls.Add(this.dgvPhong);
            this.tabXuLy.Controls.Add(this.dgvTN);
            this.tabXuLy.Controls.Add(this.dgvDBChon);
            this.tabXuLy.Controls.Add(this.lblField3);
            this.tabXuLy.Controls.Add(this.txtSoDB);
            this.tabXuLy.Controls.Add(this.lblField4);
            this.tabXuLy.Controls.Add(this.cboMucDo);
            this.tabXuLy.Controls.Add(this.lblField5);
            this.tabXuLy.Controls.Add(this.numDenBu);
            this.tabXuLy.Controls.Add(this.btnThemDB);
            this.tabXuLy.Controls.Add(this.btnBoDB);
            this.tabXuLy.Controls.Add(this.btnLapDB);
            this.tabXuLy.Controls.Add(this.lblField6);
            this.tabXuLy.Controls.Add(this.txtSoHD);
            this.tabXuLy.Controls.Add(this.lblField7);
            this.tabXuLy.Controls.Add(this.numSoNgay);
            this.tabXuLy.Controls.Add(this.btnLapHD);
            this.tabXuLy.Controls.Add(this.dgvHD);
            this.tabXuLy.Controls.Add(this.lblField8);
            this.tabXuLy.Controls.Add(this.cboHT);
            this.tabXuLy.Controls.Add(this.lblField9);
            this.tabXuLy.Controls.Add(this.numTienTT);
            this.tabXuLy.Controls.Add(this.btnThanhToan);
            this.tabXuLy.Controls.Add(this.btnTraPhong);
            this.tabXuLy.Controls.Add(this.lblField10);
            this.tabLichSu.Controls.Add(this.lblField11);
            this.tabLichSu.Controls.Add(this.dgvDB);
            this.tabLichSu.Controls.Add(this.dgvTT);
            this.Controls.Add(this.btnDong);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1180, 800);
            this.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.BackColor = System.Drawing.SystemColors.Control;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Name = "FrmTraPhong";
            this.Text = "Trả phòng - Đền bù - Hóa đơn - Thanh toán";
            this.Load += new System.EventHandler(this.FrmTraPhong_Load);
            this.tabMain.ResumeLayout(false);
            this.tabMain.PerformLayout();
            this.tabXuLy.ResumeLayout(false);
            this.tabXuLy.PerformLayout();
            this.tabLichSu.ResumeLayout(false);
            this.tabLichSu.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPhong)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTN)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDBChon)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numDenBu)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSoNgay)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvHD)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numTienTT)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDB)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTT)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();
        }
        private System.Windows.Forms.TabControl tabMain;
        private System.Windows.Forms.TabPage tabXuLy;
        private System.Windows.Forms.TabPage tabLichSu;
        private System.Windows.Forms.Label lblField1;
        private System.Windows.Forms.ComboBox cboDat;
        private System.Windows.Forms.Label lblField2;
        private System.Windows.Forms.ComboBox cboNV;
        private System.Windows.Forms.Button btnTai;
        private System.Windows.Forms.DataGridView dgvPhong;
        private System.Windows.Forms.DataGridView dgvTN;
        private System.Windows.Forms.DataGridView dgvDBChon;
        private System.Windows.Forms.Label lblField3;
        private System.Windows.Forms.TextBox txtSoDB;
        private System.Windows.Forms.Label lblField4;
        private System.Windows.Forms.ComboBox cboMucDo;
        private System.Windows.Forms.Label lblField5;
        private System.Windows.Forms.NumericUpDown numDenBu;
        private System.Windows.Forms.Button btnThemDB;
        private System.Windows.Forms.Button btnBoDB;
        private System.Windows.Forms.Button btnLapDB;
        private System.Windows.Forms.Label lblField6;
        private System.Windows.Forms.TextBox txtSoHD;
        private System.Windows.Forms.Label lblField7;
        private System.Windows.Forms.NumericUpDown numSoNgay;
        private System.Windows.Forms.Button btnLapHD;
        private System.Windows.Forms.DataGridView dgvHD;
        private System.Windows.Forms.Label lblField8;
        private System.Windows.Forms.ComboBox cboHT;
        private System.Windows.Forms.Label lblField9;
        private System.Windows.Forms.NumericUpDown numTienTT;
        private System.Windows.Forms.Button btnThanhToan;
        private System.Windows.Forms.Button btnTraPhong;
        private System.Windows.Forms.Label lblField10;
        private System.Windows.Forms.Label lblField11;
        private System.Windows.Forms.DataGridView dgvDB;
        private System.Windows.Forms.DataGridView dgvTT;
        private System.Windows.Forms.Button btnDong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_SoPhong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPhong_DonGiaNgay;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTN_MaTienNghi;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTN_TenLoaiTN;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTN_TinhTrangHienTai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDBChon_MaTienNghi;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDBChon_MucDoThietHai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDBChon_SoTien;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvHD_SoHoaDon;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvHD_SoPhieuDat;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvHD_TienPhong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvHD_TienDichVu;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvHD_TongTien;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvHD_ConLai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvHD_TrangThai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDB_SoPhieuDenBu;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDB_SoPhong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDB_MaTienNghi;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDB_MucDoThietHai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDB_SoTien;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTT_MaThanhToan;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTT_SoHoaDon;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTT_NgayThanhToan;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTT_HinhThuc;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvTT_SoTien;
    }
}
