namespace QuanLyBanHang.Forms {
 partial class FrmOrderResult {
  private System.ComponentModel.IContainer components = null;
  protected override void Dispose(bool disposing) {
   if(disposing && components!=null)components.Dispose();
   base.Dispose(disposing);
  }
  private void InitializeComponent() {
            this.lblTitle = new System.Windows.Forms.Label();
            this.dgvOrders = new System.Windows.Forms.DataGridView();
            this.dgvOrders_MaDH = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvOrders_NgayTao = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvOrders_TenTrangThai = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvOrders_TongTien = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvOrders_EmailStatus = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.lblLines = new System.Windows.Forms.Label();
            this.dgvLines = new System.Windows.Forms.DataGridView();
            this.dgvLines_MaSP = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLines_TenSP = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLines_SoLuong = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLines_DonGia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvLines_ThanhTien = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.lblInfo = new System.Windows.Forms.Label();
            this.btnReload = new System.Windows.Forms.Button();
            this.btnReconcile = new System.Windows.Forms.Button();
            this.btnEmail = new System.Windows.Forms.Button();
            this.btnReadEmail = new System.Windows.Forms.Button();
            this.btnClose = new System.Windows.Forms.Button();
            this.chkEmailFail = new System.Windows.Forms.CheckBox();
            ((System.ComponentModel.ISupportInitialize)(this.dgvOrders)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLines)).BeginInit();
   this.SuspendLayout();
            // lblTitle
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Location = new System.Drawing.Point(25, 15);
            this.lblTitle.Size = new System.Drawing.Size(940, 42);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "ĐƠN HÀNG CỦA TÔI";
            this.lblTitle.Font = new System.Drawing.Font("Segoe UI", 18F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.FromArgb(17, 60, 104);
            // dgvOrders
            this.dgvOrders.Name = "dgvOrders";
            this.dgvOrders.Location = new System.Drawing.Point(25, 75);
            this.dgvOrders.Size = new System.Drawing.Size(950, 210);
            this.dgvOrders.TabIndex = 1;
            this.dgvOrders.ReadOnly = true;
            this.dgvOrders.AllowUserToAddRows = false;
            this.dgvOrders.AllowUserToDeleteRows = false;
            this.dgvOrders.AutoGenerateColumns = false;
            this.dgvOrders.MultiSelect = false;
            this.dgvOrders.RowHeadersVisible = false;
            this.dgvOrders.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvOrders.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvOrders.BackgroundColor = System.Drawing.Color.White;
            this.dgvOrders.EnableHeadersVisualStyles = false;
            this.dgvOrders.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(232, 239, 244);
            this.dgvOrders.ColumnHeadersHeight = 32;
            this.dgvOrders.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.dgvOrders_MaDH.Name = "dgvOrders_MaDH";
            this.dgvOrders_MaDH.DataPropertyName = "MaDH";
            this.dgvOrders_MaDH.HeaderText = "Mã đơn";
            this.dgvOrders_MaDH.FillWeight = 155F;
            this.dgvOrders_MaDH.ReadOnly = true;
            this.dgvOrders.Columns.Add(this.dgvOrders_MaDH);
            this.dgvOrders_NgayTao.Name = "dgvOrders_NgayTao";
            this.dgvOrders_NgayTao.DataPropertyName = "NgayTao";
            this.dgvOrders_NgayTao.HeaderText = "Ngày tạo";
            this.dgvOrders_NgayTao.FillWeight = 110F;
            this.dgvOrders_NgayTao.ReadOnly = true;
            this.dgvOrders_NgayTao.DefaultCellStyle.Format = "dd/MM/yyyy HH:mm";
            this.dgvOrders.Columns.Add(this.dgvOrders_NgayTao);
            this.dgvOrders_TenTrangThai.Name = "dgvOrders_TenTrangThai";
            this.dgvOrders_TenTrangThai.DataPropertyName = "TenTrangThai";
            this.dgvOrders_TenTrangThai.HeaderText = "Trạng thái";
            this.dgvOrders_TenTrangThai.FillWeight = 120F;
            this.dgvOrders_TenTrangThai.ReadOnly = true;
            this.dgvOrders.Columns.Add(this.dgvOrders_TenTrangThai);
            this.dgvOrders_TongTien.Name = "dgvOrders_TongTien";
            this.dgvOrders_TongTien.DataPropertyName = "TongTien";
            this.dgvOrders_TongTien.HeaderText = "Tổng tiền";
            this.dgvOrders_TongTien.FillWeight = 85F;
            this.dgvOrders_TongTien.ReadOnly = true;
            this.dgvOrders_TongTien.DefaultCellStyle.Format = "N0";
            this.dgvOrders_TongTien.DefaultCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            this.dgvOrders.Columns.Add(this.dgvOrders_TongTien);
            this.dgvOrders_EmailStatus.Name = "dgvOrders_EmailStatus";
            this.dgvOrders_EmailStatus.DataPropertyName = "EmailStatus";
            this.dgvOrders_EmailStatus.HeaderText = "Email";
            this.dgvOrders_EmailStatus.FillWeight = 80F;
            this.dgvOrders_EmailStatus.ReadOnly = true;
            this.dgvOrders.Columns.Add(this.dgvOrders_EmailStatus);
            // lblLines
            this.lblLines.Name = "lblLines";
            this.lblLines.Location = new System.Drawing.Point(25, 300);
            this.lblLines.Size = new System.Drawing.Size(800, 30);
            this.lblLines.TabIndex = 2;
            this.lblLines.Text = "Chi tiết đơn hàng";
            this.lblLines.Font = new System.Drawing.Font("Segoe UI", 13F, System.Drawing.FontStyle.Bold);
            this.lblLines.ForeColor = System.Drawing.Color.FromArgb(17, 60, 104);
            // dgvLines
            this.dgvLines.Name = "dgvLines";
            this.dgvLines.Location = new System.Drawing.Point(25, 340);
            this.dgvLines.Size = new System.Drawing.Size(950, 165);
            this.dgvLines.TabIndex = 3;
            this.dgvLines.ReadOnly = true;
            this.dgvLines.AllowUserToAddRows = false;
            this.dgvLines.AllowUserToDeleteRows = false;
            this.dgvLines.AutoGenerateColumns = false;
            this.dgvLines.MultiSelect = false;
            this.dgvLines.RowHeadersVisible = false;
            this.dgvLines.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvLines.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvLines.BackgroundColor = System.Drawing.Color.White;
            this.dgvLines.EnableHeadersVisualStyles = false;
            this.dgvLines.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(232, 239, 244);
            this.dgvLines.ColumnHeadersHeight = 32;
            this.dgvLines.AlternatingRowsDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.dgvLines_MaSP.Name = "dgvLines_MaSP";
            this.dgvLines_MaSP.DataPropertyName = "MaSP";
            this.dgvLines_MaSP.HeaderText = "Mã SP";
            this.dgvLines_MaSP.FillWeight = 65F;
            this.dgvLines_MaSP.ReadOnly = true;
            this.dgvLines.Columns.Add(this.dgvLines_MaSP);
            this.dgvLines_TenSP.Name = "dgvLines_TenSP";
            this.dgvLines_TenSP.DataPropertyName = "TenSP";
            this.dgvLines_TenSP.HeaderText = "Tên sản phẩm";
            this.dgvLines_TenSP.FillWeight = 180F;
            this.dgvLines_TenSP.ReadOnly = true;
            this.dgvLines.Columns.Add(this.dgvLines_TenSP);
            this.dgvLines_SoLuong.Name = "dgvLines_SoLuong";
            this.dgvLines_SoLuong.DataPropertyName = "SoLuong";
            this.dgvLines_SoLuong.HeaderText = "Số lượng";
            this.dgvLines_SoLuong.FillWeight = 70F;
            this.dgvLines_SoLuong.ReadOnly = true;
            this.dgvLines.Columns.Add(this.dgvLines_SoLuong);
            this.dgvLines_DonGia.Name = "dgvLines_DonGia";
            this.dgvLines_DonGia.DataPropertyName = "DonGia";
            this.dgvLines_DonGia.HeaderText = "Đơn giá";
            this.dgvLines_DonGia.FillWeight = 100F;
            this.dgvLines_DonGia.ReadOnly = true;
            this.dgvLines_DonGia.DefaultCellStyle.Format = "N0";
            this.dgvLines_DonGia.DefaultCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            this.dgvLines.Columns.Add(this.dgvLines_DonGia);
            this.dgvLines_ThanhTien.Name = "dgvLines_ThanhTien";
            this.dgvLines_ThanhTien.DataPropertyName = "ThanhTien";
            this.dgvLines_ThanhTien.HeaderText = "Thành tiền";
            this.dgvLines_ThanhTien.FillWeight = 100F;
            this.dgvLines_ThanhTien.ReadOnly = true;
            this.dgvLines_ThanhTien.DefaultCellStyle.Format = "N0";
            this.dgvLines_ThanhTien.DefaultCellStyle.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleRight;
            this.dgvLines.Columns.Add(this.dgvLines_ThanhTien);
            // lblInfo
            this.lblInfo.Name = "lblInfo";
            this.lblInfo.Location = new System.Drawing.Point(25, 520);
            this.lblInfo.Size = new System.Drawing.Size(950, 75);
            this.lblInfo.TabIndex = 4;
            this.lblInfo.Text = "Chọn đơn để xem người nhận, giao hàng và chi phí.";
            // btnReload
            this.btnReload.Name = "btnReload";
            this.btnReload.Location = new System.Drawing.Point(25, 630);
            this.btnReload.Size = new System.Drawing.Size(150, 38);
            this.btnReload.TabIndex = 5;
            this.btnReload.Text = "Tải lại";
            this.btnReload.UseVisualStyleBackColor = true;
            // btnReconcile
            this.btnReconcile.Name = "btnReconcile";
            this.btnReconcile.Location = new System.Drawing.Point(200, 630);
            this.btnReconcile.Size = new System.Drawing.Size(210, 38);
            this.btnReconcile.TabIndex = 6;
            this.btnReconcile.Text = "Đối soát thanh toán";
            this.btnReconcile.UseVisualStyleBackColor = true;
            // btnEmail
            this.btnEmail.Name = "btnEmail";
            this.btnEmail.Location = new System.Drawing.Point(435, 630);
            this.btnEmail.Size = new System.Drawing.Size(165, 38);
            this.btnEmail.TabIndex = 7;
            this.btnEmail.Text = "Thử gửi email";
            this.btnEmail.UseVisualStyleBackColor = true;
            // btnReadEmail
            this.btnReadEmail.Name = "btnReadEmail";
            this.btnReadEmail.Location = new System.Drawing.Point(625, 630);
            this.btnReadEmail.Size = new System.Drawing.Size(200, 38);
            this.btnReadEmail.TabIndex = 8;
            this.btnReadEmail.Text = "Xem email xác nhận";
            this.btnReadEmail.UseVisualStyleBackColor = true;
            // btnClose
            this.btnClose.Name = "btnClose";
            this.btnClose.Location = new System.Drawing.Point(820, 690);
            this.btnClose.Size = new System.Drawing.Size(155, 38);
            this.btnClose.TabIndex = 9;
            this.btnClose.Text = "Đóng";
            this.btnClose.UseVisualStyleBackColor = true;
            // chkEmailFail
            this.chkEmailFail.Name = "chkEmailFail";
            this.chkEmailFail.Location = new System.Drawing.Point(25, 690);
            this.chkEmailFail.Size = new System.Drawing.Size(450, 28);
            this.chkEmailFail.TabIndex = 10;
            this.chkEmailFail.Text = "Giả lập dịch vụ email lỗi";
            this.chkEmailFail.AutoSize = true;
            this.Controls.Add(this.lblTitle);
            this.Controls.Add(this.dgvOrders);
            this.Controls.Add(this.lblLines);
            this.Controls.Add(this.dgvLines);
            this.Controls.Add(this.lblInfo);
            this.Controls.Add(this.btnReload);
            this.Controls.Add(this.btnReconcile);
            this.Controls.Add(this.btnEmail);
            this.Controls.Add(this.btnReadEmail);
            this.Controls.Add(this.btnClose);
            this.Controls.Add(this.chkEmailFail);
   this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
   this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
   this.ClientSize = new System.Drawing.Size(1000, 750);
   this.Font = new System.Drawing.Font("Segoe UI", 9F);
   this.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
   this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
   this.MaximizeBox = false;
   this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
   this.Text = "Đơn hàng của tôi";
   this.Name = "FrmOrderResult";
   this.Load += new System.EventHandler(this.FrmOrderResult_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvOrders)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvLines)).EndInit();
   this.ResumeLayout(false);
   this.PerformLayout();
  }
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.DataGridView dgvOrders;
        private System.Windows.Forms.Label lblLines;
        private System.Windows.Forms.DataGridView dgvLines;
        private System.Windows.Forms.Label lblInfo;
        private System.Windows.Forms.Button btnReload;
        private System.Windows.Forms.Button btnReconcile;
        private System.Windows.Forms.Button btnEmail;
        private System.Windows.Forms.Button btnReadEmail;
        private System.Windows.Forms.Button btnClose;
        private System.Windows.Forms.CheckBox chkEmailFail;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvOrders_MaDH;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvOrders_NgayTao;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvOrders_TenTrangThai;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvOrders_TongTien;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvOrders_EmailStatus;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLines_MaSP;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLines_TenSP;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLines_SoLuong;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLines_DonGia;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvLines_ThanhTien;
 }
}
